### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by apfelbox** [webpack-contrib/terser-webpack-plugin#1]
Hi,

I know you're probably busy with setting everything up, but is the plugin ready to be published to npm?
Can you estimate, when the first release will be?

Thanks for your great work 💪

**Comment by evilebottnawi** [comment]
@apfelbox Today i will do `1.0.0` release :+1:

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v1.0.0 feel free to feedback and report about problems
