### ISSUE TITLE
Source map + minimizer results in silent failure

### ISSUE THREAD

**Issue by underflow00** [webpack-contrib/terser-webpack-plugin#100]
- Operating System: Win 10
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.35.0
- terser-webpack-plugin Version: 1.3.0

### Expected Behavior
Using source map with minimizer created a minified file with a source map.

### Actual Behavior
Using source map with minimizer causes silent failure. Output file not created. No console output.

### How Do We Reproduce?
1. Create empty file `1.js`
2. Create `webpack.config.js` file with contents:
```
const TerserPlugin = require('terser-webpack-plugin');
module.exports = {
    devtool:  'source-map',
    entry: './1.js',
    resolve: {
        extensions: ['.js']
    },
    output: {
        filename: 'main.js',
        path: __dirname,
    },
    optimization: {
        minimize: true,
        minimizer: [
            new TerserPlugin({
                sourceMap: true,
            }),
        ],
    }
};
```
3. Run `webpack --config webpack.config.js`

**Comment by underflow00** [comment]
It works after downgrading terser-webpack-plugin to v1.2.4. Something to do with the terser upgrade? Or is it a caching problem?

**Comment by wallzero** [comment]
I am running into this as well. It looks like #101 is also.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
Looks like problem in terser

**Comment by evilebottnawi** [comment]
@p3x-robot thanks, i will look on this in near future

**Comment by evilebottnawi** [comment]
Problem in latest terser release https://github.com/terser-js/terser/pull/382

**Comment by underflow00** [comment]
That terser issue won't be fixed anytime soon. You should revert it here.

**Comment by evilebottnawi** [comment]
Closed, update deps
