### ISSUE TITLE
Minification inadvertently converts ISO-8859-1 non-ASCII characters to UTF-8

### ISSUE THREAD

**Issue by SetTrend** [webpack-contrib/terser-webpack-plugin#107]
- Operating System: Windows 10x64
- Node Version: v10.3.0
- NPM Version: 6.1.0
- webpack Version: 4.35.0
- terser-webpack-plugin Version: coming with webpack

### Expected Behavior

Minifying string literals in a UTF-8 Javascript file should not alter the text's non-ASCII characters.

### Actual Behavior

Non-ASCII characters in a string literal from a UTF-8 JavaScript file are inadvertently converted to their UTF-8 counterparts.

### Code

See [this sample repository](/SetTrend/encoding-issue).

### How Do We Reproduce?

See above.

**Comment by evilebottnawi** [comment]
hm, looks like a terser bug, can you try compress file without webpack plugin and check all fine or not?

**Comment by SetTrend** [comment]
@evilebottnawi :

Would you mind elaborating on how I would do that? I'm not too deep into WebPack at this time, I'm afraid.

**Comment by evilebottnawi** [comment]
@SetTrend install `terser` https://github.com/terser-js/terser and try to use CLI for compress file, also can you try `ascii_only` option https://github.com/terser-js/terser#output-options

**Comment by SetTrend** [comment]
I just did as you suggested and ran the proposed test. It looks like `terser` is the issue here, indeed:
<br/>

Running ...

```batch
npx tsc
```

results in these four files:

![Dist result](https://user-images.githubusercontent.com/9283914/62085329-97334b00-b25b-11e9-9a6f-88e558260410.png)

With `TestUC.js` displaying the following content:

![TSC encoding](https://user-images.githubusercontent.com/9283914/62086181-d9f62280-b25d-11e9-87ef-d5f367560058.png)

(Which is fine until that point.)
<br/>

Then running ...

```batch
npx terser "dist/*.js" -c -m -o "dist2/test.js"
```

results in this file:

![Dist2-Result](https://user-images.githubusercontent.com/9283914/62086835-eed3b580-b25f-11e9-95d7-680281f0f20f.png)

With `test.js` displaying the following content:

![Terser encoding](https://user-images.githubusercontent.com/9283914/62086718-8f75a580-b25f-11e9-8928-fec9478bc5d3.png)
<br/>

What would you suggest how to proceed?

**Comment by evilebottnawi** [comment]
@SetTrend i can't understand, bug exists in terser? Why do you use `ISO 8859-1`? escm spec allow using utf-8 only for scripts (latest)

**Comment by SetTrend** [comment]
@evilebottnawi :

That's not the case. Let me iterate:

- The JavaScript source _is_ UTF-8, as you can see from the screenshots. There's a control character in the string literals, that's all. Yet, control characters in string literals _should not_ be altered.

- Regardless, and although it's irrelevant to this issue: the ECMAScript specification (latest) doesn't set any restrictions to JavaScript source code encoding:
   > 10 - ECMAScript Language: Source Code
   > 10.1 - Source Text
   > [...]
   > The actual encodings used to store and interchange ECMAScript source text is not relevant to this specification.
<br/>

What Terser does: It actually interprets the literal strings' encoding, concludes from the control character within the string literals that the string literals must be `ISO 8895-1` and converts what it believes to have found into `UTF-8`. That's false behaviour. Instead, in general, string literals must be left untouched.

No matter what character points a string literal contains, Terser must render it 1:1, unchanged.

**Comment by evilebottnawi** [comment]
@SetTrend i think better open issue in `terser` repo, we just wrapper for this tool, i think we can't do something on our side

**Comment by endiliey** [comment]
agree that it is an issue in terser.

**Comment by SetTrend** [comment]
@evilebottnawi, @endiliey 

I just noticed that the Terser `ascii_only` option is not supported by webpack-contrib/terser-webpack-plugin. Would you mind adding it?

**Comment by evilebottnawi** [comment]
You can set any custom options for terser using https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions

**Comment by evilebottnawi** [comment]
`output: { ascii_only: true }`
