### ISSUE TITLE
OOM when set parallel to true

### ISSUE THREAD

**Issue by Miaoxingren** [webpack-contrib/terser-webpack-plugin#115]
- Operating System: tlinux
- Node Version: v10
- NPM Version: v6
- webpack Version: v4
- terser-webpack-plugin Version: 1.3.0

### Expected Behavior
Finish without OOM.

### Actual Behavior
OOM.

### How Do We Reproduce?
Please check at this issue [OOM when generating 10000 pages ](https://github.com/nuxt/nuxt.js/issues/6110)

**Comment by evilebottnawi** [comment]
What is OOM?

**Comment by Miaoxingren** [comment]
Out of memory.

**Comment by evilebottnawi** [comment]
@Miaoxingren please create minimum reproducible test repo, some projects really big and you need increase node memory

**Comment by Miaoxingren** [comment]
I create this [demo](https://codesandbox.io/embed/pymmj2r9x7) and found out there are more than one node process when set parallel to true. Check this [issue](https://github.com/nuxt/nuxt.js/issues/6110#issuecomment-519818043), I wnat to know why I got so many node process.

**Comment by evilebottnawi** [comment]
@Miaoxingren because you set parallel? You can change number of parallel process using option

**Comment by evilebottnawi** [comment]
> Default number of concurrent runs: os.cpus().length - 1.

**Comment by Miaoxingren** [comment]
@evilebottnawi Tks, I got it. I should set an appropriate number to prevent OOM.
