### ISSUE TITLE
Propagate errors from Terser

### ISSUE THREAD

**Issue by fabiosantoscode** [webpack-contrib/terser-webpack-plugin#116]
- Operating System: Linux x64
- Node Version: 12.5.0
- NPM Version: 6.10.2
- webpack Version: 4.38.0
- terser-webpack-plugin Version: 1.4.1

### Feature Proposal

To help users and Terser contributors debug Terser issues when Terser is called by this package and crashes, when Terser crashes, an indication that it was Terser that crashed, not this project, and a Terser stack trace should be printed out. 

### Feature Use Case

This would help users and Terser contributors understand Terser crashes a bit better. This would also be helpful to avoid issues being erroneously opened in this repository in case Terser crashes.

**Comment by evilebottnawi** [comment]
:+1: thanks

**Comment by evilebottnawi** [comment]
@fabiosantoscode just for infromation how we can reproduce problem in terser :smile: Maybe just invalid code?

**Comment by fabiosantoscode** [comment]
Right, I forgot!

```
function BackgroundPosition(config) {
    var getBackgroundPosition = function () {
        var backgroundDivision = 123;
        var backgroundOriginPosition = 555 + backgroundDivision * 123;

        config.foo = backgroundDivision;

        return backgroundOriginPosition;
    };
    var x = getBackgroundPosition();
}
 
```

This needs to be compressed with `evaluate: false` in the compress options, and it will make Terser's current version crash.

**Comment by fabiosantoscode** [comment]
The bug has been fixed so you'll have to stick to 4.1.3 :)

**Comment by evilebottnawi** [comment]
I can't reproduce situation where we don't show stack trace from terser when bug happens, maybe somebody can provide reproducible test repo?

**Comment by fabiosantoscode** [comment]
@evilebottnawi I noticed you need to enable the `parallel` option to see this. Sorry for not letting you know before.

**Comment by evilebottnawi** [comment]
@fabiosantoscode hm, without parallel it is also work as expected, i can't reproduce :disappointed:

**Comment by evilebottnawi** [comment]
Done
