### ISSUE TITLE
Probable crash when using old Terser version (4.1.2)

### ISSUE THREAD

**Issue by michaljabi** [webpack-contrib/terser-webpack-plugin#117]
After last update of my Webpack and loader I noticed error which crashes my build and does not make new 'dist' build:

`ERROR in bundle.bf66c9212bfb8faf1c69.js from Terser
undefined`

That thing tells me nothing. But I figured (after over an h) that some of the plugin or webpack itself uses `terser-webpack-plugin` and it is installed in my `node_modules`

Nothing special - all ok, newest `1.4.1 `version of `terser-webpack-plugin`.

But then I saw you are using "old" dependency: `"terser": "^4.1.2"`.
and that my cause the error mentioned up there.

please notice a changes in next 4.1.3 and 4.1.4 version of terser: 
[https://github.com/terser-js/terser/blob/master/CHANGELOG.md](url)

Old version of Terser might cause that problem.
I cannot tell since this `ERROR - undefined` does not tell me much...

Im sure that this can be a problem because:

- this error only exist when I build production
- this error disappear when I use: 
```
 optimization: {
      minimize: false,
},
```
then, build is ok (is ok also when I use other minimizer - that is a fixture for now)

**Comment by evilebottnawi** [comment]
Please update terser to latest version, also please use issue template, your information is not enough to help you, this is the reason we ask to use templates, also problem can be on terser side, double check what you update lock files too, sorry

You can fill issue using template and i will help with problem, now i can't do something
