### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by Allain55** [webpack-contrib/terser-webpack-plugin#122]
- Operating System: Ubuntu 16.04
- Node Version: 12.9.1
- NPM Version: 6.10.2
- webpack Version: 4.39.2
- terser-webpack-plugin Version:  1.4.1

### Expected Behavior
Exclude option not excluding anything. Tried to put a console.log in a file in node modules directory then exclude the file, so the log should remain there but it's removed. If I remove the "drop_console" option from the config the log in the file is not removed.

### Code
```
new TerserPlugin({
	exclude: /node_modules/,
	cache: false,
	sourceMap: true,
	terserOptions: {
		compress: {
			drop_console: true
		}
	}
})
```

**Comment by evilebottnawi** [comment]
Please read what `exclude` means, it is expected,  `exclude` for excluding `assets`, not modules or them location

**Comment by evilebottnawi** [comment]
When you build app, you have `bundled` files, for example for each entry point, so exclude allow to you exclude bundled files, not modules
