### ISSUE TITLE
[2.0.0] Wrong minification

### ISSUE THREAD

**Issue by frlinw** [webpack-contrib/terser-webpack-plugin#149]
- Operating System: linux
- Node Version: 12.x
- terser webpack plugin: 2.0.0

### Expected Behavior

v1.4.1 behavior
![image](https://user-images.githubusercontent.com/11896237/64551134-b0d4b180-d334-11e9-904e-58c6640e6846.png)

### Actual Behavior

v2.0.0 behavior
![image](https://user-images.githubusercontent.com/11896237/64551006-6f440680-d334-11e9-9ca0-373b4cd5b244.png)
`syncQueueItems` is not replaced by its minified name `t`
Result in `ReferenceError: syncQueueItems is not defined`

### Code

Original code 
```js
try {
      const syncQueueItems = await this._getFromSyncQueue()
      const syncQueueItemsDeduplicated = []
      for (const { createdAt, modelName, primaryKey } of syncQueueItems) {
```

### How Do We Reproduce?

No minimal reproduction yet

**Comment by evilebottnawi** [comment]
Please open issue in `terser` package https://github.com/terser/terser

**Comment by fabiosantoscode** [comment]
Please update Terser to 4.3.1 which has been released to fix this issue.
