### ISSUE TITLE
extractComments option with custom banner has no effect

### ISSUE THREAD

**Issue by perry-mitchell** [webpack-contrib/terser-webpack-plugin#159]
- Operating System: Ubuntu 18
- Node Version: 10.15.0
- NPM Version: 6.4.1
- webpack Version: 4.39.3
- terser-webpack-plugin Version: 2.1.0

### Expected Behavior

I should be able to set a custom banner with the following:

```javascript
{
    optimization: {
        minimize: true,
        minimizer: [
            new TerserPlugin({
                parallel: 2,
                terserOptions: {
                    ecma: 5,
                    extractComments: {
                        banner: "Test Banner",
                        condition: /.*/
                    },
                    output: {
                        comments: /@copyright.+My Company/i
                    }
                }
            })
        ]
    },
  plugins: [
    new BannerPlugin(
      [
        "My Company",
        "@copyright My Company Ltd. - All rights reserved",
        "@see https://mycompany.com"
      ].join("\n")
    )
  ]
}
```

The following comment should be preserved, with **no others**:

```javascript
/*!
 * My Company Script
 * @copyright My Company Ltd. - All rights reserved
 */
```

### Actual Behavior

The expected comment block _is_ preserved, and others stripped, but an _additional_ banner is added before it:

```javascript
/*! For license information please see dynamic.development.js.LICENSE */
/*!
 * My Company Script
 * @copyright My Company Ltd. - All rights reserved
 */
```

There were other comments in the output _before_ I removed them using this config.

### Code

https://gist.github.com/perry-mitchell/977ed506907ac8b1be3249f6668462db

### How Do We Reproduce?

Configure the optimization block as in my config.

**Comment by perry-mitchell** [comment]
Even with `output.comments` set to `false` the `For license information please...` text still comes through.

**Comment by perry-mitchell** [comment]
Nevermind! Issue was confusion regarding which level of options I was on. Sorry!

**Comment by greggman** [comment]
Can you explain your confusing because I've spent the last hour trying to get a custom banner back I have no idea what "confusion regarding which level of options I was on" means
