### ISSUE TITLE
SyntaxError on optimized code

### ISSUE THREAD

**Issue by sirluis** [webpack-contrib/terser-webpack-plugin#160]
- Operating System: Manjaro 18.0.4
- Node Version: 8.16.0
- Yarn Version: 1.17.3
- webpack Version: 4.39.1
- terser-webpack-plugin Version: 2.1.0

### Expected Behavior
Optimized code should not contain syntax errors.

### Actual Behavior
Code transformed by terser is broken.
`SyntaxError: missing ) after argument list`

### Code
**babel.config.js**
https://gist.github.com/sirluis/acb158120257480dd5853b3a2c977382

**webpack.config.js**
https://gist.github.com/sirluis/65d1a6b257f451b2260f6c7f3330690b

```js
// Code before optimization
  return react["createElement"]("div", {
    className: Styles
  }, hasCustomers ? customers().map((shift, idx) => !!customers.lenght && react["createElement"]("div", {
    className: "".concat(AnotherStyle),
    key: customer.id,
    idx
  }
```

```js
// Broken Code
return r.createElement("div",
{
className:kl.Styles
},
()=>{
let e=!1;
return s().forEach(t=>{
t.customers.length&&(e=!0)
}),e} // Error is right after "e"
```

**Comment by evilebottnawi** [comment]
Please open issue in terser repo
/cc @fabiosantoscode

**Comment by sirluis** [comment]
The codebase is huge, I'll isolate the module, minify it using terser alone and open a issue on terser repo. tks

**Comment by sirluis** [comment]
@evilebottnawi  Where do I find the same terser options that the plugin uses by default? When I use terser alone the result is not the same.

**Comment by evilebottnawi** [comment]
@sirluis please create minimum reproducible test repo, we can't help you without code, we just wrapper around terser so any problem with minify result output terser

**Comment by fabiosantoscode** [comment]
It's possible to produce a reproduction of a compiler issue by gradually removing code. For example, go into your main file and remove an import, see if the syntax error occurs. If it does, you've just eliminated a lot of code out of your reproduction bundle.

The final code *does not*  need to be correct, useful or even run without runtime errors. It only needs to show this syntax error.

**Comment by fabiosantoscode** [comment]
But I find it unlikely that Terser would miss a paren when outputting a function call. That's simply not a possibility. Have you tried setting `parallel` to `false` in this plugin's options?

**Comment by sirluis** [comment]
I've found the issue. Someone forgot to call the function then the variable was replaced by the function itself.

```js
const isThisTrue = () { ... }
...
render () {
...
isThisTrue ? ... : ... // instead of isThisTrue()
}
```

The result:
```js
createElement("div",
{className:s.style},(
) => {
let e=!1;
return a().forEach(t=>{t.arr.length&&(e=!0)}),
e}
```
This was not caught by linter either :(.

**Comment by sirluis** [comment]
The babel output was correct btw.
```js
  return React.createElement("div", {
    className: s.style
  }, isThisTrue ? ... : ...
```
Terser is supposed to do this transformation?
Thanks @fabiosantoscode

**Comment by sirluis** [comment]
Weird that this does not trigger an error at build step.

**Comment by sirluis** [comment]
Terser is supposed to replace the content of the variable by the function itself?
