### ISSUE TITLE
Terser mangle option seems to cause lodash.chain() to break

### ISSUE THREAD

**Issue by crobinson42** [webpack-contrib/terser-webpack-plugin#162]
```
webpack@4.40.2
terser@4.3.1
terser-webpack-plugin@2.1.0
@babel/core@7.6.0
@babel/preset-env@7.6.0
lodash-es@4.17.15
```

The offending code:

```
import { chain, get, maxBy } from 'lodash-es'

chain([ {...} ])
      .maxBy('priority')
      .get('priority')
      .value()
```

```
TypeError: Object(...)(...).maxBy is not a function
```

I'm not sure where to begin to debug this issue but I have confirmed that using `mangle: false` option in `terser-webpack-plugin` configs resolves the issue and the code works fine. Any pointers on how to begin debugging this and which direction to go? thx!

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Also please open issue in terser repo, we just wrapper around this tool.

**Comment by crobinson42** [comment]
I didn’t delete the issue template - I chose the option for support since I’m not sure if this is a big and it’s definitely not a feature request. Was just looking for a point in some direction to debug so that I could figure out if I should open a big ticket. Thanks.
