### ISSUE TITLE
Unexpected token punc

### ISSUE THREAD

**Issue by yellow1912** [webpack-contrib/terser-webpack-plugin#163]
- Operating System: Ubuntu 16
- Node Version: 8.9.0
- NPM Version: 6.4.1
- webpack Version: 4.40.2
- terser-webpack-plugin Version: 1.4.1

### Expected Behavior

I'm trying to run terser with the basic configuration, I expected the resulted code to be processed correctly.

### Actual Behavior

I get the error unexpected token punc from Terser.

### Code

```
module.exports = {
  context: '/path',
  entry:
   { below_fold: '/path/entry.js' },
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        cache: true,
      }),
    ],
  },
  target: () => undefined
};
```

The reason for the above setting, is that I don't want the final output code to be wrapped inside anything, and according to webpack's document that should do the trick

> If a function is passed, then it will be called with the compiler as a parameter. Set target to a function if none of the predefined targets from the list above meet your needs.
> 
> For example, if you don't want any of the plugins applied:
> const options = {
> target: () => undefined
> };
> 
https://webpack.js.org/configuration/target/#function

Perhaps I miss understand how this should work?

### How Do We Reproduce?

Try the above config with any code, something as simple as console.log('here');

**Comment by evilebottnawi** [comment]
Can reproduce, please create minimum reproducible test repo

**Comment by yellow1912** [comment]
Hello,

I have created a repo with minimal code for testing here:

https://github.com/yellow1912/TerserTest

Please note that I use yarn, if that makes any difference.

**Comment by evilebottnawi** [comment]
Problem in webpack, not in plugin

**Comment by evilebottnawi** [comment]
@yellow1912 Why you use `target: () => undefined` in your case?

**Comment by yellow1912** [comment]
I was trying to get rid of the wrapper export code from webpack. But I think that option doesn't help anyone. Webpack still wraps it.

**Comment by evilebottnawi** [comment]
Yes, you can't remove webpack wrapper, it is not supported right now

**Comment by evilebottnawi** [comment]
this is intended for custom targets, so you need to add other plugins that fulfill the target plugins role. It doesn't make sense alone

maybe we should throw warning/error in this case, in my todo for webpack, problem is not in plugin
