### ISSUE TITLE
Cache files being created with restrictive permissions

### ISSUE THREAD

**Issue by coreyward** [webpack-contrib/terser-webpack-plugin#182]
- Operating System: macOS 10.14
- Node Version: 12
- NPM Version:
- webpack Version: 4.41
- terser-webpack-plugin Version: 1.4.1

### Expected Behavior

Files created under `node_modules/.cache/terser-webpack-plugin/` should be user-writable (0644) to allow for non-forced removal (e.g. `rm -r node_modules/.cache` should not prompt for confirmation).

### Actual Behavior

Files are being created with `r--r--r--` (0444) permissions under this folder. For example, in a project of mine, the following file had these permissions: `node_modules/.cache/terser-webpack-plugin/content-v2/sha512/40/71/f09a66d7d7b227c0260a6ff211bb02f5b83de212be8244943cc053c99afacb5463db160910c1a9c3dc093e11dcc419189a29632daaee893127f9029ef5b5`

### How Do We Reproduce?

I assume these files are created during the normal operation of the plugin. No other packages that I am using create these prompts, including other webpack plugins, suggesting the issue lie with the terser-webpack-plugin itself and not with the surrounding tooling.

**Comment by evilebottnawi** [comment]
Fixed for webpack@5, for webpack@4 we can't fix it due we don't have options for `cachable` for control permissions.
