### ISSUE TITLE
Unused module was transformed wrongly

### ISSUE THREAD

**Issue by reeli** [webpack-contrib/terser-webpack-plugin#184]
I imported `fn1` from fn.ts in index.ts, but I have a few unused modules in fn.ts. When I look into my bundle.js I see the parameter of `createNameCreator` was transformed to a variable `var name; name="Tony"`.

```typescript
// index.ts
import { fn1 } from "./fn";

fn1();
```

```typescript
// fn.ts
export const fn1 = () => console.log("fn1");

export const createNameCreator = (name: string) =>
  () => ({
    success: `${name}_success`,
    fail: `${name}_fail`,
  });

export const createName = createNameCreator("Tony");
```

![image](https://user-images.githubusercontent.com/8966348/69611889-b1deca80-1069-11ea-9b65-8788b6569480.png)

**Comment by evilebottnawi** [comment]
Not related to `terser-webpack-plugin`, sorry, it is minificator and he do not concatenate modules
