### ISSUE TITLE
Sourcemaps not working with minification

### ISSUE THREAD

**Issue by aulbach** [webpack-contrib/terser-webpack-plugin#187]
- Operating System: Windows10
- Node Version: v12.13.0
- NPM Version: 6.12.0
- webpack Version: 4.41.2
- terser-webpack-plugin Version: 1.4.1

### Expected Behavior

Sourcemap of typescript stack is logged on error.

### Actual Behavior

Sourcemaps logs stack of compiled javascript, which is useless for typescript application. It works, if we turn minification off.

### Code

No code needed

### How Do We Reproduce?

webpack.config.prod:
```
    devtool: 'source-map',
    optimization: {
        // Test
        minimize: false,
    },
```
--> turns minification off and makes that sourcemap is working.

This bug seems to come in with 1.4. (not sure, cause we jumped from 1.1 to 1.4)

There are other issues, which point to be valid for 2.1, too.

I will try to test, if the same bug happens with 2.1 and 1.3 and will report here.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, i can't understand problem `not working with minification`

**Comment by aulbach** [comment]
I'm sorry, we invested yesterday some hours to find out, what's not working.
For example, we tested it with 2.1, by using  `minimizer: [new TerserPlugin()],`, but same effect. We tried to turn off caching. And some more ideas. All ideas didn't change the outcome - see above.
What we didn't tried is to look, if the problem comes from terser itself. But because we had a solution for our problem and the project has no problem with a little bit longer code we decided to keep it currently as it is.
Eventually we will come back to this problem next year - no promise. But if, I promise to write about it here.

**Comment by casyalex** [comment]
@evilebottnawi 

Hi, I met the same issue. and i create the test repo.

[test repo](https://github.com/casyalex/tersor-issue)

**Comment by evilebottnawi** [comment]
@casyalex please remove `uglifyjs-webpack-plugin` and migrate on `terser-webpack-plugin@2`

**Comment by casyalex** [comment]
@ evilebottnawi 
I commit upgrade terser-webpack-plugin to v2.3.5 at test repo, still no luck.  And I downgrade to v1.1.0, it works..

**Comment by casyalex** [comment]
It happens when >=v1.4.0.

1.4.0 (2019-07-31)
Features
generate higher quality SourceMaps (#109) (9d777f0)

**Comment by evilebottnawi** [comment]
I will look at that tomorrow, thanks for the issue

**Comment by jrwpatterson** [comment]
@evilebottnawi an solutions to this? I have the same issue..

**Comment by casyalex** [comment]
My solution is use old version.

**Comment by amifor-wordschatz** [comment]
@evilebottnawi, 
I have the same problem - there is no sourcesContent field in sourcemap. Although, if I specify  in your function minify (minify.js), as it was before
"terserOptions.sourceMap = {
       content: inputSourceMap,
  }; " everything works well.
Maybe this problem can be solved by adding plugin's initialization parameter, depending on the value of which initialize terserOptions.sourceMap?

**Comment by CrossMountain** [comment]
> I'm sorry, we invested yesterday some hours to find out, what's not working.
> For example, we tested it with 2.1, by using `minimizer: [new TerserPlugin()],`, but same effect. We tried to turn off caching. And some more ideas. All ideas didn't change the outcome - see above.
> What we didn't tried is to look, if the problem comes from terser itself. But because we had a solution for our problem and the project has no problem with a little bit longer code we decided to keep it currently as it is.
> Eventually we will come back to this problem next year - no promise. But if, I promise to write about it here.

Can you share how to fix?

**Comment by CrossMountain** [comment]
@aulbach

**Comment by deepanshushukla** [comment]
Is this problem resolved properly ? 
I am facing it in the electron-forge app which is using webpack .
turning off minification doesn't look good as it increases the bundle size unnecessarily.
