### ISSUE TITLE
[SECURITY] Serialize-javascript needs an update

### ISSUE THREAD

**Issue by RDIL** [webpack-contrib/terser-webpack-plugin#188]
GitHub is raising security alerts because of the dependency path `react-scripts/terser-webpack-plugin/serialize-javascript`.  Please update to 2.1.1 to stop it.

**Comment by btzr-io** [comment]
>  This vulnerability is not affected on Node.js environment since Node.js's implementation of RegExp.prototype.toString() backslash-escapes all forward slashes in regular expressions.

**Comment by evilebottnawi** [comment]
Update deps and lock file

**Comment by RDIL** [comment]
@evilebottnawi can you please release so I can update it in react-scripts?

**Comment by evilebottnawi** [comment]
yes, near future

**Comment by willdurand** [comment]
@evilebottnawi would it be possible to backport the fix for this issue in `1.4.x`? Webpack 4 relies on the version `1.4` of this plugin.

**Comment by evilebottnawi** [comment]
@evilebottnawi i strongly recommend migrate on latest version, or just update lock file, if you update lock files problem disappears

**Comment by willdurand** [comment]
As I previously mentioned, the latest webpack version (`4.41.2`) relies on version `1.4.x` of this plugin: https://github.com/webpack/webpack/blob/v4.41.2/package.json#L28 so all webpack users will automatically pull the latest version `1.4.x` of this plugin, which is `1.4.1`.

Backporting the dependency update in this lib and releasing `1.4.2` will automatically make all webpack users safe. I don't think asking the webpack maintainers to update to the `v2` of this plugin in their `v4` branch is realistic but it seems fairly okay to release a new `1.4.x` version of this plugin.

WDYT?

**Comment by evilebottnawi** [comment]
Latest users get latest version so they are no affected, for current users i recommended update lock file, yes we can do backport, but it is transitive dependency so better solution is just update lock file

**Comment by willdurand** [comment]
> Latest users get latest version so they are no affected, for current users i recommended update lock file, yes we can do backport, but it is transitive dependency so better solution is just update lock file

I don't understand, installing the latest webpack version will NOT pull the version `2` of this lib because it is a transitive dependency. The version `1.4.1` of this plugin will pull `serialize-javascript` version `1.x`: https://github.com/webpack-contrib/terser-webpack-plugin/blob/aa12914c34f3eac7280052dad3de465a163630d7/package.json#L44

```
/tmp/test/test-webpack
❯ npm install webpack

> fsevents@1.2.9 install /private/tmp/test/test-webpack/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
[fsevents] Success: "/private/tmp/test/test-webpack/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote
npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/test/test-webpack/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/test/test-webpack/package.json'
npm WARN test-webpack No description
npm WARN test-webpack No repository field.
npm WARN test-webpack No README data
npm WARN test-webpack No license field.

+ webpack@4.41.2
added 390 packages from 216 contributors and audited 4224 packages in 11.516s
found 0 vulnerabilities


/tmp/test/test-webpack 12s
❯ npm ls serialize-javascript
/private/tmp/test/test-webpack
└─┬ webpack@4.41.2
  └─┬ terser-webpack-plugin@1.4.1
    └── serialize-javascript@1.9.1
```

**Comment by evilebottnawi** [comment]
Oh, i see, let's do it, WIP

**Comment by evilebottnawi** [comment]
@willdurand Done https://www.npmjs.com/package/terser-webpack-plugin

**Comment by willdurand** [comment]
awesome, thanks!
