### ISSUE TITLE
Build fails, missing package

### ISSUE THREAD

**Issue by mohojojo** [webpack-contrib/terser-webpack-plugin#197]
Since new release 1.4.3 jenkins build fails

npm WARN prepare removing existing node_modules/ before installation
npm ERR! code ETARGET
npm ERR! notarget No matching version found for terser-webpack-plugin@1.4.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by evilebottnawi** [comment]
All fine https://www.npmjs.com/package/terser-webpack-plugin, use default register or open issue in jenkins repo
