### ISSUE TITLE
Legacy teser-webpack-plugin security advisory

### ISSUE THREAD

**Issue by deepaktatineni** [webpack-contrib/terser-webpack-plugin#198]
https://github.com/advisories/GHSA-h9rv-jmmf-4pgx - update serialize-javascript version to >=2.1.1

**Comment by evilebottnawi** [comment]
Already fixed, please look at package.json before create issue

**Comment by deepaktatineni** [comment]
It's not fixed in webpack3 legacy branch. 

https://github.com/webpack-contrib/terser-webpack-plugin/blob/996a480d043a7d6c00065bb95eccd5b9d0ede89d/package.json#L46

Sorry, It is my mistake of titling the issue.

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/terser-webpack-plugin/blob/version-1/package.json#L44

**Comment by evilebottnawi** [comment]
Update your deps, please read how package mangers work

**Comment by deepaktatineni** [comment]
Sorry, but I am talking about https://www.npmjs.com/package/terser-webpack-plugin-legacy, not the terser-webpack-plugin

**Comment by evilebottnawi** [comment]
Legacy is not supported anymore, please update webpack to 4 version
