### ISSUE TITLE
Don't JSON.parse the output source map

### ISSUE THREAD

**Issue by fabiosantoscode** [webpack-contrib/terser-webpack-plugin#199]
- Operating System: N/A
- Node Version: N/A
- NPM Version: N/A
- webpack Version: N/A
- terser-webpack-plugin Version: N/A

### Feature Proposal

I've noticed that this plugin does a JSON.parse of the `map` output by Terser ([link](https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L440)). However, it's possible to ask Terser not to JSON.stringify it in the first place. Since some chunks can be over 1MB in size this could be quite beneficial.

Here's how Terser can yield source maps in object form.

```
> const terser = require('terser')
> const { map } = terser.minify(/*...*/, { sourceMap: { asObject: true } })
> typeof map
'object'
> Object.keys(map)
[ 'version', 'sources', 'names', 'mappings' ]
```

### Feature Use Case

The purpose is to use less memory and time when compressing.

**Comment by evilebottnawi** [comment]
Thanks, let's do it

**Comment by fabiosantoscode** [comment]
Awesome :D
