### ISSUE TITLE
Make extractComments API more consistent

### ISSUE THREAD

**Issue by bryanph** [webpack-contrib/terser-webpack-plugin#20]
* terser-webpack-plugin Version: 1.1.0

### Expected Behavior / Situation
passing

```
new TerserPlugin({
  extractComments: true
})
```

should behave the same as
```
new TerserPlugin({
  extractComments: {
    condition: true
  }
})
```

### Actual Behavior / Situation
The first case makes condition equal `some` and the second case makes condition equal `all`

### Modification Proposal
Modify the second case to also equal `some` (or vice-versa)

**Comment by evilebottnawi** [comment]
@bryanph it is breaking change and we can't change this right now. We can change this behavior in next major release.
