### ISSUE TITLE
Mangled variable name shadows other variable: async + keep_fnames 

### ISSUE THREAD

**Issue by felixscheinost** [webpack-contrib/terser-webpack-plugin#201]
- Operating System: macOS 10.14.6 Mojave
- Node Version: v12.12.0 `yarn node --version`
- NPM Version: yarn 1.19.1
- webpack Version: 4.41.2
- terser-webpack-plugin Version: 2.3.0

### Expected Behavior

When having `keep_fnames` turned on a mangled parameter name shouldn't shadow or be shadowed by a kept function name.

### Actual Behavior

Outer variable name is mangled to `t` which conflicts with inner function definition.

### Code

This example prints `[async] value of param1 should be 1, is: undefined`

```js
async function foo() {}

function testBug(param1 = 1) {
  return () => {
    console.log('[async] value of param1 should be 1, is:', param1)
    var t = () => {}
    t.abc = function() {}
    return t
  }
}

testBug()()
```

### How Do We Reproduce?

- Clone https://github.com/felixscheinost/debug-terser-async-keepfnames
- Run `yarn mangle_keepfnames && yarn run_async` 
   => `[async] value of param1 should be 1, is: undefined`

### 1. Generated Code

```js 
function() {
    var t = arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : 1;
    return function() {
        console.log("[async] value of param1 should be 1, is:", t);
         var t = function() {};
         return t.abc = function() {}, t
      }
 }
```

 => `params1` gets converted to `t` which shadows the inner `t` definition.

### 2. This is because of `keep_fnames`

- Run `yarn mangle && yarn run_async` where `{ mangle: true }` 
- The generated code is 

    ```js
   function() {
      var t = arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : 1;
      return function() {
         console.log("[async] value of param1 should be 1, is:", t);
          var n = function() {};
          return n.abc = function() {}, n
      }
    }()
    ```

  => `var t = ` gets renamed correctly to `n`

### 3. Removing the `async` from the function above also works

 - Run `yarn mangle_keepfnames && yarn run_sync`
 -  The generated code is
    ```js
     function() {
            var e = arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : 1;
            return function() {
                console.log("[sync] value of param1 should be 1, is:", e);
                var t = function() {};
                return t.abc = function() {}, t
            }
        }()
    ```

   => `var t` stays `var t` but `params1` now becomes `var e`

### 4. Manually applying terse to the output of webpack

   - Run `yarn no_minimize && (yarn --silent terser target/test_async.js --mangle keep_fnames | yarn node -)` which prints the correct value
    - The generated code is

     ```js
     function testBug() {
         var r = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 1;
        return function() {
            console.log("[async] value of param1 should be 1, is:", r);
            var t = function t() {};
            t.abc = function() {};
            return t
        }
      }
      ```

   => *This is different from the code generated in (1), but why?* 
   => this is the reason why I opened this issue here and not in the terse repo.

**Comment by evilebottnawi** [comment]
We just wrapper around `terser` https://github.com/terser/terser, please open issue in `terser` repo
