### ISSUE TITLE
 extractComments banner gets applied after webpack BannerPlugin

### ISSUE THREAD

**Issue by katywings** [webpack-contrib/terser-webpack-plugin#218]
- Operating System: Reactos
- Node Version: 12.15.0
- NPM Version: 6.13.4
- webpack Version: 4.41.6
- terser-webpack-plugin Version: 2.3.4

### Expected Behavior / Situation
extractComments prepends its banner before webpack BannerPlugin

### Actual Behavior / Situation
extractComments prepends its banner after webpack BannerPlugin (at the very start of the file)

Background: I use the BannerPlugin to add a bash anchor at the start of node files: https://github.com/witneyjs/witney/blob/master/lib/node/webpack.js#L98
Since the terser plugin adds its banner at the very beginning (before my bash anchor), this renders my anchor invalid.
src: https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L347

### Modification Proposal
Personally I will just disable the extractComments for my node build. This is more a info because I had to investigate it anyways since extractComments is enabled by default now :). If more peeps run into this problem maybe it could be improved by allowing to add a custom "append" function to the plugin config :).

**Comment by evilebottnawi** [comment]
I don't think using `BannerPlugin` for adding ash anchors is good idea, anyway let's fix it

**Comment by katywings** [comment]
@evilebottnawi Insane 😁, thanks a lot! Any way to donate you a beer or milkshake or something?

**Comment by evilebottnawi** [comment]
@katywings Yes, all my work paid from open collective https://opencollective.com/webpack, thanks
