### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by satazor** [webpack-contrib/terser-webpack-plugin#22]
* Operating System: MacOSX 10.12.6
* Node Version: v11.0.0
* NPM Version: 6.4.1
* webpack Version: 4.23.1
* terser-webpack-plugin Version: 1.1.0

### Expected Behavior

Builds finishes

### Actual Behavior

Crashes with out of memory

### Code

Not applicable

### How Do We Reproduce?

Hard to provide, but it happens on big apps.

-----------------------------

The app I'm working crashes with out of memory when compiling. If I disable the minification, it finishes. This seems to be related with https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/276. Perhaps we can port that fix here?

**Comment by evilebottnawi** [comment]
@satazor sometimes you really have big app and you need increase memory nodejs usage, without minimum reproducible test repo i can't answer what exactly happens, https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/276/files was ported already

**Comment by satazor** [comment]
I can give you a reproducible test case, I’m flying home but I will provide it once I can, hopefully later today!

**Comment by satazor** [comment]
For some reason, the project is now compiling! Perhaps I was running a older version of terser.
If this happens again, I will reopen this.

Thanks @evilebottnawi
