### ISSUE TITLE
Bug when compile webpack 3

### ISSUE THREAD

**Issue by pietro-develcode** [webpack-contrib/terser-webpack-plugin#222]
- Operating System: Linux
- Node Version: v12.14.1
- NPM Version: 6.13.4
- webpack Version: 3.11.0
- terser-webpack-plugin Version: terser-webpack-plugin-legacy

I'm using webpack v3.11 and the docs of terser legacy says to use:

`optimization: {
    minimizer: [new TerserPlugin()],
  }`

But the docs of webpack says optimization were implemented since version 4.0 , so i tried and two ways to build my app but i cant minify my JS, can i do something ? i will put my code bellow.

`new webpack.LoaderOptionsPlugin({
      // test: /\.xxx$/, // may apply this only for some modules
      options: {
        optimization: {
          minimize: true,
          minimizer: [new TerserPlugin()]
        }
      }
    })
  ],`

`optimization: {
    minimizer: [new TerserPlugin()]
  }`

To reproduce just run webpack in version 3.11

**Comment by evilebottnawi** [comment]
Please update webpack to 4 version, we stop support webpack@3 and `terser-webpack-plugin-legacy`
