### ISSUE TITLE
How to prevent the creation of a LICENSE.txt file?

### ISSUE THREAD

**Issue by bugfixman** [webpack-contrib/terser-webpack-plugin#229]
Hello! I don't want the LICENSE.txt file to be created after compilation. Can i prevent this? The banner parameter with the value "false" didn't solve this problem.

Sorry. My english is not good enough. I hope that you understood me.

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter for future questions.

https://github.com/webpack-contrib/terser-webpack-plugin#remove-comments

**Comment by bugfixman** [comment]
> Please use stackoverflow or gitter for future questions.
> 
> https://github.com/webpack-contrib/terser-webpack-plugin#remove-comments

This settings not prevent creates a file. Because i was created an issue. I was read documentation before ask a question. On stackoverflow i could get examples from documentation only. How do you think stackoverflow will help me, If an example from documentation not gives a result?

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by james-ingold** [comment]
@bugfixman make sure you have both comment: false and extractComments: false. I tested and this set-up does prevent the file from being created.

**Comment by evilebottnawi** [comment]
Example - https://github.com/webpack-contrib/terser-webpack-plugin#remove-comments

**Comment by dhilt** [comment]
Here's the guide:

 - install `terser-webpack-plugin` (if you don't have): `npm install --save-dev terser-webpack-plugin`
 - import it to the webpack config: `const TerserPlugin = require('terser-webpack-plugin');`
 - add `optimization` field to the top level of the config object:

```js
  optimization: {
    minimizer: [new TerserPlugin({ extractComments: false })],
  },
```
