### ISSUE TITLE
transfer special character generate error

### ISSUE THREAD

**Issue by jackiewillen** [webpack-contrib/terser-webpack-plugin#232]
- Operating System: MacOs
- Node Version:10.15.3
- NPM Version:6.4.1
- webpack Version:4.41.4
- terser-webpack-plugin Version:1.4.1

### Expected Behavior
var region = {"\u0014":1, "\u0015": 2, "\u0016": ["\u001a", "\u001b"]};

been transfer to 
var region = {"\\u0014":1, "\\u0015": 2, "\\u0016": ["\\u001a", "\\u001b"]};

### Actual Behavior
sometimes,It will be tranfer to 
var region = {"<0x14>":1, "<0x15>": 2, "<0x16>":  ["<0x1a>", "<0x1b>"]};

<0x1b> will generate error on some versions of chrome browser.
and <0x14> <0x15> and so on cannot  display on the page because it is mechine code the browser can not read.

**Comment by evilebottnawi** [comment]
Can you create reproducible test repo? 

> sometimes,It will be tranfer to

there is no magic

**Comment by evilebottnawi** [comment]
Yep, it is terser problem https://github.com/terser/terser/issues/678, should be fixed in `4.16.13`, feel free to leave feedback

**Comment by fabiosantoscode** [comment]
That release is out in a few seconds.

**Comment by jackiewillen** [comment]
@evilebottnawi @fabiosantoscode

**Comment by evilebottnawi** [comment]
@jackiewillen if you still have an issue, please open a new issue in terser repo, thanks
