### ISSUE TITLE
Output files are not written and Node process doesn't end after updating to v3.0.0

### ISSUE THREAD

**Issue by jens-duttke** [webpack-contrib/terser-webpack-plugin#241]
I've just updated from v2.3.6 to v3.0.0, and now the production-build process doesn't end and the files are not written to the output folder.
That means it simply stops at the end, without to end the webpack/Node process.
I'm also using the BundleAnalyzerPlugin, which correctly show the expected files, but they are simply not there.
There is no error message shown in the build process.

- Operating System: Windows 10 Pro / Version 1809 (Build 17763.1158)
- Node Version: v13.6.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- terser-webpack-plugin Version: 3.0.0

### Expected Behavior

The output folder should be written with the generated files and the Node process should end.

### Actual Behavior

See above, the process doesn't end and the generated files are not written to the output folder.

### Code

My normal configuration:
```js
		optimization: {
			minimizer: [
				new TerserPlugin({
					extractComments: {
						condition: /^\**@preserve|@license|@cc_on/iu,
						filename: ({ filename }) => `${filename}.LICENSE`,
						banner: (licenseFile) => `License information can be found in ${licenseFile}`
					},
					terserOptions: {
						output: {
							preamble: `/** ${globals.appName} v${globals.appVersion} | (c) 2013, ${now.getFullYear()} ${pkg.author.name} <${pkg.author.email}> | ${pkg.license} */`,
							max_line_len: 10
						}
					}
				}),
				new OptimizeCSSAssetsPlugin({})
			],
```

I've also tried without `terserOptions` without and `extractComments` (separately) and only with `new TerserPlugin()`. As soon as `terserOptions` is not included, the process stops even earlier at:

```bash
* Webpack █████████████████████████ building (67%) 478/479 modules 1 active
 worker-loader » babel-loader » src\ts\App\components\Search\Search.worker.ts
```

### How Do We Reproduce?

That's a very good question. My repo is not public, so I'm not able to share the whole code base.
If I remove the TerserPlugin or use v2.3.6 every works fine.

Using Webpack in verbose mode, also doesn't show any interesting information to me.

Any idea what else I could provide or try to help you figuring out where the source of the problem could be?

**Comment by leosingleton** [comment]
I'm seeing the same issue when upgrading my project from v2.3.6 to v3.0.0 also.

Narrowing down my complex build configuration, I think it may be some sort of parallelism issue. Any time I have a webpack project with multiple configuration objects, it consistently hangs for me since upgrading to v3.0.0. Here's a simple repro environment:
https://github.com/leosingleton/terser-webpack-plugin-hang

If I comment out either of the two outputs, the build executes fine, but as is with both, webpack seems to consistently hang.

**Comment by evilebottnawi** [comment]
Very weird problem, I am investigating

**Comment by evilebottnawi** [comment]
Found
