### ISSUE TITLE
Map type cannot be optimized properly

### ISSUE THREAD

**Issue by zhaovbo** [webpack-contrib/terser-webpack-plugin#252]
- Operating System: macos 10.15.4
- Node Version: v12.6.3
- NPM Version:
- webpack Version: 4.23.0
- terser-webpack-plugin Version: 3.0.1

terser will optimize new Map () to new Map, causing the program to not run normally.
like this: for(var t=new Map,

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

If you think terser break your JS, please open a new issue in terser repo https://github.com/terser/terser
