### ISSUE TITLE
wget https://registry.npmjs.org/terser-webpack-plugin returns 403

### ISSUE THREAD

**Issue by ayxos** [webpack-contrib/terser-webpack-plugin#254]
- Operating System: Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
- Node Version: -
- NPM Version: - 
- webpack Version: -
- terser-webpack-plugin Version: 2.3.6

### Expected Behavior
not 403

### Actual Behavior
```
--2020-05-29 13:07:06--  https://registry.npmjs.org/terser-webpack-plugin
Resolving registry.npmjs.org (registry.npmjs.org)... 104.16.20.35, 104.16.23.35, 104.16.17.35, ...
Connecting to registry.npmjs.org (registry.npmjs.org)|104.16.20.35|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-05-29 13:07:06 ERROR 403: Forbidden.
```
Maybe our server has been blacklisted? 

### How Do We Reproduce?
On package.json we want:
`    "terser-webpack-plugin": "^2.3.6",`

```
$ wget https://registry.npmjs.org/terser-webpack-plugin

```

**Comment by evilebottnawi** [comment]
Please contact with `npm` for support

**Comment by Boulet-** [comment]
➡️ https://github.com/npm/cli/issues/1358
