### ISSUE TITLE
Arbitrary Code Injection In "serialize-javascript"

### ISSUE THREAD

**Issue by dargmuesli** [webpack-contrib/terser-webpack-plugin#255]
https://app.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-570062

> **Remediation**
> Upgrade serialize-javascript to version 3.1.0 or higher.

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v3.0.3
