### ISSUE TITLE
Provide Typings

### ISSUE THREAD

**Issue by junalmeida** [webpack-contrib/terser-webpack-plugin#26]
* Operating System: Windows
* Node Version: 9.8.0
* NPM Version: 6.4.1
* webpack Version: 4.25.1
* terser-webpack-plugin Version: 1.1.0

### Feature Proposal
Please provide Typescript bindings

### Feature Use Case
Use typings when using typescript for configuring webpack.

**Comment by thw0rted** [comment]
Note that this will also get you intellisense completion / error detection when using VSCode, provided your webpack config has proper type hinting applied (`@type` jsdoc comments, etc)

**Comment by evilebottnawi** [comment]
Out of scope repo, please create issue in `@types` repo. Example for `uglify` placed here https://www.npmjs.com/package/@types/uglifyjs-webpack-plugin

**Comment by thw0rted** [comment]
Typings may be maintained either in the package repo or in DefinitelyTyped -- plenty of popular packages aren't written in TS natively but maintain their own typings, like moment, postcss, localforage, ajv, source-map.... Having the DT community maintain typings has advantages, of course, and takes it off your plate, but keeping the typings in your own repo also has upsides you shouldn't dismiss out of hand. 

If you let somebody contribute typings here, your consumers only need to install one package to get good typings, they get better intellisense if they happen to use VSCode (or any other editor that understands them), and it's more immediately obvious when the typings start to drift out of sync with the implementation.  All things being equal, if I were going to put in a PR with typings, I think it would be better for the community if I did it here.

**Comment by evilebottnawi** [comment]
@thw0rted Disagree, we have a lot of plugins and loaders which should have types and it is increase maintenance (and we don't have enough contributors, developers very rare help OSS projects), other developers can use `flow` and we will have to lead these too, also not all developers have knowledge about `typescript` and/or `flow`, so it is should be external.
