### ISSUE TITLE
Map object cannot be optimized properly

### ISSUE THREAD

**Issue by zhaovbo** [webpack-contrib/terser-webpack-plugin#260]
- Operating System:Mac OS 13.1 or Centos 7.0
- Node Version:v12.3.1
- NPM Version:v6.14.4
- webpack Version:v4.23.0
- terser-webpack-plugin Version:v2.3.6

terser will always modify the code new Map() to new Map, remove the two brackets, causing the program to go wrong

**Comment by evilebottnawi** [comment]
Please open an issue in terser repo, we just wrapper for `terser`
