### ISSUE TITLE
Didn't get the result sesame I expected

### ISSUE THREAD

**Issue by failedUser** [webpack-contrib/terser-webpack-plugin#261]
my code 
`  CbkLog.prototype.initPvDot = function (isRepeat) {
          if (!('IntersectionObserver' in window &&
               'IntersectionObserverEntry' in window &&
               'intersectionRatio' in window.IntersectionObserverEntry.prototype)) {
               require('intersection-observer');
          }
          CbkLog.prototype.isRepeat = !!isRepeat;
     }`

after terser

`s.prototype.initPvDot = function(e) {
            var r = this;
            (!1 in t || !1 in t || !1 in t.IntersectionObserverEntry.prototype) && n(368),
            s.prototype.isRepeat = !!e
            }
            ))
        }`

I don't quite understand  `!1 in t` 

I'm not sure it's a terser problem...
terser: 4.4.0
terser-webpack-plugin: 1.4.1

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Update `terser-webpack-plugin` to latest version, if you still have a problem please open a new issue in `terser` repo
