### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by nashaofu** [webpack-contrib/terser-webpack-plugin#266]
- Operating System: Linux 3.10 Alpine Linux
- Node Version: 12.13.0
- NPM Version: 6.12.0
- webpack Version: 4.43.0
- terser-webpack-plugin Version: 3.0.6

### Expected Behavior

Do not expect to report an error

### Actual Behavior

![6FBE44BF-0499-4f8d-9D42-4A71390928A7](https://user-images.githubusercontent.com/19303058/86100873-00ff4900-baec-11ea-86b1-fea0c0f71976.png)

![image](https://user-images.githubusercontent.com/19303058/86100916-0c527480-baec-11ea-9062-c9c29e1e63e9.png)

### Code

```js
// webpack.config.js
module.exports = {
  optimization: {
    minimize: true,
    minimizer: [
      /* config.optimization.minimizer('terser') */
      new TerserPlugin({
        terserOptions: {
          parse: {
            ecma: 8
          },
          compress: {
            ecma: 5,
            warnings: false,
            comparisons: false,
            inline: 2
          },
          mangle: {
            safari10: true
          },
          output: {
            ecma: 5,
            comments: false,
            ascii_only: true
          }
        },
        parallel: true,
        cache: true,
        sourceMap: false
      })
    ]
  }
}
```

This problem should be caused by jest-worker, just like this https://github.com/facebook/jest/issues/10144

**Comment by evilebottnawi** [comment]
Problem with CirecleCI, it is described here https://github.com/webpack-contrib/terser-webpack-plugin#parallel, won't fix due incorrect behavior on CirecleCI
