### ISSUE TITLE
"Unexpected token {" with imported plugin

### ISSUE THREAD

**Issue by Rall3n** [webpack-contrib/terser-webpack-plugin#267]
- Operating System: Ubuntu 18, WSL2 Ubuntu 20
- Node Version: 8.17.0 / 8.10.0
- NPM Version: 6.13.4 / 6.4.1
- webpack Version: 4.43.0
- terser-webpack-plugin Version: 3.0.5 / 3.0.6

### Expected Behavior

When running `npx webpack` Webpack should build the bundles without errors.

### Actual Behavior

Webpack outputs `Unexpected token {` while having `terser-webpack-plugin` imported.
Had been tested on Windows before and there it works without issues.

### Code

```js
// webpack.config.js
const TerserPlugin = require('terser-webpack-plugin');
const path = require('path');

module.exports = {
    entry: './index.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
   }
};
```

### How Do We Reproduce?

* Create an empty project on a Ubuntu system
* Install:
  * `webpack` + `webpack-cli`
  * `terser-webpack-plugin`
* Create webpack config with above content
* Create at least an `index.js` in project root
* Run `npx webpack`
* See output mentioned above

**Comment by evilebottnawi** [comment]
We don't support 8.10.0 node, please look at https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/package.json#L16
