### ISSUE TITLE
TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by vamshia03** [webpack-contrib/terser-webpack-plugin#268]
- Operating System: Mac OS
- Node Version: 12.16.2
- NPM Version: 6.14.4
- webpack Version: 5.0.0-beta.18
- terser-webpack-plugin Version: 3.0.6

Webpack build throws the error "TypeError: The 'compilation' argument must be an instance of Compilation". Point to node_modules/terser-webpack-plugin/dist/index.js:526:67

This is the specific line: 
        const hooks = _webpack.javascript.JavascriptModulesPlugin.getCompilationHooks(compilation);
 
Any ideas why this is?

**Comment by evilebottnawi** [comment]
Do not ignore issue template, problem with invalid configuration, you put this plugin to the `resolve.plugins` option
