### ISSUE TITLE
WebPack won't build when I add terser-webpack-plugin

### ISSUE THREAD

**Issue by SaraCookk** [webpack-contrib/terser-webpack-plugin#269]
As soon as I import terser-webpack-plugin to my webpack config I get this error

/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:30
		} catch {}
		        ^

SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)

**Comment by fireswork** [comment]
"node": ">= 10.13.0"

**Comment by evilebottnawi** [comment]
Answer above
