### ISSUE TITLE
Remove js comments

### ISSUE THREAD

**Issue by kouga00** [webpack-contrib/terser-webpack-plugin#27]
Seems it's not possible to remove all comments when build but only extract these.

**Comment by kouga00** [comment]
I saw to remove all comments, add terserOption.output.comments to false:
`module.exports = {
optimization: {
      minimize: true,
      minimizer: [
        new TerserPlugin({
          cache: true, 
          parallel: true, 
          terserOptions: {
            output: {comments: false}
          }
        }),
      ]
    }
},`

**Comment by evilebottnawi** [comment]
@kouga00 it is expected, because some files can require copyright notation, what mean 'reviewing the documentation to improve this aspect'?

**Comment by kouga00** [comment]
I mean in documentation, those particular config is not specified enough (it's so hidden).
Maybe could be useful adding some examples like my config for somebody that needs to remove all comments.

**Comment by evilebottnawi** [comment]
@kouga00 feel free to send a PR to `Example` section :+1:

**Comment by evilebottnawi** [comment]
Done

**Comment by yyccQQu** [comment]
> @kouga00 feel free to send a PR to `Example` section 👍

please add example to npm.org
