### ISSUE TITLE
Debugging Javscript does not work because of wrong sourcemap

### ISSUE THREAD

**Issue by Allain55** [webpack-contrib/terser-webpack-plugin#270]
- Operating System: Ubuntu 16.04
- Node Version: 14.2.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- terser-webpack-plugin Version: 3.3.12

### Expected Behavior
I'd be able to debug Javascript generated by Webpack after minimalization using Chrome/Firefox Devtools

### Actual Behavior
I created a sample repository with a simple example to show the problem:
https://github.com/Allain55/terser_sourcemap/tree/master

First steps:
1, clone the repo, run npm install and npm run build
2, load the generated script from dist somewhere
3, open Chrome/Firefox Developer Tools
4, open terser.js in the Devtools
5, add a breakpoint to line 3
6, reload page

when using Chrome (83.0.4103.116) Devtools there are 2 problems:
- click on "Step over next function call" button => instead of going to line 4, you go to line 6

- click on "Step into next function call" button => you go to line 12. Click on it again: debugging stops

When using Firefox (77.0.1) Developer Tools:
- click on "Step over" button => instead of going to line 4, you go to line 6

Note: "Step in" button works as expected.

Turning off the minimize settings in Webpack solves the problem

### How Do We Reproduce?
Run "npm run build" in the test repository and follow the steps above

**Comment by evilebottnawi** [comment]
I think it is bug on terser side, we don't change source map, only pass them to `terser`, can you try to debug this without webpack, just uglify this using terser CLI?

**Comment by Allain55** [comment]
You're right, thank you!
