### ISSUE TITLE
Offer fine-grained control over `keep_fnames` (and other properties?)

### ISSUE THREAD

**Issue by Pet3ris** [webpack-contrib/terser-webpack-plugin#273]
### Feature Proposal

Proposal to include fine-grained control over which libraries, files or functions are affected by the `keep_fnames` flag.

### Feature Use Case

In my use case, one of my third-party dependencies uses references to class names and therefore breaks with renaming. I'd like to completely exclude this library or the specific file from `keep_fnames` without having to build a custom regex.

More here: https://github.com/webpack/webpack/issues/11174

**Comment by evilebottnawi** [comment]
@Pet3ris I think it's not exactly that repository, you need this https://github.com/terser/terser, we just plugin between webpack and terser

**Comment by Pet3ris** [comment]
Got it - thanks :)
