### ISSUE TITLE
Any way to support javascript-obfuscator's self defending mode ?

### ISSUE THREAD

**Issue by cameronbraid** [webpack-contrib/terser-webpack-plugin#278]
I would like to use `https://github.com/javascript-obfuscator`'s self defending mode.  Which makes the output code resilient against formating and variable renaming.

However if I use terser plugin as a wepack minimizer, the formatting changes breaking the code - as expected.

So what is needed is a way to get terser to ignore blocks of code when minimizing - possibly using start/end comment blocks ?  Then javascript-obfuscator can output these blocks to signial that the code should be left alone.

Is this something you would consider adding ?

Or is there an alternative way to do this ?

**Comment by cameronbraid** [comment]
I should mention that I dont use `javascript-obfuscator` on all my code - just selected modules via the `obfuscator-loader` webpack loader.

**Comment by evilebottnawi** [comment]
> Is this something you would consider adding ?

No, it is out of scope terser-webpack-plugin, you can create plugin for this, remember `obfuscator` is not help from stealing code, and an engineer will always figure out what is written, but it is reduce time execution, so you application/library will be slow. I do not recommend do it.
