### ISSUE TITLE
Error: Cannot find module 'terser'

### ISSUE THREAD

**Issue by AdrienLemaire** [webpack-contrib/terser-webpack-plugin#29]
* Operating System: Arch Linux, Travis CI, Ubuntu
* Node Version: 10.12.0
* NPM Version: 6.4.1
* webpack Version: 4.26.0	
* terser-webpack-plugin Version: 1.1.0

### Expected Behavior
Webpack builds without problem

### Actual Behavior
```
$ webpack -p --env=staging --progress
/home/dori/Projects/work/company/project/repo/node_modules/webpack-cli/bin/cli.js:244
                                throw err;
                                ^

Error: Cannot find module 'terser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/home/dori/Projects/work/company/project/repo/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/dori/Projects/work/company/project/repo/node_modules/terser-webpack-plugin/dist/minify.js:7:15)
    at Module._compile 
…
    at require (/home/dori/Projects/work/company/project/repo/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/dori/Projects/work/company/project/repo/node_modules/terser-webpack-plugin/dist/cjs.js:3:16)
    at Module._compile (/home/dori/Projects/work/company/project/repo/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Code

```js
  // webpack.config.js
import TerserPlugin from "terser-webpack-plugin";

…
export default {
  optimization: {
    minimizer: isProduction
      ? [
          new TerserPlugin({
            cache: true,
            extractComments: true,
            parallel: true,
            terserOptions: {
              toplevel: true,
              compress: {
                passes: 3,
                pure_getters: true,
                unsafe: false,
              },
            },
          }),
        ]
      : [],
    runtimeChunk: isProduction,
    splitChunks: isProduction ? {chunks: "all", maxSize: 1200000} : false,
  },
  …
};
```

### How Do We Reproduce?
What I noticed:
* only `terser-webpack-plugin": "1.1.0",` in package.json → fail
* also install `"terser": "3.10.11",` next to it → WORKS
* upgrade terser to 3.10.12 → fails

Checking your [package.json](https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/package.json#L50), I see a dependency to terser@^3.8.1

That raises 2 questions:
* Why do I need to install terser next to terser-webpack-plugin if the latter already has a version of terser in its dependencies ?
* If terser-webpack-plugin was relying on terser 3.8.X and subsequent minor releases added breaking changes, I'd understand, but how come v3.10.11 works and not 3.10.12 ?

**Comment by OverVlad** [comment]
I have similar problem when use `npm install` and npm version is 6.4.1

For yarn work fine

Error:
Could not list contents of `project/node_modules/.bin/terser-webpack-plugin/node_modules/.bin/terser'. Couldn't follow symbolic link.`

**Comment by mcsherrylabs** [comment]
@sischnei Did you figure it out?

**Comment by mvysny** [comment]
Deleting `node_modules`, `package.json`, `package-lock.json`, `tsconfig.json` and `types.d.ts` (a.k.a. Vaadin Dance) helped for me. https://stackoverflow.com/questions/77847333/webpack-fails-due-to-missing-terser-module-when-starting-vaadin-14-application
