### ISSUE TITLE
Error: Package exports for 'D:\development\project\node_modules\terser'  do not define a valid './package.json' target

### ISSUE THREAD

**Issue by jerptrs** [webpack-contrib/terser-webpack-plugin#299]
- Operating System: Win 10
- Node Version: 13.1.0
- NPM Version: 6.12.1
- webpack Version: 4.44.1
- terser-webpack-plugin Version: 4.1.0

While requiring the ``terser-webpack-plugin``, even in a ``.js`` file with ``const TerserWebpackPlugin = require('terser-webpack-plugin');`` I get the following error:

```Error: Package exports for 'D:\development\project\node_modules\terser' do not define a valid './package.json' target```

I have tried it on a new project with a basic ``webpack.config.js``, which didn't worked either. With version ``1.4.3`` it works without any issues. My package.json is the default which is created with ``npm init``.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Fill out all fields, I can't help you without information.

**Comment by jerptrs** [comment]
@evilebottnawi whoops 😱 yea you are right, sorry about that 😞✊

I restarted VSCode and ran ``npm remove`` + ``npm install``, seems to have fixed my issue 😎👍

**Comment by jerptrs** [comment]
Update:
I forgot I used an way older version (``1.4.3``) of the package, which works fine. 

I have added the repository where I'm having the issue.

**Comment by jerptrs** [comment]
@evilebottnawi could you take a look at the following code? Feeling pretty dumb right now because I can't figure my issue out.

webpack.config.js
```js
'use strict';
const path = require('path');
const webpack = require('webpack');
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
    context: path.resolve(__dirname, 'src'),

    entry: [
        './app.js'
    ],

    output: {
        filename: '/app.js',
        path: path.resolve(__dirname, 'dist'),
        publicPath: '../'
    },

    optimization: {
        minimize: true,
        minimizer: [new TerserPlugin()],
    },
}
```
package.json
```json
{
  "devDependencies": {
    "terser-webpack-plugin": "^4.1.0",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12"
  },
  "scripts": {
    "test": "webpack"
  }
```

src/app.js
```js
console.log('test');
```

**Comment by evilebottnawi** [comment]
Something breaks `node_modules`, maybe you have corrupted `node_modules` directory or file system, maybe you hard disk is starting dead

**Comment by jerptrs** [comment]
Tried it on my HDD and SSD, on both I get the same error. Like I said, with version ``1.4.3`` of ``terser-webpack-plugin`` it works fine.

**Comment by evilebottnawi** [comment]
It is the problem from `Node.js`, we can't fix it on our side

**Comment by jerptrs** [comment]
It is the Node.js version. Tried it with ``13.1.0`` on three machines and always got the same error but works fine with the latest Node.js version ``14.8.0``. There should be a warning that the current version f ``terser-webpack-plugin`` does not work with Node ``v13.1.0``.

**Comment by evilebottnawi** [comment]
Some version of `Node.js` can be broken, we can't list them all

**Comment by jerptrs** [comment]
Because you don't want to, am I right?

**Comment by evilebottnawi** [comment]
@jerptrs Don't want what? How I can help you? It is bug on node side https://github.com/nodejs/modules/issues/446, I can't fix it here, listing all requires testing on all versions, do you have time on this?

**Comment by jerptrs** [comment]
Oh fml - thought 13.1.0 was an LTS version since I used NVM 🤷 I'm sorry 😞
