### ISSUE TITLE
Optional Chaining Support

### ISSUE THREAD

**Issue by Druux** [webpack-contrib/terser-webpack-plugin#300]
- Operating System: macOS 10.15.4
- Node Version: 14.1.0
- NPM Version: 6.14.4
- webpack Version: 5.0.0-beta.27
- terser-webpack-plugin Version: 1.4.5

### Feature Proposal
Terser released version 5.2.0 the day before yesterday with important changes (including support for Optional Chaining). Do you think it's realistic to update the Terser dependency to version 5.2.0?

### Feature Use Case
Optional Chaining Support is a feature that has been in demand for some time as you can see [here](https://github.com/terser/terser/issues/567#issuecomment-675583347). The support would certainly make a lot easier for some people.

**Comment by evilebottnawi** [comment]
Latest version already use `terser@5`, just update deps

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/package.json#L51

**Comment by Druux** [comment]
@evilebottnawi Optional Chaining has been introduced in `terser@5.2.0` as stated in my post.

**Comment by evilebottnawi** [comment]
@Druux Do you know how semver works?

**Comment by TrySound** [comment]
This project allows any 5.* version. You can safely delete terser entry from your lockfile and run install to regenerate with the latest terser version.

**Comment by Druux** [comment]
Sorry, thats my bad - I skipped the caret for some reason. Wondering why I am still getting Optional Chaining errors. Will investigate on that.

**Comment by evilebottnawi** [comment]
@Druux webpack version?

**Comment by Druux** [comment]
Alright 100% my bad. Dropped the `terser-webpack-plugin` dep. for some reason and `webpack@5` depends on an older `terser-webpack-plugin` version. @evilebottnawi @TrySound thanks for pointing me in the right direction!
