### ISSUE TITLE
Option to apply drop_console flag only for third party modules (node_modules)

### ISSUE THREAD

**Issue by agammathur** [webpack-contrib/terser-webpack-plugin#305]
- Operating System: Ubuntu
- Node Version: 12.16.3
- NPM Version: 6.14.4
- webpack Version:4.43.0
- terser-webpack-plugin Version: 4.1.0

### Issue
I am using Webpack with Babel in my code and I want to remove statements like console.logs, console.error etc from my code for modules which are from 3rd party (i.e. node_modules). I tried using Terser plugin for this but it removes console.* statements even from my code, which I don't want. I want to just remove these statements from 3rd party code.

### Feature Proposal
We should provide an option to use drop_console flag on some specific files/paths such that we can cherry-pick file/paths on which we want or don't want to use drop_console functionality.

### Feature Use Case
This will allow users to remove console statements from specific modules/paths/files without affecting other parts of the project. This will be specifically useful for cases where we are using third party modules and are not interested in allowing them to log something on the console.

If this is possible currently then, please let me know the changes, I should do in my webpack.prod.js file:

`
const Dotenv = require('dotenv-webpack');
const ENVIRONMENT_VARIABLE = require('dotenv').config({ path: './.env.production' }).parsed;
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
    mode: 'production',
    devtool: 'source-map',
    plugins: [
        new Dotenv({
            path: './.env.production',
        })
    ],
    optimization: {
        minimizer: [
            new TerserPlugin({
                // Set to true if using source-maps in production
                sourceMap: true,
                terserOptions: {
                    // remove warnings
                    warnings: false,
                    output: {
                        // removing comments
                        comments: false,
                    },
                    compress: {
                        // remove console.logs
                        // Check environment variable 'REMOVE_CONSOLE_LOG' to decide whether should we remove console.logs or not.
                        drop_console: (ENVIRONMENT_VARIABLE.REMOVE_CONSOLE_LOG === '1') ? true : false,
                    },
                },
            }),
        ],
    },
};
`

**Comment by evilebottnawi** [comment]
Sorry it is impossible, we minify whole chunk(s) and we can't detect modules, anyway you can achieve this:
- using https://webpack.js.org/plugins/split-chunks-plugin/ and move modules from `node_modules` in the separate chunk and apply the plugin using the `test` option with different options
- You can use babel plugin for this (preferred)


Just note - removing `console` is not a safe in some cases.

**Comment by ZachSaucier** [comment]
@alexander-akait When you say "You can use babel plugin for this (preferred)" what exactly do you mean?

In my case, I'd like some way of explicitly overwriting rspack's removal of console messages. Perhaps allowing `console.info` while removing `console.log` for example.
