### ISSUE TITLE
Out of Memory with cache enabled

### ISSUE THREAD

**Issue by chaffeqa** [webpack-contrib/terser-webpack-plugin#319]
- Operating System: OSX 10.15.6
- Node Version: 14.11.0
- NPM Version: 6.14.8
- webpack Version: 5.0.0-beta.32
- terser-webpack-plugin Version: 4.1.0

### Expected Behavior

Not get out of memory crash when cache is enabled

### Actual Behavior

Consistent OOM crash

### How Do We Reproduce?

We have a multicompile (3 webpack bundles) with a nodeJS version that has `LimitChunkCountPlugin({ maxChunks: 1 })` so single file output.  Even though webpack says it sets the `cache` to `false` on production mode (and terser-webpack-plugin should respect that setting), we found that by setting `cache: false` for terser-webpack-plugin the OOM didnt occur (and the build significantly goes faster).

Happy to try to help further, but at least mentioning this in case you see other reports of the caching causing OOM

**Comment by evilebottnawi** [comment]
Fixed in `4.2.1` https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/package.json#L3, please update, feel free to feedback if it is not help
