### ISSUE TITLE
keep getting errors on build with vue-cli

### ISSUE THREAD

**Issue by kueiapp** [webpack-contrib/terser-webpack-plugin#327]
I have a vue2 project with vue-cli 4.5.
As I tried to use this plugin, but two issues occured

issue 1
When requiring terser plugin on line "const TerserPlugin = require('terser-webpack-plugin')" on building, it shows up lots of errors from node_modules/terser-webpack-plugin/ in js files which just use catch { }. I tried modify all of them to catch (e) { }, then the errors were gone.

issue 2
After passing the issue 1, it shows error on line "config.optimization" with message "this.optimization.entries is not a function..."

```
// vue.config.js
const TerserPlugin = require('terser-webpack-plugin')

module.exports = {
  configureWebpack: config => {
    config.optimization = {
      minimize: true,
      minimizer: [
        new TerserPlugin(),
      ],
    }
  }
}
```

**Comment by evilebottnawi** [comment]
Please open an issue in `vue-cli`
