### ISSUE TITLE
[webpack5] Type 'TerserPlugin' is not assignable to optimization.minimizer option

### ISSUE THREAD

**Issue by tjx666** [webpack-contrib/terser-webpack-plugin#333]
- Operating System: win10 pro
- Node Version: v12.19.0
- NPM Version: 6.14.8
- webpack Version: ^5.1.0
- terser-webpack-plugin Version: ^4.2.3

### Expected Behavior

No TypeScript Error reported.

### Actual Behavior

![screenshot_2020-10-14_00-26-55](https://user-images.githubusercontent.com/41773861/95889160-a648df00-0db4-11eb-8963-ca27daa007e6.png)

### Code

```js
import { argv } from 'yargs';
import { BannerPlugin, Configuration } from 'webpack';
import { merge } from 'webpack-merge';
import TerserPlugin from 'terser-webpack-plugin';
import SpeedMeasurePlugin from 'speed-measure-webpack-plugin';
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer';

import commonWebpackConfig from './webpack.common';

const mergedConfiguration: Configuration = merge(commonWebpackConfig, {
    mode: 'production',
    plugins: [
        new BannerPlugin({
            banner:
                '/** @preserve powered by vscode-extension-boilerplate(https://github.com/tjx666/vscode-extension-boilerplate) */',
            raw: true,
        }),
    ],
    optimization: {
        minimize: true,
        minimizer: [
            new TerserPlugin({
                cache: true,
                parallel: true,
                extractComments: false,
            }),
        ],
    },
});

// eslint-disable-next-line import/no-mutable-exports
let prodWebpackConfiguration = mergedConfiguration;
if (argv.analyze) {
    mergedConfiguration.plugins!.push(new BundleAnalyzerPlugin());
    const smp = new SpeedMeasurePlugin();
    prodWebpackConfiguration = smp.wrap(mergedConfiguration);
}

export default prodWebpackConfiguration;
```

### How Do We Reproduce?

Project Address: [vscode-extension-boilerplate](https://github.com/tjx666/vscode-extension-boilerplate)

**Comment by evilebottnawi** [comment]
Not related to `terser-webpack-plugin`, we don't have types

**Comment by evilebottnawi** [comment]
You need to wait updating `@types`

**Comment by grantila** [comment]
Specifically this https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48806

**Comment by brunomarks7** [comment]
If you use Webpack 5, you don't need the terser-webpack-plugin. 
https://webpack.js.org/plugins/terser-webpack-plugin/

![image](https://user-images.githubusercontent.com/28784176/100816654-5803a400-3425-11eb-88ce-56aa9d7452b7.png)

**Comment by suooq** [comment]
> 如果您使用 Webpack 5，则不需要 terser-webpack-plugin。
> https://webpack.js.org/plugins/terser-webpack-plugin/
> 
> ![图像](https://user-images.githubusercontent.com/28784176/100816654-5803a400-3425-11eb-88ce-56aa9d7452b7.png)

I need to update the terser options
