### ISSUE TITLE
Add back `sourceMap`?

### ISSUE THREAD

**Issue by beaugunderson** [webpack-contrib/terser-webpack-plugin#336]
- Operating System: macOS
- Node Version: v14.11.0
- NPM Version: 6.14.8
- webpack Version: 5.1.3
- terser-webpack-plugin Version: 5.0.0

### Expected Behavior / Situation

`sourceMap` allows overriding whether sourcemaps are generated.

### Actual Behavior / Situation

`sourceMap` was recently removed and now only follows the value of `devtool`.

### Modification Proposal

We use `sourceMap: true` with `terser-webpack-plugin` in production so that `webpack-sentry-plugin` could upload source maps as part of our production build, meaning that when exceptions were sent to Sentry they would have the sourcemaps available when looking at tracebacks.

I'm not sure how to achieve the same setup now without enabling setting `devtool` in production, which we don't want to do because it impacts application performance.

### Solution

In looking at the supported `devtool` settings I see `hidden-source-map`--would that be equivalent? To answer my own question, after reading the documentation, it seems so!

![image](https://user-images.githubusercontent.com/61791/96323140-c5bc5380-0fd0-11eb-8616-dcc28eaf1b67.png)

**Comment by beaugunderson** [comment]
(I'll verify the solution and leave this open for a couple of days in case other people encounter the same thing and come looking for a fix)

**Comment by evilebottnawi** [comment]
Sorry, it is impossible, if you want to support, please describe your problem

**Comment by evilebottnawi** [comment]
And yes you need `devtool`, sentry plugins can have abilities to remove some sensitive data if you need to do it

**Comment by beaugunderson** [comment]
it's not impossible, I've outlined the solution above: setting `devtool` to `hidden-source-map` :)

**Comment by koox00** [comment]
> If the default webpack minimizer has been overridden (such as to customise the TerserPlugin options), make sure to configure its replacement with sourceMap: true to enable SourceMap support.

So the above from the [SourceMapDevToolPlugin](https://webpack.js.org/plugins/source-map-dev-tool-plugin/) docs is outdated?   
What can you do if you need to customize both `TerserWebpackPlugin` and `SourceMapDevToolPlugin`?

**Comment by evilebottnawi** [comment]
@koox00 

> If the default webpack minimizer has been overridden (such as to customise the TerserPlugin options), make sure to configure its replacement with sourceMap: true to enable SourceMap support.

we should remove it, can you open an issue in webpack docs repo

> What can you do if you need to customize both TerserWebpackPlugin and SourceMapDevToolPlugin?

Terser logic is simple - we generate source maps if they exists, so you don't need to touch this, I can't imagining situation when you do minimizing and keep source maps for not minimized code :confused:

**Comment by koox00** [comment]
I will open an issue no problem.

> Terser logic is simple - we generate source maps if they exists, so you don't need to touch this, I can't imagining situation when you do minimizing and keep source maps for not minimized code 😕

@evilebottnawi sorry, I wasn't clear, I just need to append a custom url for the sourcemaps and place them in a folder so I 
use `SourceMapDevToolPlugin` and not `devtool`.

**Comment by evilebottnawi** [comment]
@koox00 you can use any options for `SourceMapDevToolPlugin`, terser will work with them

**Comment by koox00** [comment]
>  Instead of using the devtool option you can also use SourceMapDevToolPlugin/EvalSourceMapDevToolPlugin directly as it has more options. Never use both the devtool option and plugin together. The devtool option adds the plugin internally so you would end up with the plugin applied twice.

@evilebottnawi what confuses me is: I want to customise source-map generation so I use `SourceMapDevToolPlugin` but for `TerserWebpackPlugin` to generate source-maps I have to use `devtool`, I can add `devtool: hidden-source-map` but it feels more like a hack.

PS: before v5 it was working as intended: `devtool: none`, and in `TerserWebpackPlugin`: `sourceMap: true`

**Comment by evilebottnawi** [comment]
@koox00 

> I can add devtool: hidden-source-map and use the SourceMapDevToolPlugin as well but it feels more like a hack.

It is not hack, in future we want to support many `SourceMapDevToolPlugin` plugins, right now it is not work

> PS: before v5 it was working as intended: custom SourceMapDevToolPlugin, devtool: none, and in TerserWebpackPlugin: sourceMap: true

You can use the same approach here, just remove `sourceMap: true` from terser plugin and all should work fine

**Comment by jdmoody** [comment]
> It is not hack, in future we want to support many SourceMapDevToolPlugin plugins, right now it is not work

To make sure I understand, the correct way to add a custom sourcemap url in Webpack 5 is to have `devtool: 'hidden-source-map'` combined with a `SourceMapDevToolPlugin` that overrides the public path? 

For example:
```
new webpack.SourceMapDevToolPlugin({
  filename: '[file].map[query]',
  publicPath: 'https://my-sourcemap-url.com/sourcemaps/',
})
```

**Comment by alexander-akait** [comment]
And yes and no, depend what you need

**Comment by jdmoody** [comment]
> And yes and no, depend what you need

How does it depend? It sounds like there may be factors that I'm not taking into account. My use case is that I'd like to host sourcemaps internally for minified production code.

Thank you for your time.

**Comment by alexander-akait** [comment]
>  My use case is that I'd like to host sourcemaps internally for minified production code.

In this case you should apply `devtool: 'hidden-source-maps'` and apply SourceMapPlugin again
