### ISSUE TITLE
Terser Plugin has been initialized using an options object that does not match the API schema.  - options has an unknown property 'cacheKeys'.

### ISSUE THREAD

**Issue by AdeonMaster** [webpack-contrib/terser-webpack-plugin#337]
- Operating System: Windows 10
- Node Version: 12.18.2
- NPM Version: 6.14.5
- webpack Version: 5.1.3
- terser-webpack-plugin Version: 5.0.0

### Expected Behavior

No errors should be thrown while building project with terser

### Actual Behavior

![image](https://user-images.githubusercontent.com/11544417/96335606-90703e00-1082-11eb-94f5-0cb6db98151f.png)

### Terser plugin config

```js
new TerserPlugin({
 parallel: true,
 extractComments: true
})
```

Considering that these lines should be also removed as `cache` & `cacheKeys` were deprecated. https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L26, https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L27, https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L36, https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L37

**Comment by evilebottnawi** [comment]
Please look at stacktrace, there is no problem on our side
