### ISSUE TITLE
Cast " Cannot read property 'javascript' of undefined " error when installing terser-webpack-plugin@v5.0.0 and setting minimize property to true 

### ISSUE THREAD

**Issue by tjcchen** [webpack-contrib/terser-webpack-plugin#342]
Hi there,

Today, I installed the latest version of _terser-webpack-plugin_, namely v5.0.0, and with { minimize: true } property set. I got the following error message in my console:

> XXXX-MBP-2:my-project xxx$ npm run build
> 
> my-project@1.0.0 build /Users/xxx/webpack-studio/my-project
> webpack --config webpack.prod.js
> 
> /Users/xxx/webpack-studio/my-project/node_modules/terser-webpack-plugin/dist/index.js:366
>       const hooks = compiler.webpack.javascript.JavascriptModulesPlugin.getCompilationHooks(compilation);
>                                      ^
> TypeError: Cannot read property 'javascript' of undefined

However, after some struggling, when I downgrade my _terser-webpack-plugin_ to version v4.2.2, this problem disappeared. I assume this might be a problem introduced in a new version of _terser-webpack-plugin_. Can anybody help to take a look? or can any other users reproduce this problem.

Thanks in advance!

**Comment by evilebottnawi** [comment]
You need webpack@5 to use latest v5 of `terser-webpack-plugin`

**Comment by evilebottnawi** [comment]
Please always look what you package manager have written

**Comment by tjcchen** [comment]
> You need webpack@5 to use latest v5 of `terser-webpack-plugin`

Many thanks, I'll try `terser-webpack-plugin` v5 when I upgrade my webpack to version 5

**Comment by monic-shixi** [comment]
I had same issue cased by https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/160

**Comment by tjcchen** [comment]
Thanks for your updating, @monic-shixi
