### ISSUE TITLE
Cannot read property 'javascript' of undefined

### ISSUE THREAD

**Issue by a1burning** [webpack-contrib/terser-webpack-plugin#352]
- Operating System:
- Node Version:v12.19.0
- NPM Version:6.14.8
- webpack Version:^4.41.2
- terser-webpack-plugin Version:^5.0.3

### Expected Behavior

run : webpack --mode production 
bundle.js should be compress

### Actual Behavior

![微信图片_20201029180834](https://user-images.githubusercontent.com/27470579/97555453-1b522080-1a13-11eb-8a1e-f06a16c86653.png)

### Code

```js
const { CleanWebpackPlugin } = require('clean-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const OptimizeCssAssetsWebpackPlugin = require('optimize-css-assets-webpack-plugin')
const TerserWebpackPlugin = require("terser-webpack-plugin")

module.exports = {
  mode: 'none',
  entry: {
    main: './src/index.js'
  },
  output: {
    filename: '[name].bundle.js'
  },
  optimization: {
    minimizer: [
      new TerserWebpackPlugin(),
      new OptimizeCssAssetsWebpackPlugin()
    ]
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader'
        ]
      }
    ]
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      title: 'Dynamic import',
      template: './src/index.html',
      filename: 'index.html'
    }),
    new MiniCssExtractPlugin(),
  ]
}

```
### Temporary solution

"terser-webpack-plugin": "^2.2.1"

IT WORKS...

**Comment by evilebottnawi** [comment]
Because `terser-webpack-plugin` supports only webpack@5, please read what your package manager write you

**Comment by a1burning** [comment]
> Because `terser-webpack-plugin` supports only webpack@5, please read what your package manager write you

I have upgraded the version of webpack and it works.
