### ISSUE TITLE
documentation mentions a "cache" option, but TypeScript don't have such option.

### ISSUE THREAD

**Issue by trusktr** [webpack-contrib/terser-webpack-plugin#354]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [x] Not Sure?

### Please Explain in Detail...

See here the `cache: true` option:

https://webpack.js.org/configuration/optimization/

But when I import `TerserPlugin` the TS type checker in VS Code tells me there is no such `cache` option.

### Your Proposal for Changes

Something needs an update.

**Comment by evilebottnawi** [comment]
Because cache was removed
