### ISSUE TITLE
Unable to use the webpack terser-webpack-plugin module

### ISSUE THREAD

**Issue by xastor** [webpack-contrib/terser-webpack-plugin#357]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

> If you are using webpack v5 or above you do not need to install this plugin. Webpack v5 comes with the latest terser-webpack-plugin out of the box.

This section is misleading.  Although webpack5 does indeed come with the plugin, it cannot be used by a developer.  If you want to do that, you do need to install terser-webpack-module.  Webpack only uses it to set a default minimizer.

As a developer, I was expecting the statement above to mean that I could use `new webpack.TerserPlugin(options)`.

### Your Proposal for Changes

Most likely webpack won't be exposing the terser plugin module they use internally, so I propose to remove this confusing paragraph or at least clarify that webpack provides a default minimizer using terser-webpack-plugin.

**Comment by evilebottnawi** [comment]
> This section is misleading. Although webpack5 does indeed come with the plugin, it cannot be used by a developer. 

No, minimizers works only in `mode: 'production'`, it was described in docs

Sorry, I want to close it because we change it many times and every time somebody found it misleading, I don't know who it write better, so if you want to do feel free to send a PR, docs are very clarify for minimizers
