### ISSUE TITLE
is jest worker intentionally a dependency and not a dev-dependency?

### ISSUE THREAD

**Issue by sijakret** [webpack-contrib/terser-webpack-plugin#363]
Hi,
Is jest worker intentionally a dependency and not a dev-dependency?
https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/package.json
```js
"dependencies": {
    "jest-worker": "^26.6.2"
}
```
all other jest deps are dev dependencies.

somehow i doubt jest-worker should be a dependency but rather a devDependency or is this intentional?

Cheers

**Comment by alexander-akait** [comment]
We use jest-worker for parallels, it is dependency

**Comment by sijakret** [comment]
Thanks for the explanation. My bad!
