### ISSUE TITLE
Controlling mangle is not documented

### ISSUE THREAD

**Issue by gregbown** [webpack-contrib/terser-webpack-plugin#367]
Documentation Is:
- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

There is no clear documentation on how to manage the mangle option, especially when there is a need to preserve specific variable names with the reserve option.  In my case the application uses an IOC container and the name mapping needs to remain in tact for the dependency injection function to work.

It took me several hours of weeding through the issue lists here, and on the terser repo and even then, I feel that I got lucky stumbling on the exact combination of how to accomplish this.  This being said, I am grateful for Webpack and this plugin as well and appreciate the efforts of everyone involved. Thank you!

I do not think I am qualified to say without a doubt this is how it is done, but from my experimentation I found the crucial combination required to preserve variable names to was:
```
        terserOptions: {
          compress: {},
          mangle: {
            properties: false,
            reserved: ["variableNameToPreserve"]
          }
```
**Complete terser plugin configuration below** The working build/code can be found [here](https://github.com/gregbown/soma-redux-i18next-webpack)
```
    minimizer: [
      new TerserPlugin({
        // licensing
        extractComments: {
          condition: /^\**!|@preserve|@license|@cc_on/i,
          filename: (fileData) => {
            // The "fileData" argument contains object with "filename", "basename", "query" and "hash"
            return `LICENSE.txt${fileData.query}`;
          },
          banner: (licenseFile) => {
            return `License information can be found in ${licenseFile}`;
          },
        },
        // compression and minification
        terserOptions: {
          ecma: undefined,
          parse: {},
          compress: {},
          mangle: {
            properties: false,
            reserved: [
              "i18next",
              "emitter",
              "rws",
              "loader",
              "renderer",
              "actions",
              "todos",
              "filter",
              "locale",
              "reducers",
              "configuration",
              "store",
              "head",
              "input",
              "list",
              "foot"
            ]
          }
        }
      })
    ],
```

**Comment by alexander-akait** [comment]
I don't think we need document this, we have link on `terser` option, where you can ask to clarify options, we just wrapper around that tool, we can't reexplain each option in our docs, sorry

**Comment by alexander-akait** [comment]
Anyway if you know how to better clarify some parts of docs feel free to send a PR
