### ISSUE TITLE
Name mangling of variable is causing problem

### ISSUE THREAD

**Issue by paramsinghvc** [webpack-contrib/terser-webpack-plugin#375]
- Operating System: OS 11.1
- Node Version: 14.15.1
- NPM Version: 6.14.8
- webpack Version: 4.42.0
- terser-webpack-plugin Version: 2.3.7

I'm using [nrwl](https://nx.dev/) react setup

### Expected Behavior
The name mangling of the variable shouldn't cause same alphabet to used on both lhs and rhs of the `=` assignment operator. 

### Actual Behavior
```
 const { data, dataKey } = this.props;
    const lastVal = data[data.length - 1][dataKey];
    const firstVal = data[data.length - 12][dataKey];
    if (firstVal) {
      const yoyPercent = Math.round(100 * ((lastVal - firstVal) / firstVal));
```

gets converted to 

```
  const {data: n, dataKey: t} = this.props
    , e = n[n.length - 12][t];
  if (e) {
      const n = Math.round((n[n.length - 1][t] - e) / e * 100)
```

It gives an error `Cannot access variable 'n' before initialization`

![Screenshot 2021-01-13 at 09 32 51](https://user-images.githubusercontent.com/4329912/104433734-58de3880-5582-11eb-90cf-f2ecdea4045b.png)

### Configuration
I found the below configuration after digging into the generated Nx webpack config.

```
{
    "test": {},
    "extractComments": true,
    "sourceMap": false,
    "cache": true,
    "parallel": true,
    "terserOptions": {
        "warnings": true,
        "safari10": true,
        "output": {
            "ecma": 5,
            "comments": false,
            "webkit": true
        },
        "compress": {
            "ecma": 5,
            "pure_getters": {
                "scripts": true,
                "styles": true
            },
            "passes": 3,
            "global_defs": {
                "ngDevMode": false,
                "ngI18nClosureMode": false
            }
        },
        "mangle": true
    }
}
```

**Comment by alexander-akait** [comment]
Please open issue in `terser` repo, we can't control mangling, we just run your code through `terser` https://github.com/terser/terser/issues, sorry
