### ISSUE TITLE
The Readme about version confused me

### ISSUE THREAD

**Issue by wxwqslsdsh** [webpack-contrib/terser-webpack-plugin#377]
Documentation Is:

- [1] Missing about webpack@4
- [2] Needed some document for webpack@4
- [3] Confusing you said we need not install the plugin in webpack@5, so only in webpack@<5 we need to install this plugin manually, but in my webpack@4 project, I follow the document to run `npm install terser-webpack-plugin --save-dev` and then run the build command, but I got the error: `TypeError: Cannot read property 'javascript' of undefined`

**Comment by alexander-akait** [comment]
Latest version of `terser-webpack-plugin` doesn't support webpack@4, webpack@4 is deprecated (only fixes), please consider to migrate

**Comment by justin-hackin** [comment]
@alexander-akait  I'm still confused about this because this package is not needed by webpack@5 and yet it has webpack@5 as a peer dependency.  Upgrading is not always an option so it would be kind if you could list the version of this package that works with webpack@4 in the docs.
