### ISSUE TITLE
How to config format option in terserOptions?

### ISSUE THREAD

**Issue by 643104191** [webpack-contrib/terser-webpack-plugin#380]
- Operating System: win10 wsl1 ubuntu18.04
- Node Version: v14.15.4
- NPM Version: 6.14.10
- webpack Version: 4.46.0
- terser-webpack-plugin Version: 4.2.3
- terser Version: 5.5.1

### Expected Behavior
keep format options in `src/minify.js`
[src/minify.js#L232](https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/minify.js#L232)

### Actual Behavior
![image](https://user-images.githubusercontent.com/27074730/105165027-ca088780-5b50-11eb-8dab-e2d7a2e58ca1.png)

### Code
```js
// webpack.config.babel.js
export default {
  // other config
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
            test: [/\.js$/i],
            terserOptions: {
              compress: {
                drop_console: true,
                drop_debugger: true
              },
              format: {
                keep_numbers: true
              }
            }
      })
    ],
  }
  // other config
}
```

**Comment by alexander-akait** [comment]
For `terser-webpack-plugin@4` please use `output` instead `format` (it is the same https://github.com/terser/terser/blob/master/tools/terser.d.ts#L149)

**Comment by 643104191** [comment]
> For `terser-webpack-plugin@4` please use `output` instead `format` (it is the same https://github.com/terser/terser/blob/master/tools/terser.d.ts#L149)

thank you very much
