### ISSUE TITLE
reexport TerserPlugin class from webpack package

### ISSUE THREAD

**Issue by rifler** [webpack-contrib/terser-webpack-plugin#384]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- terser-webpack-plugin Version:

### Feature Proposal
TerserPlugin comes with webpack, but if you need to modify 1 option, you have to explicitly install plugin.
Npm deduplication algorithm may not work, because some other package can install older version of plugin

```
node_modules/
    terser-webpack-plugin/ # some old version from 3rd party package
    webpack/
        node_modules/
            terser-webpack-plugin/ # actual version
```

so it can easily get out of sync

### Feature Use Case
```js
import webpack from 'webpack';

minimizer:[
    new webpack.TerserPlugin(...)
]
```

**Comment by alexander-akait** [comment]
You don't need `terser-webpack-plugin` if you use v5, you can use `minimizer: ['...', new MyMinimizerPlugin()]` syntax to extend the `minimizer` option, in previous versions we exported the plugin, but this creates a problem with updates, so we removed this feature in favor `...`

**Comment by rifler** [comment]
> You don't need terser-webpack-plugin if you use v5

> Yes you need to install terser-webpack-plugin directly if you need change options

I mean exactly this - I want to use terser, but change only one option. For example, set `extractComments: false`.
So I have to install it manually. After that version can get out of sync - I will update webpack (and webpack will update terser version), but forget to update manually installed version.

> it is internal and was discussed a long time ago

Ok, let's close the issue
