### ISSUE TITLE
A case of ignoring removing console.

### ISSUE THREAD

**Issue by quietnumeric** [webpack-contrib/terser-webpack-plugin#385]
- Operating System: WSL1 on Windows10
- Node Version: v12.19.0
- NPM Version: 6.14.8
- webpack Version: 4.44.0 on Nuxt.js 2.13.3
- terser-webpack-plugin Version: 1.4.4

### Expected Behavior

Removing `console.log` in minified source.

### Actual Behavior

Remains that.

### Code

```
// I already found real cause. That is spread syntax.
const array = ['zero', 'one', 'two'];
console.log(...array);

// Of course, when I used string join, removing was successful.
console.log(array.join(' '));
```

### How Do We Reproduce?

Always.

**Comment by alexander-akait** [comment]
Please open an issue in `terser` repo (https://github.com/terser/terser), we just wrapper, removing `console.log` by default is not safe
