### ISSUE TITLE
Update serialize-javascript

### ISSUE THREAD

**Issue by anzuj** [webpack-contrib/terser-webpack-plugin#390]
- Operating System: Windows 10
- Node Version: v12.19.0
- NPM Version: 6.14.8
- webpack Version: "4.46.0"
- terser-webpack-plugin Version: "^1.4.3"

### Expected Behavior / Situation
Updated serialize-javascript version to pass an audit check.

### Actual Behavior / Situation
"serialize-javascript": "^2.1.2" comes up as a High severity issue on npm audit check.

### Modification Proposal
Update serialize-javascript to 4.0.0 as other webpack dependancies

**Comment by alexander-akait** [comment]
Already updated and published https://github.com/webpack-contrib/terser-webpack-plugin/blob/version-1/package.json#L44

**Comment by alexander-akait** [comment]
try to run `npm update`, alternative (not safe in some cases) - `rm -r node_mdoules package-lock.json && npm i`
