### ISSUE TITLE
Upgrade cacache for version 2

### ISSUE THREAD

**Issue by gonzaloriestra** [webpack-contrib/terser-webpack-plugin#391]
- Operating System: Ubuntu 20.04
- Node Version: 10.19.0
- NPM Version: 6.14.4
- webpack Version: 4.46.0
- terser-webpack-plugin Version: 2.3.8

### Expected Behavior

`cacache` dependency should pass an audit check.

### Actual Behavior

Current `cacache` version (`^13.0.1`) requires `ssri: ^7.0.0`, which has a moderate vulnerability: https://www.npmjs.com/advisories/565.

### Modification Proposal

Upgrade `cacache` to 15.0.6, which requires a safer version of ssri (`^8.0.1`).

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack-contrib/terser-webpack-plugin/issues/388, it is impossible to update due breaking changes, you can use `4` version https://github.com/webpack-contrib/terser-webpack-plugin/tree/v4.2.3

**Comment by gonzaloriestra** [comment]
Thanks! And sorry for the noise.
