### ISSUE TITLE
TerserPlugin exclude not preventing mangling

### ISSUE THREAD

**Issue by ajbrun** [webpack-contrib/terser-webpack-plugin#392]
Not sure if this should be here or in webpack main...

I am importing a JSON config file which stored application settings. This is intended to be transformed during our build/deployment procedure and happens after the production build. Therefore, replacements happen after minifcation/mangling so I don't want this JSON to be mangled.

I had expected that using the exclude option would have solved this, but it appears not to. Instead, only using mangleExports false appears to work but this is a global option and not file specific.

Here is the releavant portion of my webpack config:
```
optimization: {
    minimize: true,
    // mangleExports: false,
    minimizer: [
      new TerserPlugin({
        exclude: [/.*\.json/],
        terserOptions: {
          format: {
            comments: false,
          },
        },
        extractComments: false,
      }),
    ],
  },
```
And an example config file:
```
{
  "configSection1": {
    "setting1": "KEY",
    "setting2": true
  },
  "configSection2":{
      "siteKey": "SITE_KEY"
  }
}
```

Which is being used in our application:
`import config from "../config.json";`

However the output is not mangled unless of course it cannot/shouldn't be (used in an external dependency for example).

- Operating System: Windows
- Node Version: v10.16.3
- NPM Version: 7.6.3
- webpack Version: 5.25.0
- terser-webpack-plugin Version: As part of webpack

### Expected Behavior

`var Ka=JSON.parse('{"configSection1": {"setting1": "KEY","setting2": true},"configSection2":{"siteKey": "SITE_KEY"}}');`

### Actual Behavior

An example...
`var Ka=JSON.parse('{"A": {"B": "KEY","C": true},"D":{"E": "SITE_KEY"}}');`

**Comment by alexander-akait** [comment]
I don't think this problem in webpack or terser plugin, webpack and terser doesn't rewrite strings

**Comment by alexander-akait** [comment]
Don't ignore reproducible example, otherwise I can't help

**Comment by ajbrun** [comment]
Apologies, I've make a stripped down github repo here:
https://github.com/ajbrun/terser-webpack-plugin-392/tree/main

My understanding from my comment in the config is that I should be able to exclude manging on a file by file basis as manging is enabled by default:
https://github.com/ajbrun/terser-webpack-plugin-392/blob/main/webpack.config.js

**Comment by alexander-akait** [comment]
Oh, I see, but why do you need keep names? In browser and es modules Node.js `json` import is not supported/experimental (https://nodejs.org/api/esm.html#esm_no_json_module_loading) and maybe will not be supported in future in favor `asserts` import, so we can use two solution here:
- Load file as in browser
```js
fetch(new URL('./config.json', import.meta.url))
  .then((response) => response.json())
  .then((result) => console.log(result))
```
- Say it is not ES module and inline content
```js
import config from "./config.json";

class Class1 {
    initialise(){
        console.log(JSON.parse(config).configSection2.siteKey);
    }
}

export default Class1;
```

```js
module.exports = {
  // Configs
  module: {
    rules: [
      {
        test: /config\.json/,
        type: 'asset/source'
      }
    ]
  },
  // Configs
```

- change it on `require` (because require supports JSON modules)

```js
const config = require("./config.json");

class Class1 {
    initialise(){
        console.log(config);
    }
}

export default Class1;
```

- Use `DefinePlugin` and inline this values (less size and simple usage)

**Comment by alexander-akait** [comment]
Answered, feel free to feedback
