### ISSUE TITLE
Security Vulnerability pick up by Fortify Scan

### ISSUE THREAD

**Issue by nekyouto** [webpack-contrib/terser-webpack-plugin#393]
terser-webpack-plugin version: 4.2.3

### Expected Behavior
No Security Vulnerables

### Actual Behavior
We were performing a scan on the terser-webpack-plugin Javascript library and the Fortify application has picked up the following items that are discovered as vulnerabilities. 
(Reason being our project has imported this library as a dependency and part of our deliverable would requires the scanning of the full source code and identify/remove the vulnerable.)

(**Low**) Key Management: Null Encryption Key (Plugin: terser-webpack-plugin)
No of items picked by the Fortify Scan: **1**
Kindly refer to the following image, scanImage5
![scanImage5](https://user-images.githubusercontent.com/6581645/117434661-8a2eaa00-af5f-11eb-8bf1-d4aa07aa0902.png)

(**Low**) Poor Logging Practice: Use of a System Output Stream (Plugin: terser-webpack-plugin)
No of items picked by the Fortify Scan: **Less than 10**
Kindly refer to the following image, scanImage6
![scanImage6](https://user-images.githubusercontent.com/6581645/117436053-1f7e6e00-af61-11eb-9d9b-0ea87339d5a7.png)

(Reason being our project has imported this library as a dependency and part of our deliverable would requires the scanning of the full source code and identify/remove the vulnerable.)

**Comment by alexander-akait** [comment]
We don't have this code, problem in your bundle

**Comment by alexander-akait** [comment]
Answer here https://github.com/webpack/webpack/issues/13321#issuecomment-834276928
