### ISSUE TITLE
Mark uglifyjs-webpack-plugin as deprecated on npm

### ISSUE THREAD

**Issue by abraham** [webpack-contrib/terser-webpack-plugin#398]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

`uglifyjs-webpack-plugin` on GitHub is archived and marks this package as the replacement. However when running npm install on a project using `uglifyjs-webpack-plugin` there is not warning that the package is deprecated.

### Your Proposal for Changes

Use [npm-deprecate](https://docs.npmjs.com/cli/v7/commands/npm-deprecate) to mark all version of [uglifyjs-webpack-plugin](https://www.npmjs.com/package/uglifyjs-webpack-plugin) as deprecated.

**Comment by alexander-akait** [comment]
We decided not to do this because many boilerplates still use `uglifyjs-webpack-plugin`, so it will create a lot of spam for them
