### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by sergeu90** [webpack-contrib/terser-webpack-plugin#403]
Hello everyone after update terser plugin to 5.1.2 i have error 

I downgrade to 5.1.1 and works.

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa222f0 node::Abort() [webpack]
 2: 0x96411f node::FatalError(char const*, char const*) [webpack]
 3: 0xb97f1e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [webpack]
 4: 0xb98297 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [webpack]
 5: 0xd52fd5  [webpack]
 6: 0xd53b5f  [webpack]
 7: 0xd61beb v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [webpack]
 8: 0xd657ac v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [webpack]
 9: 0xd33e5b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [webpack]
10: 0x107c5af v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [webpack]
11: 0x1423279  [webpack]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.4.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please respect time of other developers, thanks

**Comment by sergeu90** [comment]
@alexander-akait Problem was terser plugin eats up a lot of memory after release 5.1.2. /
My build server have 2 Ram and in the 5.1.1 version all work fine. But after  upgrade  to 5.1.2 I have get error. 

I use terser plugin with webpack. 

My configuration Terser plugin. 


```
minimizer: [
      new TerserPlugin({
      terserOptions: {
        warnings: false,
        compress: {
          comparisons: false,
        },
        parse: {},
        mangle: true,
        output: {
          comments: false,
          ascii_only: true,
        },
      },
    }),],
```
I think in the https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.1.2 was commit which which have leak memory

**Comment by alexander-akait** [comment]
This commit fixes memory usage, with 5.1.1 all fine?

**Comment by sergeu90** [comment]
@alexander-akait Yes in the 5.1.1 all fine. Could you check pls version 5.1.2 ?

**Comment by alexander-akait** [comment]
@sergeu90 Can you provide reproducible example? I want to check memory usage, because it should fix memory usage

**Comment by sergeu90** [comment]
@alexander-akait on my real project I don't share source code.I think you can take my configuration and compare 5.1.1 and 5.1.2 between

**Comment by alexander-akait** [comment]
Sorry I can find the problem using comparing, because it is fix the parallel problem and memory usage

**Comment by sergeu90** [comment]
@alexander-akait maybe change status issue from close to open

**Comment by alexander-akait** [comment]
@sergeu90 please provide example of the problem, if you need i can sign NDA

**Comment by sergeu90** [comment]
@alexander-akait Above i send configuration terser plugin. I think you can compare two version.

**Comment by alexander-akait** [comment]
@sergeu90 I compare and don't see any problem with memory, if we have big problem(s) with memory, we will have a lot of issue here, but you can see it is not, what is the problem to help? You can share repo only for me and then close access after we fix the problem

**Comment by sergeu90** [comment]
@alexander-akait  Sorry but i can't share project and give access

**Comment by alexander-akait** [comment]
@sergeu90 Unfortunately I can't help here, maybe related https://github.com/webpack/webpack/issues/13550

**Comment by alexander-akait** [comment]
I recommend to pin terser-webpack-plugin to v5.1.1 right now, look like jest-worker has memory leak

**Comment by sergeu90** [comment]
@alexander-akait  Thanks. Now I downgraded to 5.1.1  and works fine.

**Comment by Tallyb** [comment]
I can confirm we experience the same issue both on angular storybook builds and angular builds. they both point to the @5.1.2. 
Is there a way to bypass the fix in 5.1.2 by changing the plugin configuration?

**Comment by alexander-akait** [comment]
@Tallyb Please provide reproducible test repo

**Comment by Tallyb** [comment]
@alexander-akait 
https://github.com/tallyb/coreui-free-angular-admin-template
This is a smaller project than the one I use (well, significantly smaller), so I put the node memory to 1024, then you see the failure. You only need to run npm run build, as it takes care of the mem allocation.

**Comment by alexander-akait** [comment]
@Tallyb Please open an issue in `ng` repo, look like something is leaking, even more if I set `config.optimization.minimizer = []` (i.e. disable terser plugin) I still get memory problem.

**Comment by Tallyb** [comment]
https://github.com/angular/angular/issues/42618
