### ISSUE TITLE
Missing "types" property in package.json file

### ISSUE THREAD

**Issue by amid2887** [webpack-contrib/terser-webpack-plugin#405]
- Operating System: macOS Big Sur. Version: 11.4 (20F71)
- Node Version: v15.14.0
- NPM Version: 7.7.6
- webpack Version: 5.39.0
- terser-webpack-plugin Version: 5.1.3

### Expected Behavior

As I can see declaration files are included in the plugin's npm package.

So, I expect this plugin to work with webpack configuration written in TypeScript.

### Actual Behavior

If you try to import the plugin in the webpack.config.ts file - you will get an error.

```js
// webpack.config.ts
import TerserPlugin from 'terser-webpack-plugin'; // TS7016: Could not find a declaration file for module 'terser-webpack-plugin'.
```

### How Do We Reproduce?

You can use this one-liner for example:

```bash
mkdir ~/terser-webpack-plugin-issue && cd $_ && npm install typescript ts-node terser-webpack-plugin && npx tsc --init && echo "import TerserPlugin from 'terser-webpack-plugin';" > webpack.config.ts && npx ts-node webpack.config.ts
```

And you will get the error:
```bash
./node_modules/ts-node/src/index.ts:587
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
webpack.config.ts:1:26 - error TS7016: Could not find a declaration file for module 'terser-webpack-plugin'. './node_modules/terser-webpack-plugin/dist/cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/terser-webpack-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module 'terser-webpack-plugin';`

1 import TerserPlugin from 'terser-webpack-plugin';
                           ~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (./node_modules/ts-node/src/index.ts:587:12)
    at reportTSError (./node_modules/ts-node/src/index.ts:591:19)
    at getOutput (./node_modules/ts-node/src/index.ts:921:36)
    at Object.compile (./node_modules/ts-node/src/index.ts:1189:32)
    at Module.m._compile (./node_modules/ts-node/src/index.ts:1295:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.require.extensions.<computed> [as .ts] (./node_modules/ts-node/src/index.ts:1298:12)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
```

### Possible Solution
Possible solutions are mentioned [here](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package).

For example:
Set the `types` property to point to your bundled declaration file.
```diff
// package.json
{
...
  "main": "dist/cjs.js",
+  "types": "types/cjs.d.ts",
...
}
```

**Comment by alexander-akait** [comment]
Types is not implemented yet here, it is internal

**Comment by amid2887** [comment]
Could you explain what you mean - "it is internal"?

The types are included in the npm package, so it's not obvious that they should not be used.

**Comment by alexander-akait** [comment]
@amid2887 it is internal only as lint, it is prepare step for types in all repo. Firstly we add all types to all plugins/loader and check (include problems with types in webpack), then the next step -  we will fix the problem and publish types

**Comment by amid2887** [comment]
Okay. Thank you!
