### ISSUE TITLE
Use TerserPlugin with webpack 5

### ISSUE THREAD

**Issue by trumko** [webpack-contrib/terser-webpack-plugin#406]
Terser documentation says there is no need to install `terser-webpack-plugin` if webpack 5 is used:
> If you are using webpack v5 or above you do not need to install this plugin. Webpack v5 comes with the latest terser-webpack-plugin out of the box.

However I need to add custom TerserPlugin options into my webpack prod configuration. 

Example:
```
    minimizer: [
      new TerserPlugin({
        parallel: true,
        terserOptions: {
          compress: {
            // ...
          },
          output: {
            // ...
          },
        },
      }),
    ],
```

How can I do this without installing  TerserPlugin and importing it into my webpack config (`const TerserPlugin = require('terser-webpack-plugin');`)?

**Comment by alexander-akait** [comment]
> How can I do this without installing TerserPlugin and importing it into my webpack config (const TerserPlugin = require('terser-webpack-plugin');)?

You need install terser-webpack-plugin and using example above, this is the only correct solution, you can have multiple minimizers, so you can setup only options
