### ISSUE TITLE
 Can't resolve 'worker_threads'

### ISSUE THREAD

**Issue by xudawww** [webpack-contrib/terser-webpack-plugin#409]
error - ./node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/messageParent.js:27:36
Module not found: Can't resolve 'worker_threads'
Please fixing this annoying stuff for me, it takes me 10 hours, without any lucks, not the problem of node --experimental-worker server.js, my node version is newest.

**Comment by alexander-akait** [comment]
You need minimum Node.js v10.13.0 https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/package.json#L16, please update Node.js
