### ISSUE TITLE
Function names are not properly minified and causes a invalid syntax.

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [webpack-contrib/terser-webpack-plugin#410]
- Operating System: MacOs Big Sur (Happens in CI too)
- Node Version: v14.6.0
- NPM Version: 6.14.11
- webpack Version: ^5.10.0
- terser-webpack-plugin Version: ^5.1.4

### Expected Behavior

Function names are preserved or minified according to the options passed.

### Actual Behavior

Function names are mixed with some `for loop` and causes `Invalid left-hand side in for-in loop: Must have a single binding.` error.

I am trying to bundle a `npm` module which you can be found from the [unpkg](https://unpkg.com/browse/@teleporthq/teleport-plugin-common@0.17.0/dist/esm/index.js
) and line number `593`.  When minifier is used with the webpack plugin. The function name is mixed with a `for loop` with invalid syntax. This doesn't happen when i disable the optimiser in `webpack`.

### Code
https://unpkg.com/browse/@teleporthq/teleport-plugin-common@0.17.0/dist/esm/index.js

### How Do We Reproduce?

For reproducing the bug, i have created a repository which creates two builds on with `terser` enabled and one with `terser` disabled. And when we try to load the files. The one with terser enabled causes the bug.

https://user-images.githubusercontent.com/11075561/124172457-8040a780-dac7-11eb-933c-7c094412478f.mov

### Terser disabled
![Screenshot 2021-07-01 at 11 35 58 PM](https://user-images.githubusercontent.com/11075561/124172762-d7df1300-dac7-11eb-9328-c21179bd90d2.png)

### Terser Enabled
![Screenshot 2021-07-01 at 11 40 28 PM](https://user-images.githubusercontent.com/11075561/124172851-f218f100-dac7-11eb-9572-c405733fd167.png)

### Repository to reproduce the bug 
https://github.com/JayaKrishnaNamburu/terser-minifier-bug-reproduction

I am not sure, if it's in the scope of the `webpack-terser-plugin` or it is directly handled inside `terser` but thanks in advance 😄

**Comment by alexander-akait** [comment]
Yep, bug in terser, please open an issue in terser repo

**Comment by JayaKrishnaNamburu** [comment]
Thanks for confirming, will do that 👍

**Comment by JayaKrishnaNamburu** [comment]
@alexander-akait i used terser separately on the chunk using `cli`. It seems to work good. Any chance that webpack does something after the terser output that's causing this. I don't know much about internals of webpack

**Comment by JayaKrishnaNamburu** [comment]
@alexander-akait i don't have this issue with `webpack-4` but happens in `webpack-5`. And the package which causes it uses `es6`.  I am trying to understand, does this happen because, the chunks of webpack-5 have es6 code too inside it and so terser is failing ?. Sorry, i didn't listen anything from terser team, so trying to understand better and find some solution.

**Comment by alexander-akait** [comment]
Webpack v4 uses old version of terser, webpack v5 uses the latest version, I think it is regression on terser side, by docs terser supports all es features, webpack generate valid code

**Comment by JayaKrishnaNamburu** [comment]
Thanks once again 🙏

**Comment by alexander-akait** [comment]
@JayaKrishnaNamburu Can we close in favor https://github.com/terser/terser/issues/1019?

**Comment by JayaKrishnaNamburu** [comment]
Yes yes, i was waiting. If i should make a update here once they make a release in terser 😄 👍

**Comment by alexander-akait** [comment]
Feel free to feedback
