### ISSUE TITLE
[webpack-cli] Error: Cannot find module 'terser-webpack-plugin'

### ISSUE THREAD

**Issue by Juraj-Masiar** [webpack-contrib/terser-webpack-plugin#415]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The docs says: _"If you are using webpack v5 or above you do not need to install this plugin."_
So as part of my migration to Webpack 5 I've removed it and now I'm getting error:
```
[webpack-cli] Error: Cannot find module 'terser-webpack-plugin'
```
So I'm confused, how do I use and configure the one inside the Webpack? All examples are using `require('terser-webpack-plugin');` which will fail without installing it first. Right?

**Comment by nikhilnayyar002** [comment]
yeah thats a nice question. Having same issue. I have this configeration earlier:

```js
const TerserPlugin = require("terser-webpack-plugin")
...
    optimization: {
        minimize: true,
        minimizer: [
            new TerserPlugin({
                extractComments: false,
            }),
            new CssMinimizerPlugin()
        ],
```

How will this code change?

**Comment by alexander-akait** [comment]
Install terser-webpack-plugin, it is how package managers works

**Comment by Juraj-Masiar** [comment]
LOL :D
The very first sentence in the "Getting started" is that you don't need to install this plugin. How is that not confusing?
![image](https://user-images.githubusercontent.com/6358971/127156337-1ce29f8a-b0e6-4bc0-ba88-94481d4242d8.png)

**Comment by alexander-akait** [comment]
Terser webpack plugin comes with webpack v5, but if you need to use manually plugin, I.e. require, you need to install plugin itself, it is how work any package
