### ISSUE TITLE
Usage with webpack 5 

### ISSUE THREAD

**Issue by gaurav5430** [webpack-contrib/terser-webpack-plugin#416]
Documentation Is:

- [x] Missing
- [ ] Needed
- [x] Confusing

### Please Explain in Detail...
Usage with webpack 5 is not explained in the README. It just mentions that webpack 5 internally includes terser, but does not mention how to pass on / override the terser options in the default included terser plugin

### Your Proposal for Changes
Add a section and examples for usage with webpack 5

**Comment by alexander-akait** [comment]
There are a lot of examples in readme with options and with examples

**Comment by gaurav5430** [comment]
sorry but aren't those examples for webpack 4?

the documentation says that terser plugin is included with default with webpack 5, but doesn't have any examples for how to customise the inbuilt terser configuration or how to override it

- should we create a new instance of terser plugin and provide the terserOptions to it?
- should we expect to get the already included instance from inside webpack and then modify its config?
- or is there a config option which gets forwarded to the included terser instance, say a config property called terserOptions which gets forwarded to the internal terser

**Comment by alexander-akait** [comment]
Here example usage of plugin https://github.com/webpack-contrib/terser-webpack-plugin#getting-started

> or is there a config option which gets forwarded to the included terser instance, say a config property called terserOptions which gets forwarded to the internal terser

No abilities to avoid breaking changes between releases

**Comment by gaurav5430** [comment]
the example usage says there is no need to install this plugin with webpack 5 but is that true?

if I have to customise the internal terser plugin available in webpack 5, how do I do that?

**Comment by alexander-akait** [comment]
> the example usage says there is no need to install this plugin with webpack 5 but is that true?

if you need custom options you need to use example from https://github.com/webpack-contrib/terser-webpack-plugin#getting-started

**Comment by gaurav5430** [comment]
ok, so I need new TerserPlugin() and then pass it on to webpack `optimization.minimizer` just like the setup for webpack 4 ?

**Comment by alexander-akait** [comment]
Yes, if you need custom options

**Comment by Protosac** [comment]
I have to agree the documentation is pretty confusing here and apparently incorrect. It would be helpful to clarify the wording so that its clear that if you're trying to setup custom configuration for Terser with webpack 5, you *do* need to install it. It isn't available as an import in my current webpack 5 installation. So in fact I do need to install it in order to set customize settings.

**Comment by alexander-akait** [comment]
PR welcome if you have idea how we can improve this

**Comment by 0dp** [comment]
When ever I try to follow the documentation regarding TerserPlugin in Webpack5
ultimately, I always end up with `Error: Cannot find module 'terser-webpack-plugin'`
So even though I can see its included in Webpack5 it does not seem to be available.

So atm I'm running it with terser-webpack-plugin installed in the project.

**Comment by alexander-akait** [comment]
this is how package manager works, it is not feature/bug in webpack, you need to install dep to use it directly in your project

**Comment by 0dp** [comment]
> this is how package manager works, it is not feature/bug in webpack, you need to install dep to use it directly in your project

If you are using webpack v5 or above you do not need to install this plugin. Webpack v5 comes with the latest terser-webpack-plugin out of the box. Using Webpack v4, you have to install terser-webpack-plugin v4.

**Comment by alexander-akait** [comment]
If you use plugin directly in your `webpack.config.js`, you **always** need to install `terser-webpack-plugin` and put it in your `package.json`

**Comment by 0dp** [comment]
Where else would you use it?
I mean does it not make sense to parse options?

**Comment by 0dp** [comment]
So ultimately it should read,
```Webpack v5 comes with the latest terser-webpack-plugin out of the box. If you are using Webpack v5 or above and wish to customize the options, you will still need to install terser-webpack-plugin. Using Webpack v4, you have to install terser-webpack-plugin v4.```
