### ISSUE TITLE
unicode bug 

### ISSUE THREAD

**Issue by yukinotech** [webpack-contrib/terser-webpack-plugin#420]
when i use babel and webpack , i found this issue. i don't know is this a bug or feature.

only use babel

The whitespace in code is some unicode ,which can be transform by `@babel/plugin-transform-literals` (include in `@babel/preset-env`)
```
let a = '\t\n\v\f\r                　\u2028\u2029\ufeff'
```
after babel transform
```
var a = "\t\n\x0B\f\r \xA0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u202F\u205F\u3000\u2028\u2029\uFEFF";
```

however ,  use babel and webpack together, with webpack config:
// weboack.config.js
```
  optimization: {
    minimize: true, 
  },
```

finally, the result go back to 
```
let a = '\t\n\v\f\r                　\u2028\u2029\ufeff'
```

the process in webpack is:
sourece code => babel  transform(`target : { chrome: '36',  android: '4'}`) => terser-webpack-plugin transform

let a = '\t\n\v\f\r                　\u2028\u2029\ufeff'  
 => 
var a = "\t\n\x0B\f\r \xA0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u202F\u205F\u3000\u2028\u2029\uFEFF"; 
=> 
let a = '\t\n\v\f\r                　\u2028\u2029\ufeff'  

as u can see ,` terser-webpack-plugin` change babel result 。 which means  `@babel/plugin-transform-literals`  is useless, 

i dont know if i describe the issue clearly，i am expecting a reply，thank you

**Comment by snitin315** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
