### ISSUE TITLE
Release new version with ts typings

### ISSUE THREAD

**Issue by gzaripov** [webpack-contrib/terser-webpack-plugin#432]
I see that typescript typings were added last yesterday. could you release a new package version with these types?

Typings in @types/terser-webpack-plugin don't work with webpack 5.

**Comment by alexander-akait** [comment]
Release will be today, I got sick covid, so sorry for delay

**Comment by snitin315** [comment]
> I got sick covid

Take care, I hope you are better soon ⭐
