### ISSUE TITLE
Constructor type error in 5.2.0

### ISSUE THREAD

**Issue by gpoitch** [webpack-contrib/terser-webpack-plugin#437]
### Actual Behavior

Using the plugin throws a typescript type error as of version 5.2.0:
```
error TS2351: This expression is not constructable.
  Type 'typeof import("/Users/user/app/node_modules/terser-webpack-plugin/types/index")' has no construct signatures.

259       minimizer: [new TerserPlugin()]
```

### Expected Behavior

Does not throw an error for documented usage

### How Do We Reproduce?

Simply using it as documented
```js
// @ts-check
const TerserPlugin = require('terser-webpack-plugin')

module.exports = {
  optimization: {
    minimize: true,
    minimizer: [new TerserPlugin()]
  }
}
```

**Comment by alexander-akait** [comment]
What is typescript version? https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/types/index.d.ts#L248

**Comment by gpoitch** [comment]
Typescript version 4.4.2 (latest)
Webpack version 5.51.1 (latest)
Node version 16.7.0

I manually downgraded to terser-webpack-plugin 5.1.4 and it works correctly, keep everything else the same

**Comment by alexander-akait** [comment]
Something wrong with ts I think here, do you have `allowSyntheticDefaultImports: true`?

**Comment by gpoitch** [comment]
> Something wrong with ts I think here, do you have allowSyntheticDefaultImports: true?

Yes. I tried with it removed and it still has the same error

**Comment by gpoitch** [comment]
Changing `export default TerserPlugin` to `export = TerserPlugin` fixed it.
I don't think you should have real exports in an ambient d.ts file only type exports

**Comment by alexander-akait** [comment]
yep, make sense, we still in commonjs

**Comment by alexander-akait** [comment]
Weird, but I can't reprice it locally, can you provide ts options?
