### ISSUE TITLE
Bug in own typings in 5.2.0

### ISSUE THREAD

**Issue by artem-malko** [webpack-contrib/terser-webpack-plugin#439]
### Bug report

Looks like we have a problem in typings.

### Actual Behavior

Errors in tsc output

```bash
node_modules/terser-webpack-plugin/types/index.d.ts(9,38): error TS2307: Cannot find module 'uglify-js' or its corresponding type declarations.
node_modules/terser-webpack-plugin/types/index.d.ts(10,33): error TS2307: Cannot find module '@swc/core' or its corresponding type declarations.
node_modules/terser-webpack-plugin/types/utils.d.ts(4,44): error TS2307: Cannot find module 'uglify-js' or its corresponding type declarations.
node_modules/terser-webpack-plugin/types/utils.d.ts(5,38): error TS2307: Cannot find module 'uglify-js' or its corresponding type declarations.
node_modules/terser-webpack-plugin/types/utils.d.ts(6,33): error TS2307: Cannot find module '@swc/core' or its corresponding type declarations.
```

### Expected Behavior

No type errors

### How Do We Reproduce?

Just try to run `node_modules/.bin/tsc` in a project with terser-webpack-plugin 5.2.0

Looks like we need to install all possible minifiers. But it looks quite strange. Why do I need to install swc, if I use esbuild?)

My tsconfig is:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "tslib": [
        "./node_modules/tslib/tslib.d.ts"
      ],
      "*": [
        "src/*"
      ]
    },
    "esModuleInterop": true,
    "declaration": false,
    "declarationMap": false,
    "moduleResolution": "node",
    "module": "commonjs",
    "incremental": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "alwaysStrict": true,
    "pretty": false,
    "jsx": "react-jsxdev",
    "strict": true,
    "strictNullChecks": true,
    "target": "es6",
    "noEmitHelpers": true,
    "importHelpers": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictPropertyInitialization": false,
    "lib": [
      "es6",
      "es2016",
      "es2017",
      "dom"
    ]
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

The optimization section from my webpack config:

```js
optimization: {
    concatenateModules: true,
    minimizer: [
      new TerserPlugin({
        minify: TerserPlugin.esbuildMinify,
      }),
    ],
  },
```

As a solution, you can add esbuild, @swc/core and uglify-js typings to dependencies.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 619.85 MB / 16.00 GB
  Binaries:
    Node: 14.17.3 - ~/n/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.14.13 - ~/n/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 88.0.1
    Safari: 14.0.1
    Safari Technology Preview: 14.1
  Packages:
    compression-webpack-plugin: 8.0.1 => 8.0.1
    terser-webpack-plugin: 5.2.0 => 5.2.0
    webpack: 5.51.1 => 5.51.1
    webpack-bundle-analyzer: 4.4.2 => 4.4.2
    webpack-cli: 4.8.0 => 4.8.0
    webpack-merge: 5.8.0 => 5.8.0
    webpack-npm-dependencies-analyzer: 1.0.1 => 1.0.1
    webpack-stats-plugin: 1.0.3 => 1.0.3
```

**Comment by alexander-akait** [comment]
Expected, you should not linting types in `node_modules`, it is optional dev dependecies

**Comment by alexander-akait** [comment]
if ts not found types, it will be `any`

**Comment by artem-malko** [comment]
Ok, thx

**Comment by alexander-akait** [comment]
hm, wait, found one strange, maybe we need report, investigate

**Comment by huineng** [comment]
right, this version breaks , i got one line more then above

```
node_modules/terser-webpack-plugin/types/index.d.ts:11:37 - error TS2307: Cannot find module 'esbuild' or its corresponding type declarations.

export type EsbuildOptions = import("esbuild").TransformOptions;
```

**Comment by artem-malko** [comment]
@huineng just add 
```
skipLibCheck: true
```
to your tsconfig as a temporary solution)

**Comment by huineng** [comment]
thanks, i can wait , i think it's probably just a matter of putting your packages as dependencies, or changing the optional or giving us the instructions we need to install these packages ourselves (not preferred)
 
```
"peerDependenciesMeta": {
    "@swc/core": {
      "optional": true
    },
    "uglify-js": {
      "optional": true
    },
    "esbuild": {
      "optional": true
    }
  },
``ù

**Comment by alexander-akait** [comment]
Looks like `typescript` don't work with `peerDependenciesMeta`, based on docs any optional deps should be any, but ts still continue report about `Cannot find module`, it is very weird, we don't have ability to mark some dependencies as optional,  looking for solution...

**Comment by huineng** [comment]
I looks to me that in ./utils you require all 3 packages (imported by ./index), so optional is not an option. They have to be there and installed before we can use typescript and webpack.

**Comment by alexander-akait** [comment]
We don't want to install all minimizer because you will get very big node_modules, found workaround - `@ts-ignore` in our declarations

**Comment by alexander-akait** [comment]
Please try https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.2.1

**Comment by huineng** [comment]
I'm afraid this doesn't solve the issue  @ts-ignore ignores errors being reported in linting, the compiler error still exists
``` 
Please note that this comment only suppresses the error reporting
```

the utils.d.ts still exports from imports that don't resolve
```
export type UglifyJSOutputOptions = import("uglify-js").OutputOptions;
export type UglifyJSOptions = import("uglify-js").MinifyOptions;
export type SwcOptions = import("@swc/core").JsMinifyOptions;
export type EsbuildOptions = import("esbuild").TransformOptions;
```

technically this could be solved by a dynamic import.then wrapped in an if ..  (or a require within an if)

full error has not changed
```
node_modules/terser-webpack-plugin/types/utils.d.ts:5:44 - error TS2307: Cannot find module 'uglify-js' or its corresponding type declarations.

5 export type UglifyJSOutputOptions = import("uglify-js").OutputOptions;
                                             ~~~~~~~~~~~

node_modules/terser-webpack-plugin/types/utils.d.ts:6:38 - error TS2307: Cannot find module 'uglify-js' or its corresponding type declarations.

6 export type UglifyJSOptions = import("uglify-js").MinifyOptions;
                                       ~~~~~~~~~~~

node_modules/terser-webpack-plugin/types/utils.d.ts:7:33 - error TS2307: Cannot find module '@swc/core' or its corresponding type declarations.

7 export type SwcOptions = import("@swc/core").JsMinifyOptions;
                                  ~~~~~~~~~~~

node_modules/terser-webpack-plugin/types/utils.d.ts:8:37 - error TS2307: Cannot find module 'esbuild' or its corresponding type declarations.

8 export type EsbuildOptions = import("esbuild").TransformOptions;
                                      ~~~~~~~~~
```

**Comment by alexander-akait** [comment]
Looks like here only one workaround - `skipLibCheck: true`, we need report this in `ts` repo

**Comment by orta** [comment]
TypeScript has a global set of types, and assumes you have access to every type you need locally which in this case is for all of those imports - but as some folks don't have each of the different options in their node_modules it will fail for them.

IMO you should use an `any` and not expose that to your users, and get users to use `/** @type {import("X").Config} */ if they need it (but I have no context, I just read the thread )

**Comment by alexander-akait** [comment]
Thanks for answer, understand

**Comment by alexander-akait** [comment]
Looks like we need small breaking change for types, but I want to say it is fix, so I will improve readme and changelog notes

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/terser-webpack-plugin/pull/442, note - here small breaking change for types due invalid usage optional dependencies types
