### ISSUE TITLE
Small type error in terserOptions

### ISSUE THREAD

**Issue by huineng** [webpack-contrib/terser-webpack-plugin#443]
after upgrading to the latest 5.2.2 (thanks for that other fix) i do see another small issue

```
error TS2345: Argument of type '{ parallel: true; terserOptions: { compress: { dead_code: boolean; 
pure_funcs: string[]; }; mangle: boolean; }; }' is not assignable to parameter of type
 'BasePluginOptions & { minify: MinimizerImplementation<unknown>; terserOptions?: unknown; }'.
  Property 'minify' is missing in type '{ parallel: true; terserOptions: { compress: 
{ dead_code: boolean; pure_funcs: string[]; }; mangle: boolean; }; }' but required in
 type '{ minify: MinimizerImplementation<unknown>; terserOptions?: unknown; }'.
```

```
(alias) new TerserPlugin<unknown>(options?: (BasePluginOptions & {
    minify: MinimizerImplementation<unknown>;
    terserOptions?: unknown;
}) | undefined): TerserPlugin<unknown>
import TerserPlugin
```

![image](https://user-images.githubusercontent.com/3482445/131980621-910cc826-5eaa-4410-97ab-1a99dbe10d3d.png)

I think this is caused by the second minify not being optional (?)

```
export type DefinedDefaultMinimizerAndOptions<T> =
  InferDefaultType<T> extends TerserOptions
    ? {
        minify?: MinimizerImplementation<InferDefaultType<T>> | undefined;
        terserOptions?: InferDefaultType<T> | undefined;
      }
    : {
        minify: MinimizerImplementation<InferDefaultType<T>>;
        terserOptions?: InferDefaultType<T> | undefined;
      };
```

thanks

**Comment by vladimiry** [comment]
The related TS issue is that the `terserMinify` imported from "terser-webpack-plugin" doesn't get accepted by `TerserPlugin` constructor when passed as `minify` option (that `terserMinify` named as used by default):

```
error TS2322: Type 'typeof terserMinify' is not assignable to type 'MinimizerImplementation<unknown>'.
  Type 'typeof terserMinify' is not assignable to type 'BasicMinimizerImplementation<unknown>'.
    Types of parameters 'minimizerOptions' and 'minifyOptions' are incompatible.
      Type 'unknown' is not assignable to type 'PredefinedOptions & CustomOptions'.
        Type 'unknown' is not assignable to type 'PredefinedOptions'.

86                         minify: terserMinify
```

**Comment by alexander-akait** [comment]
Weird, we infer default type when it is not passed, unknown should be never infered...

**Comment by 0x1af2aec8f957** [comment]
The same question +1

```bash
Property 'minify' is missing in type '{ parallel: true; terserOptions: { format: { comments: true | RegExp; }; }; extractComments: true; }' but required in type '{ minify: MinimizerImplementation<unknown>; terserOptions?: unknown; }'.
```

**Comment by alexander-akait** [comment]
somebody can provide small example?

**Comment by vladimiry** [comment]
> Weird, we infer default type when it is not passed, unknown should be never infered...

The wild guess is that the props named differently, `minifyOptions` vs `minimizerOptions` https://github.com/webpack-contrib/terser-webpack-plugin/blob/c314e33354180fe2b017d9a155a519096dec8fca/types/index.d.ts#L75

https://github.com/webpack-contrib/terser-webpack-plugin/blob/c314e33354180fe2b017d9a155a519096dec8fca/types/utils.d.ts#L44

Another/original issue is that `minify` props is currently typed as "not optional".

**Comment by alexander-akait** [comment]
> Another/original issue is that minify props is currently typed as "not optional".

Because when you use non `import("terser").MinifyOptions` you should always set `minify`, no problems here

**Comment by alexander-akait** [comment]
Just provide tsconfig.json and example usage to reproduce the problem

**Comment by alexander-akait** [comment]
I cant reproduce this inside webpack and other repos...

**Comment by alexander-akait** [comment]
`import TerserPlugin, {terserMinify} from "terser-webpack-plugin";`

is wrong usage, you should use `TerserPlugin.terserMinify`, there is not named export

**Comment by vladimiry** [comment]
Ok, then would be great `terserMinify` from "terser-webpack-plugin" gets accepted.

> Just provide tsconfig.json and example usage to reproduce the problem

> there is no named export

There is:
https://github.com/webpack-contrib/terser-webpack-plugin/blob/c314e33354180fe2b017d9a155a519096dec8fca/src/utils.js#L630
https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/types/utils.d.ts#L41

Not ready at the moment to provide isolated repro project but https://github.com/vladimiry/ElectronMail/tree/wip-webpack-ts-issue (`wip-webpack-ts-issue` branch) with  and run `yarn --pure-lockfile && yarn build:electron-main` you will get the issue I posted above.

**Comment by alexander-akait** [comment]
> Ok, then would be great terserMinify from "terser-webpack-plugin" gets accepted.

we are on commonjs, no named export allowed

**Comment by vladimiry** [comment]
> we are on commonjs, no named export allowed

Bot the runtime code, ie JS, and TS typings say to me that named importing is accepted. Anyway, if you use `TerserPlugin.terserMinify` the same issue will still be taking place.

**Comment by alexander-akait** [comment]
And please use the issue template, all necessary information for help and fix problems there, not using them, we are wasting the time of each other

**Comment by vladimiry** [comment]
I'm here to speed up the process the way I'm ready at the moment. Not the one who placed the original issue.

**Comment by alexander-akait** [comment]
Anyway way do you use `minify: terserMinify`? It is default value

**Comment by vladimiry** [comment]
The `minify` is currently not optional (typings issue), so some value should be provided. The originally placed issue highlights this fact:
```
...
Property 'minify' is missing in type
...
```

So I thought I could provide the default value (the `terserMinify` thing), but this trick also failed due to the seems to be another typings issue.

**Comment by alexander-akait** [comment]
> Module '"/path/to/ElectronMail/node_modules/terser-webpack-plugin/types/cjs"' can only be default-imported using the 'esModuleInterop' flag

**Comment by alexander-akait** [comment]
hm, found a bug

**Comment by alexander-akait** [comment]
bug on ts side, change `declare class TerserPlugin<T>` on `declare class TerserPlugin<T = TerserOptions>`, ts remove it when I publish...

**Comment by alexander-akait** [comment]
Something weird in our scripts, WIP on this, because `terser-webpack-plugin@5.2.2` from npm doesn't have `T = TerserOptions`, but we have it https://github.com/webpack-contrib/terser-webpack-plugin/blob/v5.2.2/types/index.d.ts#L210

**Comment by alexander-akait** [comment]
Please try https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.2.3

**Comment by huineng** [comment]
All good, thanks for your quick action !

**Comment by alexander-akait** [comment]
Hope we we will ~~not~~ have bug in types :smile:

**Comment by vladimiry** [comment]
Can confirm that the typings error I posted is also gone. Both ways, using `TerserPlugin.terserMinify` and named `terserMinify` import now get accepted by TS compiler.

**Comment by 0x1af2aec8f957** [comment]
This type of error still exists.

webpack error: 
```bash
[webpack-cli] webpack/webpack.base.ts:655:24 - error TS2345: Argument of type '{ parallel: boolean; terserOptions: { format: { comments: true | RegExp; }; }; extractComments: boolean; }[]' is not assignable to parameter of type 'undefined'.
```

tsconfig:
```json
{
  "compilerOptions": {
    "noImplicitThis": false,
    "alwaysStrict": true,
    "strictPropertyInitialization": false,
    "emitDecoratorMetadata": true,
    "noFallthroughCasesInSwitch": true,
    "target": "es5",
    "module": "CommonJS",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "node"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
  ],
  "exclude": [
    "node_modules"
  ]
}
```

webpack-chain config:
```typescript
config.optimization
    .minimize(isProduction)
    .minimizer('terser-webpack-plugin')
    .use(TerserPlugin, [{ /// doc: https://github.com/terser/terser#minify-options
        parallel: true,
        terserOptions: {
            format: { /// doc: https://github.com/terser/terser#format-options
                comments: isDevelopment || /@license/i,
              },
        },
        extractComments: true,
    }])
    .end()
    .splitChunks(/* <webpack.Options.SplitChunksOptions> */{
        chunks: 'all',
        minSize: 30000,
        maxSize: 80000,
        minChunks: 1,
        maxAsyncRequests: 5,
        maxInitialRequests: 3,
        automaticNameDelimiter: '-',
        name(module: {identifier: Function}, chunks: Array<{name: string}>, cacheGroupKey: string) {
            const moduleFileName: string = module.identifier().split('/').reduceRight((item: string) => item);
            const allChunksNames: string = chunks.map((item) => item.name).join('-');
            return `${cacheGroupKey}-${allChunksNames}-${moduleFileName}`;
        },
        cacheGroups: {
            default: false,
            defaultVendors: {
                test: /[\\/]node_modules[\\/]/,
                name: 'module',
                priority: 10
            }
            /* 'meri-design': {
                test: /[\/]node_modules[\/]meri-design[\/]/,
                // test: /[\/]node_modules[\/]/,
                name: 'meri-design',
                // minChunks: 1,
                priority: 1,
                enforce: true
            } */
        }
    })
    .minimizer('css')
    .use(CssMinimizerPlugin)
    .end();
```

package.json: 
```json
"webpack": "^5.47.0",
"terser-webpack-plugin": "^5.2.3",
"@types/webpack": "^5.28.0",
"@types/terser-webpack-plugin": "^5.2.0",
```

**Comment by alexander-akait** [comment]
You don't need `@types/terser-webpack-plugin`, types are built-in

**Comment by 0x1af2aec8f957** [comment]
I removed the installation `@types/terser-webpack-plugin`, and the error is still there.

webpack error: 
```bash
[webpack-cli] webpack/webpack.base.ts:652:24 - error TS2345: Argument of type '{ parallel: boolean; terserOptions: { format: { comments: true | RegExp; }; }; extractComments: boolean; }[]' is not assignable to parameter of type 'undefined'.

652     .use(TerserPlugin, [{ /// doc: https://github.com/terser/terser#minify-options
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
653         parallel: true, // 并发构建
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
659         extractComments: true, // 是否剥离注释（删除注释使用false）
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
660     }])
    ~~~~~~

error Command failed with exit code 2.
```

**Comment by alexander-akait** [comment]
You still use old types, `@types/webpack` is deprected, please read migration guide for webpack v5

**Comment by 0x1af2aec8f957** [comment]
I removed the installation `@types/webpack`, and the error is still there.

<details>
  <summary>webpack error</summary>
<pre>
[webpack-cli] webpack/webpack.base.ts:652:24 - error TS2345: Argument of type '{ parallel: boolean; terserOptions: { format: { comments: true | RegExp; }; }; extractComments: boolean; }[]' is not assignable to parameter of type 'undefined'.

652     .use(TerserPlugin, [{ /// doc: https://github.com/terser/terser#minify-options
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
653         parallel: true,
    ~~~~~~~~~~~~~~~~
... 
659         extractComments: true,
    ~~~~~~~~~~~~~~~~~~~~~~~~
660     }])
    ~~~~~~

error Command failed with exit code 2.
</pre>
</details>

<details>
  <summary>webpack-chain config</summary>
<pre>
config.optimization /// doc: https://webpack.js.org/configuration/optimization/
    .minimize(isProduction)
    .minimizer('terser-webpack-plugin')
    .use(TerserPlugin, [{ /// doc: https://github.com/terser/terser#minify-options
        parallel: true,
        terserOptions: {
            format: { /// doc: https://github.com/terser/terser#format-options
                comments: isDevelopment || /@license/i,
              },
        },
        extractComments: true,
    }])
    .end()
    .splitChunks(/* <webpack.Options.SplitChunksOptions> */{
        chunks: 'all',
        minSize: 30000,
        maxSize: 80000,
        minChunks: 1,
        maxAsyncRequests: 5,
        maxInitialRequests: 3,
        automaticNameDelimiter: '-',
        name(module: {identifier: Function}, chunks: Array<{name: string}>, cacheGroupKey: string) {
            const moduleFileName: string = module.identifier().split('/').reduceRight((item: string) => item);
            const allChunksNames: string = chunks.map((item) => item.name).join('-');
            return `${cacheGroupKey}-${allChunksNames}-${moduleFileName}`;
        },
        cacheGroups: {
            default: false,
            defaultVendors: {
                test: /[\\/]node_modules[\\/]/,
                name: 'module',
                priority: 10
            }
            /* 'meri-design': {
                test: /[\/]node_modules[\/]meri-design[\/]/,
                // test: /[\/]node_modules[\/]/,
                name: 'meri-design',
                // minChunks: 1,
                priority: 1,
                enforce: true
            } */
        }
    })
    .minimizer('css')
    .use(CssMinimizerPlugin)
    .end();
</pre>
</details>

<details>
  <summary>package.json</summary>
<pre>
"webpack": "^5.47.0",
"terser-webpack-plugin": "^5.2.3"
</pre>
</details>

Make sure that this problem is caused by `terser-webpack-plugin`. I'll look at the source code of type declaration later.

**Comment by 0x1af2aec8f957** [comment]
I found the problem：

The type definition here does not use abstract classes：https://github.com/webpack-contrib/terser-webpack-plugin/blob/210a5a03d28108b29821a71af3fd6db0226239b8/types/index.d.ts#L210

However, `webpack-chain` uses `ConstructorParameters` to infer parameter types: https://github.com/neutrinojs/webpack-chain/blob/8ca76d3301d4fd446b0663ed09aa8912645c0344/types/index.d.ts#L116

`Constructorparameters` is defined here: https://github.com/microsoft/TypeScript/blob/c8ada74862c0b17cb73ae06e01b1e89f68ffcd5c/lib/lib.es5.d.ts#L1531

I changed the code to meet my needs：
```typescript
// line-210
declare abstract class TerserPlugin<T = TerserOptions> {
  /**
   * @private
   * @param {any} input
   * @returns {boolean}
   */
...
```
After the above code changes, `new terserplugin()` cannot be used directly, and the abstract class cannot be instantiated directly before it is implemented.

Or deleting [the dynamic type `T`](https://github.com/webpack-contrib/terser-webpack-plugin/blob/210a5a03d28108b29821a71af3fd6db0226239b8/types/index.d.ts#L250) here can also be inferred correctly: 
```typescript
/* constructor(
    options?:
      | (BasePluginOptions & DefinedDefaultMinimizerAndOptions<T>)
      | undefined
  ); */

constructor(
    options?:
      | (BasePluginOptions & DefinedDefaultMinimizerAndOptions<TerserOptions>)
      | undefined
  );
```

**Comment by alexander-akait** [comment]
Please open an issue in `webpack-chain`, `webpack-chain` uses old types (for webpack v4)

**Comment by 0x1af2aec8f957** [comment]
@alexander-akait OK, thank you for your reply.
