### ISSUE TITLE
Terser version not updated?

### ISSUE THREAD

**Issue by Friksel** [webpack-contrib/terser-webpack-plugin#46]
With Terser being at version 3.13.1 now with some important bugfixes like mangling had some problems, is there a reason terser-webpack-plugin still has terser 3.8.1 as dependency in its package.json?

I tried building a new terser-webpack-plugin dist with an upgrade to the latest terser in the terser-webpack-plugin package.json, but it's missing files to build for some reason. So that doesn't seem to be the right workflow?!

Can we just install the latest terser module in our own projects (so install the latest terser in the root of node_modules) so that terser-webpack-plugin uses that version instead? Or is terser baked in terser-webpack-plugin / needs its own terser module inside its own node_modules folder instead?

Best in my opinion would be if the terser-requirement would be kept up to date in terser-webpack-plugin builds so we can rely on having the latest terser after upgrading terser-webpack-plugin.

**Comment by evilebottnawi** [comment]
@Friksel your package manager (`npm`/`yarn`/etc) use cache for `terser`, me recommendation to setup deps bot (example `renovate`) and setup `lock file maintenance` to avoid this problems, we can't increase `terser` version every time he was updated so we use `^` in `package.json`, anyway in future we will update `terser` on each release to avoid problems with caching, thanks for issue

**Comment by Friksel** [comment]
@evilebottnawi Not sure what you're saying exactly. But to be clear: only terser-webpack-plugin uses the terser package which was installed by terser-webpack-plugin. I don't have any problems with npm packages not up to date or anything, it's just terser-webpack-plugin not updating its required terser-package. But do I understand this will be updated from now on by terser-webpack-plugin?
