### ISSUE TITLE
Add TERSER_NO_BUNDLE environmental variable to cache keys

### ISSUE THREAD

**Issue by fabiosantoscode** [webpack-contrib/terser-webpack-plugin#47]
* Operating System: any
* Node Version: any
* NPM Version: any 
* webpack Version: any
* terser-webpack-plugin Version: latest

### Feature Proposal

The proposal is to add $TERSER_NO_BUNDLE to the cache keys. When set to 1, it changes the behaviour of terser by reading the source code in lib/ instead of dist/bundle.js

### Feature Use Case

If TERSER_NO_BUNDLE is not part of the cache keys, then enabling it wouldn't break the cache, while terser behaviour would change. This variable makes it easy to debug issues with terser when not being used directly.

**Comment by fabiosantoscode** [comment]
And probably the node version too should be there. When it changes, terser behaviour could change. We often try other node versions to try and isolate an issue better.

**Comment by evilebottnawi** [comment]
@fabiosantoscode 

> The proposal is to add $TERSER_NO_BUNDLE to the cache keys. When set to 1, it changes the behaviour of terser by reading the source code in lib/ instead of dist/bundle.js

Feel free to send a PR, it should be easy.

> And probably the node version too should be there. When it changes, terser behaviour could change. We often try other node versions to try and isolate an issue better.

Can you elaborate?

**Comment by evilebottnawi** [comment]
@fabiosantoscode we should invalidate cache of `node` version was changes?

**Comment by evilebottnawi** [comment]
Unfortunately, terser doesn't have `lib` directory in package 

> ls -l node_modules/terser

```shell
total 80
drwxr-xr-x 2 evilebottnawi evilebottnawi  4096 фев 25 14:22 bin
-rw-r--r-- 1 evilebottnawi evilebottnawi   675 окт 26  1985 CHANGELOG.md
drwxr-xr-x 2 evilebottnawi evilebottnawi  4096 фев 25 14:22 dist
-rw-r--r-- 1 evilebottnawi evilebottnawi  1348 окт 26  1985 LICENSE
-rw-r--r-- 1 evilebottnawi evilebottnawi  3949 фев 25 14:22 package.json
-rw-r--r-- 1 evilebottnawi evilebottnawi    86 окт 26  1985 PATRONS.md
-rw-r--r-- 1 evilebottnawi evilebottnawi 52921 окт 26  1985 README.md
drwxr-xr-x 2 evilebottnawi evilebottnawi  4096 фев 25 14:22 tools
```

**Comment by fabiosantoscode** [comment]
I might just add it again. I'm not very satisfied with having to re-run Rollup every time I change a single thing in the code.

**Comment by evilebottnawi** [comment]
@fabiosantoscode if you add it again i reopen issue and release new version with this feature, just do it and ping me again, thanks
