### ISSUE TITLE
webpack build freezing when using terser

### ISSUE THREAD

**Issue by fabiosantoscode** [webpack-contrib/terser-webpack-plugin#48]
* Operating System: linux
* Node Version: @StefanSchoof can you fill this in?
* NPM Version: @StefanSchoof this too
* webpack Version: @StefanSchoof and here
* terser-webpack-plugin Version: @StefanSchoof and here

Sorry for not following the template, but I don't have all the information. @StefanSchoof will come and complete the issue and I'll edit in the information.

### Expected Behavior

The build should finish.

### Actual Behavior

Webpack freezes for at least 60 minutes (the build times out).

### Code

switch.js:
```js
"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const msRestAzure = __importStar(require("ms-rest-azure"));
const azure_keyvault_1 = require("azure-keyvault");
async function getConnectionString() {
    const cred = msRestAzure.loginWithAppServiceMSI({ resource: 'https://vault.azure.net' });
    const client = new azure_keyvault_1.KeyVaultClient(await cred);
    const secret = await client.getSecret(process.env.KEYVAULT_URI, 'iotHubConnectionString', '');
    return secret.value;
}
exports.getConnectionString = getConnectionString;
```

webpack config:

```js
const path = require('path');

module.exports = {
    mode: 'production',
    target: 'node',
    entry: {
        'switch': './switch.js'
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name]/[name].js',
        libraryTarget: 'commonjs2'
    },
    resolve: {
        extensions: ['.ts', '.js', '.json'],
        modules: [
            'node_modules',
            'src'
        ]
    },
}
```

### How Do We Reproduce?

run NODE_ENV=production webpack with the above config and entry file

 [:snowman: original issue link here](https://github.com/terser-js/terser/issues/204)

**Comment by fabiosantoscode** [comment]
Probably important to mention that this is being run inside a VM.

I'm pretty sure that this is not terser freezing since it has no async code at all.

**Comment by StefanSchoof** [comment]
Node Version: 10.14.2
NPM Version: 6.4.1
webpack Version: 4.27.1
terser-webpack-plugin Version: 1.1.0

**Comment by dpogue** [comment]
We've run into this issue too, on macOS High Sierra and Mojave (not in a VM). We fixed it by downgrading `terser` (after stumbling upon https://github.com/terser-js/terser/issues/204).

Node version: 10.14.2
npm version: 6.5.0
Webpack version: 4.28.2
terser-webpack-plugin version: 1.2.0

**Comment by dpogue** [comment]
Will also add that when I ran into this bug, I tried downgrading webpack to 4.27.1 and also tried downgrading terser-webpack-plugin to 1.1.0. Neither made a difference, the builds would still hang as long as terser itself was upgraded.

**Comment by evilebottnawi** [comment]
@StefanSchoof @dpogue what os you use? Please create reproducible test repo

**Comment by StefanSchoof** [comment]
My code is at https://github.com/StefanSchoof/espresso/tree/terser/func. The error occurs on the azure pipeline (a Ubuntu 1604  VM in the azure size Standard DS2 v2). I can reproduce on a Ubuntu 1804 VM in azure with the same size. 

```
git clone https://github.com/StefanSchoof/espresso.git
git checkout terser
cd func
npm install
npx webpack
```

**Comment by StefanSchoof** [comment]
No, this a "real" Linux VMs. I can currently not try on a non VM Linux. So maybe it can occur localy. @fabiosantoscode How was your setup for the repro?

**Comment by evilebottnawi** [comment]
@StefanSchoof can you try `1.2.0` version?

**Comment by StefanSchoof** [comment]
I updated to 1.2.1 and some minutes I cancelled locally. The Build still runs at https://dev.azure.com/sschoof/espresso/_build/results?buildId=363 (function job) I think it will run again hit the 60min limit.

**Comment by evilebottnawi** [comment]
@StefanSchoof Can you try downgrade `terser` (change resolution if you use `yarn` or change version in lock file)? We need find place where it is broken, if downgrade helpt o you i think problem in terser and we continue search problem in terser.

**Comment by evilebottnawi** [comment]
@StefanSchoof hm, i think problem is not part of `terser` plugin because we did not changed logic for a long time, we just run `terser` in multi threading. If downgrading help to you problem on `terser` side or in your environment.

Anyway let's debug this. We need manually setup `terser-webpack-plugin` and disable `cache` and `parallels`. 

Try:
```js
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  optimization: {
    minimizer: [new TerserPlugin({ cache: false, parallel: false })],
  },
};
```

**Comment by StefanSchoof** [comment]
With this options the problem still occurs.

Is there an way to see the used terser options?
If I run:
```
npx webpack --mode development
npx terser dist/switch/switch.js
```
All works. Maybe the webpack plugin set a option which triggers the problem.

**Comment by evilebottnawi** [comment]
@StefanSchoof you can try https://github.com/webpack-contrib/terser-webpack-plugin#minify, just use `terser` instead `uglify-module` and avoid all options or setup only needed

**Comment by StefanSchoof** [comment]
I take a look into the minify.js and changed the code to extract options and the input. With this I could write a repro without webpack. Think this bug should continue at https://github.com/terser-js/terser/issues/204

**Comment by StefanSchoof** [comment]
Thanks for all the quick help.

**Comment by evilebottnawi** [comment]
@StefanSchoof So we can close issue here?

**Comment by StefanSchoof** [comment]
I think yea. I like to hear from @fabiosantoscode if he see things the same.

**Comment by fabiosantoscode** [comment]
Let's do that. I'll work on this tomorrow. Thanks for the help @evilebottnawi
