### ISSUE TITLE
Doesn't support IE11

### ISSUE THREAD

**Issue by aniruddhashevle** [webpack-contrib/terser-webpack-plugin#481]
### Bug report
https://stackoverflow.com/questions/71704578/terser-webpack-plugin-doesnt-support-ie11

### Actual Behavior
Should support IE11 by default

### Expected Behavior
Doesn't support IE11

**Comment by vankop** [comment]
maybe you need to play with terser options https://github.com/terser/terser . btw will be great if you can reduce this to reproducible repo.

**Comment by alexander-akait** [comment]
Sorry, without reproduce test repo we can't help
