### ISSUE TITLE
5.3.2 package release does not include dist. 

### ISSUE THREAD

**Issue by dwjohnston** [webpack-contrib/terser-webpack-plugin#491]
### Bug report

Latest publish (5.3.2) appears to have not included the dist folder. 

### Actual Behavior

When I install terser-webpack-plugin, the package.json `main` property says `dist/index.js` but no dist folder is included. 

This can cause error messages like this one in create-react-app https://github.com/facebook/create-react-app/issues/10515

### Expected Behavior

Those files should be included. 

### How Do We Reproduce?

```
yarn init
yarn add terser-webpack-plugin 

```

navigate to the node_modules folder and see that dist is not included. 

Also, repro here: https://github.com/dwjohnston/terser-wb-rerpro/tree/main

**Comment by shermify** [comment]
Can confirm, there is nothing in the package.

**Comment by alexander-akait** [comment]
Please try https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.3.3
