### ISSUE TITLE
Published package missing dist folder

### ISSUE THREAD

**Issue by jereckley** [webpack-contrib/terser-webpack-plugin#492]

**Comment by ChristmasWoe** [comment]
Same

**Comment by helkaroui** [comment]
Same

**Comment by JWambaugh** [comment]
Same, getting error "Cannot find module 'node_modules/terser-webpack-plugin/dist/index.js'. Please verify that the package.json has a valid "main" entry"

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack-contrib/terser-webpack-plugin/issues/491, please update to 5.3.3
