### ISSUE TITLE
Webpack5: can not get the properties names "published", "closed", "locked" mangled 

### ISSUE THREAD

**Issue by thucnh** [webpack-contrib/terser-webpack-plugin#498]
### Bug report
I have several classes and some of them have properties with names 
- published
- closed
- locked

I'm expecting these props got mangled to shorter names

### Actual Behavior
They are still have the same names as they was in typescript code

**Comment by alexander-akait** [comment]
Please ask this in terser repo, we just a plugin and run terser inside https://github.com/terser/terser, thank you
