### ISSUE TITLE
Way to exclude a file or section of code from minification

### ISSUE THREAD

**Issue by tetranoir** [webpack-contrib/terser-webpack-plugin#501]
### Modification Proposal

Way to exclude a file or section of code from minification. 

### Expected Behavior / Situation

I'm using [GPU.js](https://github.com/gpujs/gpu.js/) which compiles JavaScript into WebGL. The minification process uses JS syntax that is not perserved in GPU.js's compilation and causes runtime errors in WebGL.

### Actual Behavior / Situation

It would be great to be able to exclude a file or section of code from minifcation.

**Comment by alexander-akait** [comment]
Sorry, it is impossible, please report about minifcation problems in `terser` repo https://github.com/terser/terser

**Comment by alexander-akait** [comment]
As workaround you can switch to `swc` https://github.com/webpack-contrib/terser-webpack-plugin#swc, almost all options are compatbility and it is faster
