### ISSUE TITLE
Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS

### ISSUE THREAD

**Issue by martinGrig** [webpack-contrib/terser-webpack-plugin#506]
I cannot build my project because of yarn audit stopping my build due to high severity in the terser package.
My terser-webpack-plugin is v5.3.3
Check image:
<img width="643" alt="Screenshot 2022-07-26 at 10 12 02" src="https://user-images.githubusercontent.com/64526931/180957352-cca516d1-b1d9-47de-a3c5-d5bd19cd8728.png">

**Comment by alexander-akait** [comment]
Please update your deps locally, terser is a transive dep, run `rm -rf node_modules package-lock.json && npm i`
