### ISSUE TITLE
Terser version requires security update

### ISSUE THREAD

**Issue by mitchellroberts11** [webpack-contrib/terser-webpack-plugin#507]
### Bug report

Version of terser currently used (15.14.1) is missing a security patch (implemented in 5.14.2). See https://github.com/terser/terser/blob/master/CHANGELOG.md#v5142.

### Actual Behavior

In repositories which include terser-webpack-plugin, dependabot alerts are raised for terser. See below:

![image](https://user-images.githubusercontent.com/78336079/181171019-8cf00369-b32e-4250-9c41-17c26dff1b3d.png)

### Expected Behavior

No dependabot alerts should be raised from dependencies included from terser-webpack-plugin.

### How Do We Reproduce?

I assume that if dependabot is set up for this repo, there is already a dependabot alert? If not, I believe creating a new repo with dependabot set up and adding a dependency to `terser-webpack-plugin: 5.3.3` will raise a dependabot alert.

**Comment by alexander-akait** [comment]
Duplicate of https://github.com/webpack-contrib/terser-webpack-plugin/issues/502, update locally deps
