### ISSUE TITLE
Setting compress to false no longer prevents compression in 5.3.5.

### ISSUE THREAD

**Issue by amoser67** [webpack-contrib/terser-webpack-plugin#513]
### Bug report

Setting the "compress" terserOptions property to false no longer seems to have any effect in 5.3.5.

5.3.3 works fine, but 5.3.5 compresses my JS even when set to false.

### Actual Behavior

Setting 'compress' to false in terser options does not prevent webpack from compressing applicable JS.

### Expected Behavior

Setting compress to false in terser options should prevent webpack from compressing applicable JS.

### How Do We Reproduce?

Try processing a JS file using the following optimization object, and you will notice that the output is compressed:

```
optimization: {
    minimizer: [
        new TerserPlugin({
            parallel: true,
            extractComments: true,
            terserOptions: {
                compress: false,
                mangle: false,
            }
        })
    ]
}
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

Not applicable.

**Comment by alexander-akait** [comment]
Sorry for delay, fixed - https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.3.6
