### ISSUE TITLE
Issue with acorn

### ISSUE THREAD

**Issue by DanTheMan827** [webpack-contrib/terser-webpack-plugin#519]
### Bug report

When using this on an entry point requiring `acorn`, the file appears to be incorrectly minified causing an error.

![image](https://user-images.githubusercontent.com/790119/189436872-93204c8f-faf3-480d-be63-aec71971f1c6.png)

### Actual Behavior

The file should be minified without error

### Expected Behavior

The optimization appears to transform a large block of escaped unicode text into the unescaped characters, this seems to cause an issue somewhere.

### How Do We Reproduce?

https://github.com/DanTheMan827/webpack-terser-acorn-issue

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 1.33 GB / 13.90 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.22000.120
  Packages:
    babel-loader: ^8.2.5 => 8.2.5
    html-webpack-plugin: ^4.5.2 => 4.5.2
    pug-loader: github:DanTheMan827/pug-loader => 2.4.1
    webpack: ^5.74.0 => 5.74.0
    webpack-cli: ^4.10.0 => 4.10.0
```

**Comment by alexander-akait** [comment]
Please open an issue in `terser` repo - https://github.com/terser/terser, we just wrapper/runner for this tool

**Comment by DanTheMan827** [comment]
If `ascii_only` is enabled, the module minifies without issue.

Just putting this workaround here if anyone has a similar issue

**Comment by alexander-akait** [comment]
Let's close here, because we can't fix it here, anyway thank you for the issue
