### ISSUE TITLE
function params print with 'console.log', is not deleted when 'drop_console' set true

### ISSUE THREAD

**Issue by xiaoyouyu** [webpack-contrib/terser-webpack-plugin#522]
- terser-webpack-plugin Version: 5.3.3

**Settings**
`
terserOptions: {
            compress: {
                drop_debugger: true,
                drop_console: true,
                dead_code: true,
            }
}
`

**Examples that can be deleted**
`
function(){
    console.log(111,"????");
}
`

**Examples that cannot be deleted**
`
function(params){
    console.log(111, "????", ...params);
}
`

**Other**
Set 
`pure_funcs: ['console.log','console.*','window.console'] `
It's without effect

**Comment by alexander-akait** [comment]
Please open an issue in https://github.com/terser/terser, we just wrapper for this tool
