### ISSUE TITLE
terser-webpack-plugin stable version

### ISSUE THREAD

**Issue by Prudhvicharan** [webpack-contrib/terser-webpack-plugin#524]
### Bug report

Hi,
We have updated the terser-webpack-plugin package to the latest version(5.3.6)

The latest version of opener has 1 High Vulnerability
Is there a way to fix this vulnerability? If so, can you please let us know how to do?

And Latest Version was published on 08/29/2022. Can you please also state the release date of next version?

**Comment by alexander-akait** [comment]
We don't have the next version, current version is stable, I don't see any vulnerability, please format your issue using the issue template so I will investigate where problem is. I will reopen when you fixed it, thank you
