### ISSUE TITLE
esbuild minify does not produce warnings

### ISSUE THREAD

**Issue by ankurk91** [webpack-contrib/terser-webpack-plugin#548]
* terser-webpack-plugin version latest (5.3.6)
* webpack version latest (5.75.0)
* node-js version 18.14
* esbuild latest (0.17.x)

I have this incorrect code in my project (legacy)

```js
const form = new Array;

if (!form instanceof FormData) {
  console.log("error in form")
}
```

When i use this plugin to minify this code;
The esbuild generates some warnings but webpack shows them as "[Object object]" on terminal.
 
Something is wrong at this line
https://github.com/webpack-contrib/terser-webpack-plugin/blob/15e3e35fda1a6c7f48127f498f1de6498f8026a6/src/utils.js#L703

Thanks.

**Comment by alexander-akait** [comment]
Sorry for delay, will look and fix soon :sta

**Comment by alexander-akait** [comment]
Fixed: https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.3.7, feel free to feedback
