### ISSUE TITLE
babel-loader with regex property on mangle doesn't work correctly

### ISSUE THREAD

**Issue by cs09g** [webpack-contrib/terser-webpack-plugin#55]
* Operating System: Windows 7
* Node Version: v10.13.0
* NPM Version: 6.4.1
* webpack Version: 3.10.0
* terser-webpack-plugin Version: 1.2.1

### Expected Behavior
when `mangle` is set, the codes should be mangled both on declaration and usage part.

### Actual Behavior
the code is mangled only on usage part.

### Code

```js
  // webpack.config.js
  ...
  module: {
    rules: [{
      exclude: /node_modules/,
      use: {
        loader: "babel-loader",
      },
    }],
  },
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          mangle: {
            properties: {
              regex: /^_/,
            },
          },
        },
      }),
    ],
  },
  ...
```

### What it looks like
![image](https://user-images.githubusercontent.com/7428017/51020625-760e5400-15c2-11e9-8d42-6b484c20661e.png)
`_setupAndExtendOptions` is mangled to `this.M`, but `key: '_setupAndExtendOptions',` is not mangled as `M` so it throws `TypeError: this.M is not a function`

### How Do We Reproduce?
add babel-loader
```javascript
  module: {
    rules: [{
      exclude: /node_modules/,
      use: {
        loader: "babel-loader",
      },
    }],
  },
```

**Comment by evilebottnawi** [comment]
@cs09g better ask this question in `terser`, we just wrapper, create issue with original code in `terser` repo.  Thanks!
