### ISSUE TITLE
plugin running jest tests with maximum number of workers in Bitbucket Pipeline - causing exceeded memory limit errors

### ISSUE THREAD

**Issue by drewg2009** [webpack-contrib/terser-webpack-plugin#552]
### Bug report

During the `npm run build`, `terser-webpack-plugin` is running jest tests with max workers causing out of memory issues with Bitbucket Pipelines and likely other pipeline configurations with limited resources.

### Actual Behavior
The `npm run build` step starts building a production version of our react app. 

It kicks off the create react app build script. 

During the build, the `terser-webpack-plugin` begins running jest tests with the maximum number of workers. 

This is causing our pipeline to fail.

### How Do We Reproduce?
It is hard to reproduce this without having a bitbucket pipeline setup. 

However I can provide the logs that prove that jest is running during the build causing an out of memory issue. 

This log file attached shows the memory usage of different processes during the `npm run build` step. 
Search for `terser-webpack-plugin`, and you will find the jest workers spawned right before the out of memory issue occurs. 

[pipelineLog-with terser-webpack-plugin out of memory issue.txt](https://github.com/webpack-contrib/terser-webpack-plugin/files/11017729/pipelineLog-with.terser-webpack-plugin.out.of.memory.issue.txt)

**Comment by alexander-akait** [comment]
Sorry, it means a file (and souce maps?) requires more memory, we can't do something here, you can try to switch on `swc` or please increase your memory

**Comment by drewg2009** [comment]
Why is it running jest during a build step?

**Comment by alexander-akait** [comment]
We don't run jest tests, we use `jest-worker` to create multiple threads, sorry we can't fix it, sometimes you have very big files and you need a lot of memory to minify them, moving files to own thread is better for memory (that is why it is enabled by default), also you can disable this logic https://github.com/webpack-contrib/terser-webpack-plugin#parallel, feel free to feedback
