### ISSUE TITLE
Format option "quote_keys" breaks private variable syntax

### ISSUE THREAD

**Issue by Crizzlyy** [webpack-contrib/terser-webpack-plugin#553]
**Bug report**
Using this plugin with the `format `option `quote_keys` set to `true`, it breaks a line that defines a static private variable. I noticed this when adding a library called **pdfjs** for rendering pdf's. [Here's the first line that breaks.](https://github.com/mozilla/pdfjs-dist/blob/master/build/pdf.js#L1172)

**Actual Behavior**
**In**
`static #docId = 0;`

**Out**
`static #"A"= 0;`

**Expected Behavior**
**In**
`static #docId = 0;`

**Out**
`static "#A"= 0;` or `static #A = 0;` since this ain't a object literal(?)

**How Do We Reproduce?**
Adding [*pdfjs-dist*](https://github.com/mozilla/pdfjs-dist) and running it through terser should do. We're running webpack + babel transpiled bundles through terser and here's where I noticed this syntax error after a bit of digging where the error could be and landed upon this format option in this plugin.

Let me know if there's any additional information I can add to the issue if something's unclear or if you can't reproduce!

**Comment by alexander-akait** [comment]
Please open an issue in the `terser` repo, it is just a wrapper for minication tools - https://github.com/terser/terser, also please check you have the latest version of `terser` (`npm ls terser`), thank you
