### ISSUE TITLE
impossible to keep the name of a function

### ISSUE THREAD

**Issue by chiqui3d** [webpack-contrib/terser-webpack-plugin#56]
I can not save the name of a function, these are my options

```js
new TerserPlugin({
                extractComments: false,
                terserOptions: {
                    compress:{
                        keep_fnames: /gtag_report_conversion/,
                    },
                    mangle: {
                        keep_fnames: /gtag_report_conversion/,
                        reserved: ['gtag_report_conversion']
                    },
                    output: {
                        preamble: banner,
                        comments: false
                    }
                }
            }),
```
Why don't we have the option reserved in compress?

any idea?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Use `keep_fnames` (true) you can see example here https://github.com/terser-js/terser#minify-options-structure
