### ISSUE TITLE
No documentation for MangleOptions

### ISSUE THREAD

**Issue by fahadash** [webpack-contrib/terser-webpack-plugin#563]
Documentation Is:

- [ x ] Missing
- [ x ] Needed
- [ ] Confusing
- [ ] Not Sure?

I have been reading documentation to see if I can achieve my goal of selectively not mangle class names that are in files under a certain directory. I found MangleOptions and decided to dig deeper and found nothing.

Add some documentation for MangleOptions.

**Comment by alexander-akait** [comment]
Please read this https://github.com/terser/terser#mangle-options, we support a lot of minimifiers and they work different, so when you need more infromation please look at the minifier's documentation
