### ISSUE TITLE
Bug: minified output causes a ReferenceError

### ISSUE THREAD

**Issue by nmulle** [webpack-contrib/terser-webpack-plugin#566]
### Bug report

I have a yarn 2 mono-repo, in which I use webpack to bundle a package. From webpack v5.79.0 onwards, running the minified production bundle with Node causes a `ReferenceError: BaseClass is not defined.` The non-minified development bundle runs successfully.

I have found that the cause is probably due to terser and some issues with class names.

### Actual Behavior

The build process executes successfully. Running the generated bundle with node throws with a `ReferenceError: <name of a class in original code> is not defined.`

### Expected Behavior

Running the generated bundle should not cause a run-time error, if the non-minified bundle also runs correctly.

### How Do We Reproduce?

I have prepared a reproduction repository at https://github.com/nmulle/bug-repro-terser. All of the instructions to reproduce are in the README of that repository, however I will gladly clarify if needed.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.34 GB / 16.00 GB
  Binaries:
    Node: 18.16.0 - /private/var/folders/rt/b621fpl14rj7zwhvfk4x9zrc0000gn/T/xfs-9e1740bb/node
    Yarn: 3.3.1 - /private/var/folders/rt/b621fpl14rj7zwhvfk4x9zrc0000gn/T/xfs-9e1740bb/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Chrome Canary: 115.0.5761.0
    Firefox: 113.0.1
    Firefox Developer Edition: 107.0
    Safari: 16.4
```
Latest working webpack: 5.78.0

I am using `webpack-cli@4.10.0`.

**Comment by alexander-akait** [comment]
Sorry, I can't reproduce it, what do you to get this error?

**Comment by alexander-akait** [comment]
Bug in terser, example:
```js
import { minify } from "terser";

var code = `
(function test() {
    class RelatedClass {}
    class BaseClass {}

    class SubClass extends BaseClass {
      static field = new RelatedClass;
    }

    const subclassUser = {
      oneUse: SubClass,
      otherUse() {
        return new SubClass
      }
    };
})()
`;

var result = await minify(code);

console.log(result.code);
```

**Comment by alexander-akait** [comment]
Close in favor https://github.com/terser/terser/issues/1392, sorry, we can't fix it here

**Comment by alexander-akait** [comment]
My recommendation is to pin the version until it's fixed
