### ISSUE TITLE
[Question] how do remove console.log

### ISSUE THREAD

**Issue by arpu** [webpack-contrib/terser-webpack-plugin#57]
* Operating System:
* Node Version: 11
* NPM Version: 6 
* webpack Version: 4 
* terser-webpack-plugin Version:  master

### Feature Proposal
remove console log 

### Feature Use Case
 remove console.log in production like it was possible with uglify webpack plugin

**Comment by arpu** [comment]
tesing with 
```
 terserOptions: {
          // https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions
           extractComments: 'all',
           extractComments: /console\.log\(([^)]+)\)/,
        }
```

but no sucess :/ anyone an idea?

**Comment by evilebottnawi** [comment]
@arpu better ask this question in `terser` repo, we just wrapper around this tool

**Comment by arpu** [comment]
@evilebottnawi  ok thx  but would be good if anyone knows how to use the regex to remove the console log

**Comment by evilebottnawi** [comment]
@arpu `extractComments` option not for remove `console.log`

**Comment by arpu** [comment]
ah ok thx, looks like terser has drop_console setting

**Comment by evilebottnawi** [comment]
@arpu feel free to send a PR to `README` in `Example` section

**Comment by arpu** [comment]
for reference this works for me 
```
 minimizer: [
      new TerserPlugin({
        extractComments: true,
        cache: true,
        parallel: true,
        sourceMap: true, // Must be set to true if using source-maps in production
        terserOptions: {
          // https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions
           extractComments: 'all',
           compress: {
               drop_console: true,
           },
	}
      }),
    ]
```

@evilebottnawi  thx for your time and pointing me to the right direction

**Comment by simkessy** [comment]
Not working for me with exact same settings

**Comment by B2o5T** [comment]
Option `drop_console: true` remove all console methods.
If there is a solution to remove all console.log but keep other console methods?
Like option `pure_funcs: [ 'console.log' ]` in UglifyJS?

**Comment by dhirajforyou** [comment]
> Option `drop_console: true` remove all console methods.
> If there is a solution to remove all console.log but keep other console methods?
> Like option `pure_funcs: [ 'console.log' ]` in UglifyJS?

Here I did in terser:
`terserOptions:
                        { 
                            compress:{
                                // filter all console's statements
                                // console.error, console.log will stay
                                pure_funcs: ['console.info', 'console.debug', 'console.warn']
                            }
                        }`

**Comment by carrollcai** [comment]
> > Option `drop_console: true` remove all console methods.
> > If there is a solution to remove all console.log but keep other console methods?
> > Like option `pure_funcs: [ 'console.log' ]` in UglifyJS?
> 
> Here I did in terser:
> `terserOptions: { compress:{ // filter all console's statements // console.error, console.log will stay pure_funcs: ['console.info', 'console.debug', 'console.warn'] } }`

is work?

**Comment by dhirajforyou** [comment]
> > > Option `drop_console: true` remove all console methods.
> > > If there is a solution to remove all console.log but keep other console methods?
> > > Like option `pure_funcs: [ 'console.log' ]` in UglifyJS?
> > 
> > 
> > Here I did in terser:
> > `terserOptions: { compress:{ // filter all console's statements // console.error, console.log will stay pure_funcs: ['console.info', 'console.debug', 'console.warn'] } }`
> 
> is work?

Yes. It does work.
`"terser": "^4.0.0",
"webpack": "^4.32.2",
`
and terserOptions are mentioned as:

`compress:{
                  pure_funcs: ['console.info', 'console.debug', 'console.warn']
}`

Let me know if you need any help in setting it up

**Comment by cliqer** [comment]
Using `dropConsole `with `vitejs, rollup, and terser-plugin` somehow mesh-up `peerjs screen sharing` or maybe just `media streams`.
`Peerjs data channel` works though. Really strange :/

**Comment by LukasWillin** [comment]
Well I'm not sure where the issue lies, however since people are most likely looking here still I can give another solution:

Basically, after I minified the files with the terser-webpack plugin, I let them run through terser-CLI with just the drop_console option:
```shell
npx terser --compress drop_console=true -o build/app.js -- build/app.js
```

This apparently handles the options differently, and the console-statements are actually fully removed.

My Environment:
```json
{
    "devDependencies": {
        "webpack": "5.98.0",
        "webpack-cli": "6.0.1",
        "ts-loader": "9.5.2",
        "typescript": "5.8.2",
        "terser-webpack-plugin": "5.3.14",
        "terser": "5.39.0"
    }
}
```
```shell
npm 10.9.2
node v22.13.0
```
