### ISSUE TITLE
Updater terser to 5.20.0

### ISSUE THREAD

**Issue by peratik** [webpack-contrib/terser-webpack-plugin#579]
### Bug report

next.js uses `terser-webpack-plugin` and it uses  `"terser": "^5.19.2"`

more information is here: https://github.com/terser/terser/issues/1451

### Actual Behavior
Next.js Build failed since there is an `Unexpected token: punc ({) ` error which is related to `terser-webpack-plugin` that uses old version of `terser`

### Expected Behavior
Next.js build should be success after updating terser to `5.20.0` version

### How Do We Reproduce?

1. install the latest next.js version (13.5.1)
2. install kaboom (https://github.com/replit/kaboom)
3. import kaboom and use it (you can use https://github.com/replit/kaboom/issues/74#issuecomment-956943584 snippet)
4. try to run `npm run build`

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
It is inside next.js, we can't do that. it shows:
> Need to install the following packages: webpack-cli@5.1.4

**Comment by dxhsmwqcwelllee** [comment]
I also need the latest version  5.20.0

**Comment by dxhsmwqcwelllee** [comment]
@ericclemmons

**Comment by dxhsmwqcwelllee** [comment]
> ### Bug report
> next.js uses `terser-webpack-plugin` and it uses `"terser": "^5.19.2"`
> 
> more information is here: [terser/terser#1451](https://github.com/terser/terser/issues/1451)
> 
> ### Actual Behavior
> Next.js Build failed since there is an `Unexpected token: punc ({) ` error which is related to `terser-webpack-plugin` that uses old version of `terser`
> 
> ### Expected Behavior
> Next.js build should be success after updating terser to `5.20.0` version
> 
> ### How Do We Reproduce?
> 1. install the latest next.js version (13.5.1)
> 2. install kaboom (https://github.com/replit/kaboom)
> 3. import kaboom and use it (you can use [combine with react? replit/kaboom#74 (comment)](https://github.com/replit/kaboom/issues/74#issuecomment-956943584) snippet)
> 4. try to run `npm run build`
> 
> ### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
> It is inside next.js, we can't do that. it shows:
> 
> > Need to install the following packages: webpack-cli@5.1.4

How did you solve this?

**Comment by rudolfolah** [comment]
The version of terser should be updated to the latest, 5.24.0. There's a performance issue that is fixed in that version: https://github.com/webpack/webpack/issues/17322

**Comment by jchu231** [comment]
+1 for updating to 5.24.0, it also has a fix that causes function.name to break with minimization:
https://github.com/terser/terser/commit/aa4742a611fb59d12e241b3e844c75babed2ef0f
