### ISSUE TITLE
Cache filenames can cause "path too long" errors on Windows

### ISSUE THREAD

**Issue by splatteredbits** [webpack-contrib/terser-webpack-plugin#58]
* Operating System: Windows 2012/10
* Node Version: 10.14.1
* NPM Version: 6.4.1
* webpack Version: 4.27.1
* terser-webpack-plugin Version: 1.1.0

### Expected Behavior / Situation
Unfortunately, Windows has a maximum path length of 260 characters. I'd like to see the terser-webpack-plugin cache files with names friendlier to Windows' file system.

### Actual Behavior / Situation
Files in the cache directory have file names whose names are 124 characters, using up almost half of the available characters. This causes sporadic problems for us deploying, depending on where/how we're deploying. One of our app packages has a cached file whose path is `package\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\6d\4f\92533bbffcef2fd2ad4468c4c440e1c47d7d5a2860db0763fda881a868123115a98406fce6736831807f479dbc0812154b748630029f31c8695e17dd6b4a`. Yikes!

In our situation, our deployment tool deploys all our packages into a temp directory that for one app is 70 characters long. It fails to unpack the package when it gets to ``package\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\6d\4f\92533bbffcef2fd2ad4468c4c440e1c47d7d5a2860db0763fda881a868123115a98406fce6736831807f479dbc0812154b748630029f31c8695e17dd6b4a` because that is 198 characters long.

### Modification Proposal
I'd like to see terser-webpack-plugin use a shorter filename than `92533bbffcef2fd2ad4468c4c440e1c47d7d5a2860db0763fda881a868123115a98406fce6736831807f479dbc0812154b748630029f31c8695e17dd6b4a`. Maybe trim to 38 characters? Or use a hashing algorithm that results in shorter hashes?

**Comment by evilebottnawi** [comment]
We use `cacache` package (https://github.com/zkat/cacache) please report about this problem in `cacache` repo, also you don't need deploy `.cache` directory on `production`

**Comment by bsivanov** [comment]
We have the same problem, and I am looking into [this](https://github.com/zkat/cacache/issues/122#issuecomment-401900514):
> After thinking about this and looking into it, I've decided that this is not an issue to fix in cacache itself. The uglify plugin can **try manually changing the hash algorithm by manually passing in algorithms: ['sha1']** or such. It doesn't need very cryptographically secure algorithms, and changing it to sha1, or even sha256, would possibly remove this problem altogether for most Windows users.

Is this something we can try here?
