### ISSUE TITLE
keep_classnames and keep_fnames missing from TypeScript definition file

### ISSUE THREAD

**Issue by StephenWeatherford** [webpack-contrib/terser-webpack-plugin#59]
* Operating System: N/A
* Node Version: N/A
* NPM Version: N/A
* webpack Version: 4.28.1
* terser-webpack-plugin Version: 1.2.1

### Expected Behavior

No typescript warnings in webpack.config.js file

keep_classnames and keep_fnames should be defined in typescript definition file but are not:

export interface MinifyOptions {
    spidermonkey?: boolean;
    outSourceMap?: string;
    sourceRoot?: string;
    inSourceMap?: string;
    fromString?: boolean;
    warnings?: boolean;
    mangle?: boolean | MangleOptions;
    output?: OutputOptions;
    compress?: boolean | CompressOptions;
    nameCache?: {};
}

### Actual Behavior

Typescript squigglies:
![image](https://user-images.githubusercontent.com/6913354/51274474-2940c980-1984-11e9-8351-80a96755ba09.png)

### Code

```js
    optimization: {
        minimizer: [
            new TerserPlugin({
                terserOptions: {
                    // https://github.com/webpack-contrib/terser-webpack-plugin/

                    // Without this, parseError() will not recognize user cancelled errors.  Also makes debugging easier in production.
                    keep_classnames: true
                }
            }),
        ],
    },```

### How Do We Reproduce?

<!--
  Remove this section if not reporting a bug.

  If your webpack config is over 50 lines long, please provide a URL to a repo
  for your beefy 🍖 app that we can use to reproduce.
-->

**Comment by evilebottnawi** [comment]
Out of scope plugin, all types should be in `DefinitelyTyped` repo, please create issue in `DefinitelyTyped` repo
