### ISSUE TITLE
Change 'cache' and 'parallel' defaults to 'true'

### ISSUE THREAD

**Issue by edmorley** [webpack-contrib/terser-webpack-plugin#6]
* Operating System: Windows 10
* Node Version: 10.9.0
* NPM Version: N/A (yarn)
* webpack Version: 4.16.5
* terser-webpack-plugin Version: 1.0.2

### Feature Proposal
Currently `terser-webpack-plugin` has the `cache` and `parallel` settings set to `false` by default. I propose that they be changed to `true` by default instead.

### Feature Use Case
webpack 4 already sets those two settings to `true` by default for `uglifyjs-webpack-plugin` ([see here](https://github.com/webpack/webpack/blob/0e60343dcacd49e875da6e65701eece2a05d921f/lib/WebpackOptionsDefaulter.js#L304-L315)). Changing the defaults in `terser-webpack-plugin` will:
* reduce the amount of boilerplate required in the webpack repo when it eventually switches over to `terser-webpack-plugin`
* make it simpler for people overriding the default webpack `optimization.minimizer`, since they also will have less boilerplate, but also will be less likely to accidentally forget to enable these two important performance-boosting settings

Changing the defaults for these settings will require a major version bump, but now seems like a better time to do so, than after webpack has already started using it.

**Comment by evilebottnawi** [comment]
@edmorley It's good practice to turn off these things. Some platform doesn't support `parallel`, cache in some case can output outdated data. You should enable this features if you known what you platform support this.
/cc @michael-ciniawsky What do you think?

**Comment by edmorley** [comment]
Hi! I agree there may be cases where they should be disabled, however:
* webpack already enables them by default - this proposal only moves the defaults around
* I think the defaults should reflect the common case (where caching and parallelism works/is useful) rather than be held back by the 5% case (which can just disable it if needed)

**Comment by evilebottnawi** [comment]
@edmorley anyway it is breaking change, and we can change this only in next major release, let's left this open to dicussion

**Comment by edmorley** [comment]
Versions are cheap to bump - doesn't need to wait for a deadline :-)

**Comment by michael-ciniawsky** [comment]
I think it is a mistake for `webpack` to enable it be default in the vein of zero config or whatever, we should not enable it be default within the plugin imho and leave it **opt-in** for env where one benefits from parallelism

**Comment by PeterKottas** [comment]
99% percent of people will want to turn these on anyways. 1% that don't want this (and probably builds on some fancy docker images that doesn't work with fs or cpu as we are used to) are probably expert enough to be able to set this to false when they start seeing errors in build pipeline. Note that even for that 1% group, they would probably want cache and parallel on their own PCs. They would only find out about the problem when it kicks up a build in cloud. I am definitely all for changing this.

**Comment by dandrei** [comment]
>cache in some case can output outdated data

Does this happen often? It sounds like it would make the `cache` option unusable. Any way to avoid it?

**Comment by evilebottnawi** [comment]
@dandrei yep, we are working on this, problem only on `WDS` (in other cases it is safe)

**Comment by dandrei** [comment]
That's `webpack-dev-server`, right? Then it's safe to have the `cache` flag conditional?

     const dev = process.env.NODE_ENV !== "production";

     new TerserPlugin({
         cache: !dev,
     }),

**Comment by evilebottnawi** [comment]
@dandrei no, my typo `WSL` https://docs.microsoft.com/en-us/windows/wsl/install-win10, also be default terser doesn't use in development mode

**Comment by backyardcoder** [comment]
@edmorley : It looks like this enhancement has landed in the newest update, and this can be closed. Source code reference [here](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L305-L306).

**Comment by edmorley** [comment]
@backyardcoder hi! This issue is about changing the defaults for this package, so downstream consumers (such as webpack) don't have to set the defaults themselves - and still applies.

**Comment by evilebottnawi** [comment]
Done for next
