### ISSUE TITLE
let versus var Treeshaking Issue Caused By Terser

### ISSUE THREAD

**Issue by Lonniebiz** [webpack-contrib/terser-webpack-plugin#64]
* Operating System: Ubuntu 16.04.5
* Node Version: v10.14.2
* NPM Version: 6.70
* webpack Version: 4.29
* terser-webpack-plugin Version: 1.10

I've been advised that a Tree-shaking issue I'm having in Webpack may be being caused by terser:
https://github.com/webpack/webpack/issues/8692#issuecomment-459683396

If you scroll up from that comment, you can see the entire issue.

I'm I submitting this at the correct place?

**Comment by evilebottnawi** [comment]
@Lonniebiz no, tree shaking it is part of `webpack`, we just wrapper around `terser`, you can look source code and find what we do nothing only call `terser`

**Comment by Lonniebiz** [comment]
When I turn on terser's warnings option, I do see that terser is responsible for dropping unused functions and that's what tree-shaking is all about, right?

**Comment by evilebottnawi** [comment]
@Lonniebiz https://github.com/webpack/webpack/issues/8692#issuecomment-459683396, please create issue in terser repo

**Comment by Lonniebiz** [comment]
https://github.com/terser-js/terser/issues/249

**Comment by nyngwang** [comment]
@Lonniebiz Oh fuck! (Sorry to be rude) This is exactly the problem I'm trying to solve!
