### ISSUE TITLE
Terser v3.16.0 breaks terser-webpack-plugin

### ISSUE THREAD

**Issue by pitops** [webpack-contrib/terser-webpack-plugin#66]
The latest terser update (released an hour ago) breaks this plugin.

* Operating System:
* Node Version: 10.12.0
* NPM Version: 6.4.1
* webpack Version: 4.29.0
* terser-webpack-plugin Version: 1.2.1

### Expected Behavior

Terser to minify my code

### Actual Behavior

```bash
ERROR in js/main.6e4faa1e7d31caf0fa3b.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/<path>/node_modules/terser-webpack-plugin/dist/minify.js:175:23)

```

### How Do We Reproduce?

Delete yarn.lock

Install terser-webpack-plugin and try to run a production build where the plugin is called

### workaround

As a workaround for now if you use yarn you can add a resolution to a fixed terser version. Delete yarn.lock first and node_modules

Example (in your package.json)

```
"resolutions": {
  "terser": "3.14.1"
}
```

For npm try the suggestion by @odedi

**Comment by kurtinatlanta** [comment]
I added console logging locally and the `_terser` object is empty (`{}`) at the point where it's trying to do this:
```
  const {
    error,
    map,
    code,
    warnings
  } = _terser.default.minify({
    [file]: input
  }, terserOptions);
```

`_terser.default` is undefined and therefore it can't dereference `_terser.default.minify`.

I assume the `terser` folks must have changed something such that
```
var _terser = _interopRequireDefault(require("terser"));
```
no longer gets the right object.

**Comment by Xanngo** [comment]
I changed `_terser.default.minify` to `_terser.minify` and it works

**Comment by odedi** [comment]
https://github.com/rogeriochaves/npm-force-resolutions
for npm

**Comment by filipesilva** [comment]
https://github.com/terser-js/terser/pull/254 should address this.

**Comment by huochunpeng** [comment]
Even without any work from terser, you can fix the code in the repo, defensively support both terser 3.16 (esm) and old versions (commonjs).

```js
// import terser from 'terser';
// change to
import {minify} from 'terser';

//... change terser.minify(...) to minify(...)
```

**Comment by vladimiry** [comment]
@huochunpeng the point is that `terser` made a breaking change without bumping the major version, but just v3.14.1 => v3.16.0. Besides worth taking into the account that it's not just `terser-webpack-plugin` depends on `terser` but [many other libraries](https://github.com/terser-js/terser/network/dependents) too.

**Comment by huochunpeng** [comment]
@vladimiry you are right, I understand. I just offer a solution for this repo instead of waiting terser to fix the backward compatibility.

**Comment by kopax** [comment]
Sometimes bad things happen.

**Comment by vapurrmaid** [comment]
> I changed `_terser.default.minify` to `_terser.minify` and it works

Thanks ❤️ , verified for me running `npm run build` with:

```
devDependencies": {
    ...,
    "@vue/cli-plugin-babel": "^3.4.0",
    "@vue/cli-service": "^3.4.0",
  }
```

**Comment by csvan** [comment]
Fix has been implemented: https://github.com/terser-js/terser/pull/254

**Comment by Dynogic** [comment]
Yikes, looks like next.js is broken too 😨

**Comment by Tunc88** [comment]
> _terser.default.minify

In my case it was _terser2.default.minify and it works also fine for me.

**Comment by Tunc88** [comment]
> I changed `_terser.default.minify` to `_terser.minify` and it works

In my case it was _terser2.default.minify and it works also fine for me.

**Comment by Hendrykes** [comment]
A bug in terser 3.16 which was released hours ago.
For npm users: run npm i terser@3.14
For yarn users: add the following field to package.json and then rerun yarn:

```
"resolutions": {
  "terser": "3.14.1"
}
```

**Comment by TomCosta** [comment]
Solution:
`npm install terser@3.14.1 --save-dev`
For me it solves!

**Comment by sameera207** [comment]
@TomCosta , I literally had this issue about 15 mins ago for an ionic 4 project. Found your solution, which you posed about 10 mins ago and worked perfectly, thanks :)

**Comment by dodanex** [comment]
Hello guys, the same problem for me when running nuxt generate, now I fixed using @TomCosta solution `npm install terser@3.14.1 --save-dev`, so thanks.
Hope this problem will be fixed in the future.

**Comment by sorxrob** [comment]
Running `npm install terser@3.14.1 --save-dev` fixed my Nuxt `npm run build` too. Thank you.

**Comment by TrySound** [comment]
FYI rollup plugin is not broken :)
https://github.com/TrySound/rollup-plugin-terser/blob/master/transform.js#L1

**Comment by mrmckeb** [comment]
This is also affecting Create React App. See https://github.com/facebook/create-react-app/issues/6334.

**Comment by vladimiry** [comment]
> FYI rollup plugin is not broken :)

One more instance of default exports should not be used at all, in my opinion.

**Comment by ksharlandjiev** [comment]
For everyone who are worried of their broken builds, here is a simple (temporary) fix, until this is fixed: 
1) edit package-lock.json
2) locate: "terser-webpack-plugin" and inside it's tree: change: "terser": "^3.8.1", to "terser": "3.14.1"

Cheers

**Comment by ksharlandjiev** [comment]
@cezarsmpio:
Install terser 3.14.1 as a separate dependency and update your package-lock
I’m running this on a pure react app, but it should also work for next.js
Also try to check the dependency tree when running your build to check if other dependency is installing terser 3.16.
If this is the case, again locate in your lock file and force downgrade do 3.14.1
Remember to remove the ^ in front of the version to lock to a specific one.
Good luck

**Comment by cezarsmpio** [comment]
Needed to use yarn instead of npm, here is what I've done as a temp fix:

1. Delete your package-lock.json
2. Add to your package.json
```
"resolutions": {
    "terser": "3.14.1"
},
```
3. `npm install terser@3.14.1 --save-dev`
4. Deploy

**Comment by mdix** [comment]
When doing the above trick, make sure to install the exact version (`--save-exact`) or else you'll end up with a broken first level dependency:

`npm install terser@3.14.1 --save-dev --save-exact`

**Comment by anujladia** [comment]
@mdix I am not using terser library directly in my package.json.
Third party libraries are using terser, so will this change help me be able to build my web app correctly?

**Comment by ksharlandjiev** [comment]
@anujladia check my suggestion, I was also with the same case.
Install terser 3.14.1 locally with —save-dev, modify package-lock and specify 3.14.1 and not anything else starting with ^ for any package using it

**Comment by anujladia** [comment]
@ksharlandjiev Hey thanks. But I have another quick question 
We ignore sending the package-lock to git from where it gets build and deployed 
So from now on should I send my package-lock everytime it is being pushed so that it always uses this package-lock.json rather than building it again on Gitlab and recreating it??
I never worked on package-lock. So have no idea about it

**Comment by sokra** [comment]
> We ignore sending the package-lock to git

Yes package-lock.json resp. yarn.lock should be commited and pushed.

**Comment by ksharlandjiev** [comment]
@anujladia, this is a side topic, but yes lock files should be added to prevent exactly this kind of scenarios with build processes

**Comment by sokra** [comment]
To summarize it: Everybody that gets a CI failure on the master branch or an error on production, probably didn't commit the lockfile. That's not how lockfiles work. They are there to fix your dependencies, so every dependency upgrade need to be done manually* in a PR, which is reviewed and tested by CI. This way no broken release (which happen, because everyone makes mistakes) could every break your production environment or even your development workflow.

* There are also services to automate this.

**Comment by vladimiry** [comment]
@anujladia if you build something on CI servers (Travis, Gitlab, etc) using npm consider executing `npm ci` there instead of `npm install`.

**Comment by riksnelders** [comment]
I'm getting a build error still using 3.14.1 from terser..
 Error: CSS minification error: Cannot read property 'type' of undefined. File: css/app.8384d281.css

**Comment by kopax** [comment]
@bendg25 it is `terser` plugin that cause to be block, or this plugin directly. `terser` as updated the way it exports it's file. This plugin needs or `terser` needs to provide backward compatibility. It is nothing related to angular.

**Comment by bendg25** [comment]
@kopax I don't directly include the terser plugin in my package.json.  So what is bringing this dependency into my scope?

**Comment by ksharlandjiev** [comment]
@bendg25 look at your package-lock.json and search for "terser".
I have suggested a fix somewhere up in the comments.

**Comment by csvan** [comment]
@bendg25 webpack uses the terser plugin by default unless you override it and use something else for minification.

**Comment by kopax** [comment]
@bendg25 run `npm ls terser` in your project. That doesn't mean that your `package.json` doesn't have a dependency named `terser` that one of your dependency doesn't have it in it's `package.json` dependencies. And this is done in chain through all your dependencies.

**Comment by bendg25** [comment]
@kopax so I have this: ─┬ @angular-devkit/build-angular@0.11.4
│ └─┬ terser-webpack-plugin@1.1.0
│   └── terser@3.16.0  deduped
└── terser@3.16.0 

Fix suggested by @ksharlandjiev does not work for me, as my release process runs npm install from a clean box.

**Comment by evilebottnawi** [comment]
WIP on this

**Comment by Carbammato** [comment]
With Angular 7, I updated my package-json to add:
`"Terser": "3.14.1" `
in the section `devDependencies`.

It's a workaround, but helps me to avoid that CI tries to download the latest version available (in my company, we don't push the `package-lock.json` in source control).

Hope this might help out while we wait for a proper solution. I'm following the thread.

**Comment by ksharlandjiev** [comment]
@kopax : 
1) clone everything locally, run npm install
2) follow my guide: install terser@3.14.1,  edit package-lock.json and pin 3.14.1 everywhere you can find it. 
3) commit package-lock.json to your repository.

run your build!
your build process and npm install will follow versions "locked" into your lock file.
That is why it is important to have this into your repository and available for any CI server to use.

**Comment by alasdairhurst** [comment]
@ksharlandjiev package-lock is generally quite good for applications but not libraries (since you won't be testing and building using the same dependencies that users of your library will end up with)

**Comment by vladimiry** [comment]
> @ksharlandjiev package-lock is generally quite good for applications but not libraries (since you won't be testing and building using the same dependencies that users of your library will end up with)

Locking the dependencies is useful even for libraries as it makes the build process reproducible.

**Comment by kopax** [comment]
Locking the dependencies is not that useful for libraries. You rather want to see things break in your CI and be warned about it. If you must lock your dependency to a certain dependencies, this should be the way to go.

**Comment by sidag95** [comment]
Awesome @pitops the workaround works, thanks

**Comment by manniL** [comment]
https://github.com/terser-js/terser/issues/251

Resolved

**Comment by afide1** [comment]
> The latest terser update (released an hour ago) breaks this plugin.
> 
> * Operating System:
> * Node Version: 10.12.0
> * NPM Version: 6.4.1
> * webpack Version: 4.29.0
> * terser-webpack-plugin Version: 1.2.1
> 
> ### Expected Behavior
> Terser to minify my code
> 
> ### Actual Behavior
> ```shell
> ERROR in js/main.6e4faa1e7d31caf0fa3b.js from Terser
> TypeError: Cannot read property 'minify' of undefined
>     at minify (/<path>/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
> ```
> 
> ### How Do We Reproduce?
> Delete yarn.lock
> 
> Install terser-webpack-plugin and try to run a production build where the plugin is called
> 
> ### workaround
> As a workaround for now if you use yarn you can add a resolution to a fixed terser version. Delete yarn.lock first and node_modules
> 
> Example (in your package.json)
> 
> ```
> "resolutions": {
>   "terser": "3.14.1"
> }
> ```
> For npm try the suggestion by @odedi

"Thank you!"

**Comment by pitops** [comment]
@afide1 Hey, its been fixed, all you need to do is update terser-webpack-plugin to v1.2.2 +
