### ISSUE TITLE
Map sourceMap to devtool

### ISSUE THREAD

**Issue by stevenvachon** [webpack-contrib/terser-webpack-plugin#71]
* Operating System: macOS 10.14.2
* Node Version: 10.15.0
* NPM Version: 6.4.1
* webpack Version: 4.29.3
* terser-webpack-plugin Version: 1.2.2

### Feature Proposal
Currently, the `sourceMap` option must be explicitly defined when it'd be much more convenient for it to rely on the value of Webpack's `devtool` option.

### Feature Use Case
Less verbose config

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by lakatostamas** [comment]
Can I send a PR for this one?

**Comment by evilebottnawi** [comment]
Yep, PR welcome

**Comment by nicholascm** [comment]
@evilebottnawi I have a branch with this change that is working for my use case, just working on tests:  https://github.com/webpack-contrib/terser-webpack-plugin/compare/master...nicholascm:set-sourcemap-based-on-webpack-config

**Comment by evilebottnawi** [comment]
Looks good, feel free to send a PR

**Comment by evilebottnawi** [comment]
Partial fixed in `2.0.0` version, other fixes possible only for `webpack@5`
