### ISSUE TITLE
optimized function changes behavour

### ISSUE THREAD

**Issue by roblan** [webpack-contrib/terser-webpack-plugin#73]
* Operating System: Mac OS
* Node Version: 11.9.0
* NPM Version: 6.8.0
* webpack Version: 4.29.5
* terser-webpack-plugin Version: 1.2.3

### Expected Behavior

function should behave like non minimized one.

### Actual Behavior

Terser plugin overoptimize function and changes it return params.

### Code

```js
module.exports = (function(constructor) {
  return constructor();
})(function() {
  return function(input) {
    var keyToMap = input.key;
    return {
      mappedKey: (function(value) {
        return value || "CONDITIONAL_DEFAULT_VALUE";
      })(keyToMap)
    };
  };
});
```

### How Do We Reproduce?

https://github.com/roblan/webpack_terser_bug/tree/master

**Comment by evilebottnawi** [comment]
We just wrapper around `terser`, please post issue in `terser` repo

**Comment by roblan** [comment]
@evilebottnawi - but code parsed through terser works just fine

**Comment by evilebottnawi** [comment]
@roblan we don't change code, only send to terser and return, maybe other plugin do this

**Comment by roblan** [comment]
@evilebottnawi have you looked into provided example? only difference is `minimizer: [new TerserPlugin()]` in webpack config

**Comment by evilebottnawi** [comment]
@roblan yes, and as i said above we don't change you code, all optimization do `terser`, if some optimization break code or do something wrong please post issue in `terser` repo https://github.com/terser-js/terser

**Comment by roblan** [comment]
ok, thanks. just realised that flags --compress --mangle makes all the difference here
