### ISSUE TITLE
Webpack v3 support

### ISSUE THREAD

**Issue by etripier** [webpack-contrib/terser-webpack-plugin#74]
First off: I'm a huge fan of the plugin and Terser in general. It's always nice when things run faster and produce better results.

### Feature Proposal
I know the issue title is probably going to elicit some groans, but it doesn't _seem_ like much is preventing this plugin from working on Webpack v3. I think it might just involve modifying the `index` file like so:

```javascript
if (compiler.hooks) {
  ...
} else {
  compiler.plugin('compilation', (compilation) => {
    if (this.options.sourceMap) {
      compilation.plugin('build-module', buildModuleFn);
    }
    compilation.plugin('optimize-chunk-assets', optimizeFn.bind(this, compilation));
  });
}
```

We'd lose out on the `contenthash` regeneration, but I don't think that's breaking for Webpack v3 users (or at least, we're used to the problem).

For those of us stuck with older versions of Webpack, this would significantly improve our build times and give us a sample of the benefits of v4!

I'd be happy to open a PR to make the needed changes if the idea seems appealing.

### Feature Use Case
This would be very helpful for developers stuck in the year 2016.

**Comment by evilebottnawi** [comment]
@etripier we officially don't support `webpack@3`, anyway you can send a PR and we can release this under `terser-webpack-plugin-legacy` name with supporting `webpack@3`. Anyway we strongly recommendation update `webpack`, because `webpack@5` will have some changes and it was incompatibility with `webpack@3`

**Comment by evilebottnawi** [comment]
Released https://www.npmjs.com/package/terser-webpack-plugin-legacy
