### ISSUE TITLE
What are the implications of setting "cache" to true?

### ISSUE THREAD

**Issue by evbo** [webpack-contrib/terser-webpack-plugin#76]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...
Please just add a 1 liner explaining what a "cache" is in the context of minification. 

In general I know what a cache is - some (local) storage of files/data to reuse for avoiding redundant regeneration of (if no changes exist) for faster build times. But if there were only benefits to adding a cache then why even include it as an option? What are the implications of setting cache to `true` (for the typical use case where someone _isn't_ using a custom minify - or is that the only reason you might not want to)?

### Your Proposal for Changes

Something like this:

Enable file caching. Default path to cache directory: `node_modules/.cache/terser-webpack-plugin`. Enabling this option will < improve build speed at the cost of...?  >

...

**Comment by evilebottnawi** [comment]
@evbo 
> In general I know what a cache is - some (local) storage of files/data to reuse for avoiding redundant regeneration of (if no changes exist) for faster build times. But if there were only benefits to adding a cache then why even include it as an option? What are the implications of setting cache to true (for the typical use case where someone isn't using a custom minify - or is that the only reason you might not want to)?

Some platform/os doesn't support filesystem (use memory instead) so you should setup this to `true`. We setup this as `true` by default for next major release. Also some people disable cache for CI (it is allow calculate first build time and for other cases).

> Enabling this option will < improve build speed at the cost of...? >

We can't say how it is improve build speed, it is depends on you system (filesystem) and hardware. 99% it is speed build, but in some cases it can decrease speed (example when you harddisk is overloaded).

**Comment by evilebottnawi** [comment]
Feel free to feedback
