### ISSUE TITLE
Function call disappear if there is a comment above it

### ISSUE THREAD

**Issue by NeeEoo** [webpack-contrib/terser-webpack-plugin#79]
* Operating System: Windows 10
* Node Version: v10.9.0
* NPM Version: 6.4.1
* webpack Version: 4.29.6
* terser-webpack-plugin Version: 1.2.3

### Expected Behavior

The registerCmd function call should not disappear when there is a comment above it

### Actual Behavior

The registerCmd function call disappears from the output

### Code

```js
/*registerCmd("cal", function(argv) { // Old code
   // ... 142 lines of private code
}, "cal - Shows a calendar")*/

registerCmd("cal", function(argv) { // New code
   // ... 154 lines of private code
}, "cal - Shows a calendar")
```

```js
const TerserPlugin = require('terser-webpack-plugin');
// ...
new TerserPlugin({
    terserOptions: {
        mangle: true,
        output: {
            comments: /@license/i
        },
        ecma: 8,
        compress: {
            unsafe: true,
            sequences: true,
            passes: 5
        },
        parallel: true
    },
    parallel: true
})
```

### How Do We Reproduce?

Cannot provide a repo because my project is closed source

**Comment by NeeEoo** [comment]
I found why the function call disappears it is because the old code comment had #__PURE__ so the function call became pure

**Comment by evilebottnawi** [comment]
We just wrapper around `terser` (https://github.com/terser-js/terser), if you think it is bug please open issue in their repo, we can't do something on our side (we don't modify your code, just send this code to `terser` and return output), thanks!
