### ISSUE TITLE
When used with Lerna, a cache directory is created in several different locations

### ISSUE THREAD

**Issue by damienwebdev** [webpack-contrib/terser-webpack-plugin#82]
* Operating System: `MacOS v10.14.3`
* Node Version: `v10.15.0`
* NPM Version:`6.7.0`
* Webpack Version: 
```
@angular-devkit/build-angular@0.13.1
  ├── terser-webpack-plugin@1.2.2 
  └─┬ webpack@4.29.0
    └── terser-webpack-plugin@1.2.2  deduped
```

### Expected Behavior
When using lerna for *hoisted* package management in a monorepo, when I do run `lerna run build` and it runs the build script in each of my packages, the resulting cache directory should be in my **root** `node_modules` of my project.

### Actual Behavior
When using lerna for **hoisted** package management, when I do run `lerna run build` and it runs the build script in each of my packages, `ng build` runs webpack with `terser-webpack-plugin` with the [`cache` flag set to true](https://github.com/renovate-bot/angular-cli/blob/bf52b26219ffc16bed2dd55716e21773b415fd2a/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L264). This generates a new `node_modules` directory in each of my source directories.

### How Do We Reproduce?

You can reproduce fairly easily by cloning: https://github.com/graycoreio/daffodil and then:

```
npm install -g lerna @angular/cli
lerna run build
look in apps/daffio/ and see a new node_modules folder
```

**Comment by evilebottnawi** [comment]
@damienwebdev we use https://github.com/avajs/find-cache-dir for detect cache directory, better create issue in their repo, as workaround you can setup path in configuration

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/avajs/find-cache-dir/issues/14

**Comment by damienwebdev** [comment]
@evilebottnawi See @sindresorhus 's [comment](https://github.com/avajs/find-cache-dir/issues/9#issuecomment-364163029) I don't think there are any plans to change this, so I think the next step is to find a different `find-cache-dir` implementation that allows for configuration, utilize it here, and then make changes in Lerna to take advantage of it.

**Comment by evilebottnawi** [comment]
@damienwebdev we provide cacheDir option, you can implement any behavior. You can add example to docs.
