### ISSUE TITLE
sourceMap url through terserOptions does not working

### ISSUE THREAD

**Issue by 29decibel** [webpack-contrib/terser-webpack-plugin#84]
* Operating System: Linux
* Node Version: 8
* webpack Version: 4.29.6
* terser-webpack-plugin Version: 1.2.3

### Expected Behavior
I am using the following to generate a customized sourceMappingURL according to [terserOptions section](https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions)
```javascript
// webpack.config.js
 // ......
  new TerserPlugin({
    sourceMap: true,
    terserOptions: {
      sourceMap: {
        file: '[name].map',
        url: 'https://my-host/[url]'
      }
    }
  }),
//....

```

I am expecting the source code to have the following at the bottom of the minified source code:
```
//# sourceMappingURL=https://my-host/app.xxxxxxx.js.map
```

### Actual Behavior

```
//# sourceMappingURL=app.xxxxxxx.js.map
```

Does terser-webpack-plugin ever support `sourceMap` option in `terserOptions` ? 

Thanks!

**Comment by evilebottnawi** [comment]
Answer https://stackoverflow.com/questions/38976873/how-to-change-sourcemappingurl-by-using-webpack
