### ISSUE TITLE
ERROR in main.js from Terser

### ISSUE THREAD

**Issue by zhongzhong0505** [webpack-contrib/terser-webpack-plugin#91]
* Operating System: iMac
* Node Version: v10.14.2
* NPM Version: 6.4.1
* webpack Version: 4.28.2
* terser-webpack-plugin Version: none

### Expected Behavior
success compile

### Actual Behavior
[0] ./src/a.js 951 bytes [built]
[1] ./src/index.js 1.01 KiB {0} [built]
[2] ./src/b.js 980 bytes [built]

ERROR in main.js from Terser
Unexpected token punc «(», expected name «from» [main.js:101,9]

### Code

```js
  // webpack.config.js
  // If your code blocks are over 20 lines, please paste a link to a gist
  // (https://gist.github.com).
const RemovePlugin = require('./src/plugin');

module.exports = {
  mode: 'production',
  optimization: {
    usedExports: true,
  },
  plugins: [
    new RemovePlugin()
  ],
  module:{
    rules: [
      {
        test: /\.m?js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
            plugins: ['@babel/plugin-syntax-dynamic-import']
          }
        }
      }
    ]
  }
};
```

// index.js
```js
  // additional code, HEY YO remove this block if you don't need it
//  S#RP(account)
import B from "./b";
//  E#RP(account)
export * from "./a";
class Main {
    init() {

    }
    initA() {

    }
}

new Main().init();
```
// plugin.js
```js
class RemovePlugin {
  apply(compiler) {
    compiler.hooks.compilation.tap("RemovePlugin", (compilation, callback) => {
      compilation.hooks.finishModules.tap(
        this.constructor.name,
        (modules) => {
            modules.forEach(m => {
                m._source._value = m._source._value.replace(/S#RP\(\w+\)/, '99099');
                console.log(m._source._value)
            });
        })

        // callback();
    // })
  })
}}
module.exports = RemovePlugin;

```

**Comment by evilebottnawi** [comment]
We just wrapper around terser, please open issue in terser repo, we can't do something on our side, but this looks like parser error, maybe something create invalid es code, please try to disable `RemovePlugin` or `@babel/plugin-syntax-dynamic-import` and try to build again.

**Comment by Alex-Willenbrink** [comment]
How do you disable the ```RemovePlugin```?

**Comment by swateek** [comment]
Facing this issue, don't have any solution yet.

**Comment by swateek** [comment]
Facing this issue, exact error is 

    ERROR in my_backend.js from Terser
    Invalid assignment

No solution yet.

**Comment by evilebottnawi** [comment]
@swateek you have invalid code `Invalid assignment`, or something wrong on terser side, open a issue in the terser repo

**Comment by LitileXueZha** [comment]
Here is a series of steps to locate the syntax error:

1. disable terser plugin and enable source map
2. run the output bundle `main.js` (without terser optimized)
3. review the same syntax error and map to source files, now you can know how to fix it

In my case, when enabled 'production' mode, the webpack `DefinePlugin` replace `process.env.NODE_ENV` to `"procution"`, so it throws a *Invlid assignment* error.

```javascript
// source file
process.env.NODE_ENV = 'production';

// webpack output file
"production" = 'production';
^
Invalid assignment
```

**Comment by rafael-ferreira-11** [comment]
> Here is a series of steps to locate the syntax error:
> 
> 1. disable terser plugin and enable source map
> 2. run the output bundle `main.js` (without terser optimized)
> 3. review the same syntax error and map to source files, now you can know how to fix it
> 
> In my case, when enabled 'production' mode, the webpack `DefinePlugin` replace `process.env.NODE_ENV` to `"procution"`, so it throws a _Invlid assignment_ error.
> 
> ```js
> // source file
> process.env.NODE_ENV = 'production';
> 
> // webpack output file
> "production" = 'production';
> ^
> Invalid assignment
> ```

Would you mind explaining how you  solved this issue @LitileXueZha ? I'm getting the same error on a quite big codebase
