### ISSUE TITLE
Isn't webpack switched to terser internally? Can I config terser without terser-webpack-plugin?

### ISSUE THREAD

**Issue by frederikhors** [webpack-contrib/terser-webpack-plugin#92]
Why should I need terser if webpack already uses it internally?

I need some non-default options, for example the comment strip in the final bundle and found around that I could do this:

```js
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  entry: /*...*/
  output: /*...*/,
  module: /*...*/,
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          output: {
            comments: false,
          },
        },
      }),
    ],
  },
}
```

Can I config webpack without require `terser-webpack-plugin`?

**Comment by evilebottnawi** [comment]
Answer in webpack repo

**Comment by womcauliff** [comment]
For any others who also arrived to this thread via google search results, the answer is located here: https://github.com/webpack/webpack/issues/9151
