### ISSUE TITLE
terser-webpack-plugin-legacy webpack.optimization.minify

### ISSUE THREAD

**Issue by roblevintennis** [webpack-contrib/terser-webpack-plugin#98]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

I'm using webpack v3.11 and we used to do:

`new webpack.optimize.UglifyJsPlugin()` but I switched to Terser and found the docs recommend:

```javascript
webpack.optimization = {
  minimizer: [new TerserPlugin()],
}
```

This confuses me as I wonder if `webpack.optimization` is even a thing in 3.x as the new webpack documentation [starts with](https://webpack.js.org/configuration/optimization/):

> Since version 4 webpack runs optimizations for you depending on the chosen mode...

So maybe it was a thing before but now does something different? Or, is it completely new in Webpack 4?

The reason I started looking in to this is I get an error in production mode signifying that minification isn't kicking in:

`Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build`

### Your Proposal for Changes

Make the legacy documentation less ambiguous and crystal clear for webpack 3 users.

**Comment by evilebottnawi** [comment]
https://reactjs.org/docs/optimizing-performance.html#webpack
```js
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify('production')
})
```

**Comment by roblevintennis** [comment]
I have:

```
if (production) {
  plugins.push(
    ...prodLikePlugins,
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      },
    }),
  );
  webpack.optimization = {
     minimizer: [new TerserPlugin()],
  };
}
```

`production` is just a boolean assume it `true` and `webpack` has been imported

**Comment by roblevintennis** [comment]
@evilebottnawi Hey, just for posterity for anyone else that has this problem and since the -legacy is so new, I figured out the issue in our environment which is Chrome Version 74.0.3729.157 (Official Build) (64-bit) on a macbook with mohave 10.14.4 (18E226), webpack v3.11 and babel 7 (if all that matters).

I can repro this bug repeatedly if I toggle React Developer Tools
 extension! (version 3.6.0):

`Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build`

It might be unique to our exact env / code / etc., but it might be worthwhile to see if others have this.
