### ISSUE TITLE
Stackoverflow in very specific code scenario

### ISSUE THREAD

**Issue by mifopen** [webpack-contrib/terser-webpack-plugin#99]
- Operating System: macOS Mojave 10.14.5
- Node Version: 12.4
- yarn Version: 1.17.0
- webpack Version: 4.35.0
- terser-webpack-plugin Version: default for this webpack version

### Expected Behavior
Should not crash =)
I have tried to turn off terser-webpack-plugin and minify it with the same version of terser and it works

### Actual Behavior
```
ERROR in main.js from Terser
RangeError: Maximum call stack size exceeded
```

### How Do We Reproduce?
```
git clone https://github.com/mifopen/terser-webpack-plugin-bug.git
cd terser-webpack-plugin-bug
yarn install
yarn build
```

**Comment by Corky3892** [comment]
Looks like issue is introduced in Webpack 4.26.0 - rolling backwards to 4.25.0 and bundle completes successfully.

**Comment by evilebottnawi** [comment]
@Corky3892 no bugs with `4.25.0` and `4.26.0`

**Comment by evilebottnawi** [comment]
Please update `terser-webpack-plugin` to latest version, no problems
